/* RapidRemove — Bestellprozess (Redesign 10/2026): NUR die neuen Texte.
 * Alles, was es schon übersetzt gibt (Überschriften, AGB-/FAGG-Einwilligung,
 * Presse-Formular, Bewertungs-Auswahl, Schutz-Namen …), kommt weiterhin aus den
 * bestehenden Blöcken in Wizard.jsx / i18n — hier stehen nur Strings, die das
 * neue Design zusätzlich braucht. Fehlende Sprache → Englisch. */

const de = {
  sub0: "Wählen Sie die gewünschte Leistung.",
  badgeTop: "Am häufigsten gewählt",
  tiles: {
    delete: ["Google-Unternehmensprofil löschen", "Das Profil wird mitsamt allen Bewertungen dauerhaft entfernt."],
    reviews: ["Einzelne Bewertungen löschen", "Ausgewählte Bewertungen werden entfernt, das Profil bleibt bestehen."],
    press: ["Negative Presse oder Suchergebnisse", "Ein Artikel oder Google-Treffer, der verschwinden soll."],
    unsure: ["Nicht sicher?", "Zwei kurze Fragen, dann leiten wir Sie weiter."],
  },
  labelsA: ["Firmenname", "Profilsuche", "Bestätigen", "Leistung", "Bewertungen", "Kasse", "Fertig"],
  labelsB: ["Firmenname", "Profilsuche", "Bestätigen", "Leistung", "Schutz", "Kasse", "Fertig"],
  stepOf: (n, t) => ["Schritt " + n, " von " + t],
  eta2: "ca. 2 Min.", eta1: "ca. 1 Min.", almost: "Fast geschafft", doneLbl: "Fertig",
  expert: "Mit Google-Experten sprechen", online: "Jetzt erreichbar",
  sub1: "Wir suchen Ihr Google-Unternehmensprofil.", find: "Profil finden",
  searchH: "Wir suchen Ihr Profil …", searchSub: (n) => ["Einen Moment – wir durchsuchen Google Maps nach ", n, "."],
  checkH: "Wir prüfen Ihr Profil …", checkSub: (n) => ["Einen Moment – wir prüfen ", n, "."],
  st: ["Google Maps durchsuchen", "Profil abgleichen", "Löschbarkeit prüfen"],
  altNotMineSub: "Mit anderem Namen erneut suchen", altNotFound: "Profil nicht gefunden?",
  altNotFoundA: "Links zu den Bewertungen eingeben", altNotFoundB: "Google-Maps-Link eingeben",
  svcH: "Was dürfen wir für Sie tun?", svcSub: "Wählen Sie die passende Leistung. Bezahlt wird erst nach erfolgreicher Löschung.",
  svcOk: "Ihr Profil kann gelöscht werden",
  svc1: ["Profil löschen", "Das Profil verschwindet dauerhaft – und mit ihm alle Bewertungen.", ["Alle Bewertungen weg", "Meist in 24 h"]],
  svc2: ["Profil löschen + Neustart", "Wir löschen das alte Profil und richten ein neues ein – mit 0 Bewertungen.", ["Neues, verifiziertes Profil", "Sauberer Neuanfang"]],
  reviewsNA: "Einzelne Bewertungen löschen wir für Profile in Deutschland und Österreich nicht. Möglich ist die Löschung des ganzen Profils.",
  naH: (c) => "Einzelne Bewertungen löschen wir in {c} nicht".replace("{c}", c), naSub: (c) => "Ihr Profil liegt in {c}. Wegen der Rechtslage dort dürfen wir einzelne Google-Bewertungen nicht entfernen, das ist Anwälten vorbehalten. Für Ihr Profil gibt es diese Möglichkeit:".replace("{c}", c), naOpts: "Diese Optionen gibt es für Ihr Profil", naWrong: "Falsches Profil? Erneut suchen", naLegal: "Allgemeine Information, keine Rechtsberatung.",
  change: "Ändern", riskT: "Kein Erfolg, keine Kosten.", riskD: "Sie zahlen erst, wenn das Profil tatsächlich gelöscht ist.",
  ldSub: (n) => ["Wir holen alle Bewertungen von ", n, " aus Google Maps."], ldFound: "Bewertungen gefunden",
  nRev: (n) => (n === 1 ? "1 Bewertung" : n + " Bewertungen"), selAll: "Alle auswählen", selNone: "Auswahl aufheben",
  noText: "Bewertung ohne Text",
  tag: { std: "ca. 90 %", legal: "über 90 %", sw: "Vorab-Prüfung" },
  cat: { std: "Bis 4 Wochen", legal: "Älter als 4 Wochen", nt: "Ohne Text", sw: "Spezial-Software" },
  selN: (n) => (!n ? "Keine Bewertung ausgewählt" : n === 1 ? "1 Bewertung ausgewählt" : n + " Bewertungen ausgewählt"),
  selShort: (n) => (n ? n + " ausgewählt" : "Keine ausgewählt"), pickOne: "Wählen Sie mindestens eine Bewertung.",
  nudge: (k, p) => (k === 1 ? "Noch 1 Bewertung" : "Noch " + k + " Bewertungen") + " bis −" + p + " %",
  toCo: "Weiter zur Kasse", payAfter: "Zahlung erst nach erfolgreicher Löschung", subtotal: "Zwischensumme",
  sheet: {
    t1: ["Bis 4 Wochen alt", "Direkte Meldung bei Google", "ca. 90 % Erfolgschance"],
    t2: ["Älter als 4 Wochen", "Zuerst rechtlicher Hinweis an Google", "über 90 % Erfolgschance"],
    t3: ["Ohne Text oder aus den USA", "Nur mit Spezial-Software möglich. Wir prüfen vorab, ob es klappt."],
    per: "pro Bewertung", from: (n) => "ab " + n, riskR: " Sie zahlen erst, wenn die Bewertung gelöscht ist.",
  },
  protH: "Schutz vor erneuter Veröffentlichung",
  protSub: "Gelöschte Profile können wieder auftauchen. Mit Schutz entfernen wir sie erneut – kostenlos.",
  protD: { monthly: "Erneute Löschung kostenlos, wann immer Sie es brauchen.", monitor: "Wir prüfen täglich und löschen automatisch – ohne Ihr Zutun.", lifetime: "Einmal zahlen, für immer geschützt – inklusive Überwachung." },
  protNone: "Ohne Schutz", protNoneD: "Kann auch später noch hinzugebucht werden.", perMonth: " / Monat", cancel: "Monatlich kündbar", once: "einmalig",
  warnB: "Ohne Schutz löschen wir ein wieder aufgetauchtes Profil nicht kostenlos.", warnR: " Das Risiko einer erneuten Veröffentlichung tragen Sie dann selbst.",
  exT: "So kann Ihr Profil zurückkommen", exN: ["Dritte – oft Mitbewerber – melden es neu an", "Google übernimmt Daten von Websites", "Profil ist wieder auf Google Maps"],
  yourSel: "Ihre Auswahl", fromDel: "ab Löschung", today: "Heute fällig", billNote: "Abrechnung erst nach erfolgreicher Löschung.", todayShort: (v) => "Heute " + v,
  coSub: "Nur das Nötigste. Bezahlt wird erst nach erfolgreicher Löschung.",
  f: { name: "Ihr Name", email: "E-Mail", phone: "Telefon", optional: "optional", company: "Unternehmen" },
  order: "Kostenpflichtig bestellen", nothingToday: "Heute wird nichts abgebucht",
  payOnSuccess: "Zahlung nach Erfolg", total: "Gesamt bei Erfolg", how: "Wie wird abgerechnet?",
  howA: [["Wir prüfen und starten.", " Sobald im Dashboard eine Zahlungsart hinterlegt ist, legen wir los."], ["Sie zahlen pro Löschung.", " Wird nur eine von zwei Bewertungen entfernt, zahlen Sie nur diese."], ["Kein Erfolg, keine Kosten.", " Klappt es nicht, zahlen Sie nichts."]],
  howB: [["Wir starten sofort.", " Alle nächsten Schritte bekommen Sie per E-Mail."], ["Abrechnung nach Löschung.", " Erst wenn das Profil entfernt ist, kommen Zahlungslink und Rechnung – ein Schutz startet ab dann."], ["Kein Erfolg, keine Kosten.", " Klappt es nicht, zahlen Sie nichts."]],
  lineSub: { std: "Direkte Meldung bei Google", legal: "Rechtlicher Hinweis an Google", nt: "Spezial-Software · Vorab-Prüfung" },
  delN: (n) => (n === 1 ? "1 Bewertung löschen" : n + " Bewertungen löschen"),
  expressSub: "Bearbeitung in ~6 Std.",
  verified: "Verifizierte Bewertung", tpFoot: (r, n) => [r, " aus " + n + " Bewertungen auf Trustpilot"],
  thanksH: "Vielen Dank.", thanksSub: "Ihre Bestellung ist eingegangen. Die Bestätigung kommt per E-Mail – wir melden uns innerhalb von 24 Stunden.", newOrder: "Neue Bestellung",
  sending: "Bestellung wird gesendet …",
};

const en = {
  sub0: "Choose the service you need.",
  badgeTop: "Most chosen",
  tiles: {
    delete: ["Delete Google Business Profile", "The profile is permanently removed, together with all its reviews."],
    reviews: ["Delete individual reviews", "Selected reviews are removed, the profile itself stays."],
    press: ["Negative press or search results", "An article or Google result that should disappear."],
    unsure: ["Not sure?", "Two quick questions, then we'll point you the right way."],
  },
  labelsA: ["Business", "Profile search", "Confirm", "Service", "Reviews", "Checkout", "Done"],
  labelsB: ["Business", "Profile search", "Confirm", "Service", "Protection", "Checkout", "Done"],
  stepOf: (n, t) => ["Step " + n, " of " + t],
  eta2: "approx. 2 min", eta1: "approx. 1 min", almost: "Almost done", doneLbl: "Done",
  expert: "Talk to a Google expert", online: "Available now",
  sub1: "We'll look up your Google Business Profile.", find: "Find profile",
  searchH: "Looking for your profile …", searchSub: (n) => ["One moment – we're searching Google Maps for ", n, "."],
  checkH: "Checking your profile …", checkSub: (n) => ["One moment – we're checking ", n, "."],
  st: ["Searching Google Maps", "Matching the profile", "Checking removability"],
  altNotMineSub: "Search again with a different name", altNotFound: "Profile not found?",
  altNotFoundA: "Enter links to the reviews", altNotFoundB: "Enter a Google Maps link",
  svcH: "What can we do for you?", svcSub: "Choose the right service. You only pay after a successful removal.",
  svcOk: "Your profile can be deleted",
  svc1: ["Delete profile", "The profile disappears for good – and all its reviews with it.", ["All reviews gone", "Usually within 24 h"]],
  svc2: ["Delete profile + fresh start", "We delete the old profile and set up a new one – with 0 reviews.", ["New, verified profile", "A clean restart"]],
  reviewsNA: "We don't remove individual reviews for profiles in Germany and Austria. Deleting the whole profile is possible.",
  naH: (c) => "Review removal isn't possible in {c}".replace("{c}", c), naSub: (c) => "Your profile is located in {c}. Due to the legal situation there, we aren't allowed to remove individual Google reviews; this is reserved for lawyers. Here's what we can do for your profile instead:".replace("{c}", c), naOpts: "Available options for your profile", naWrong: "Wrong profile? Search again", naLegal: "General information, not legal advice.",
  change: "Change", riskT: "No success, no fee.", riskD: "You only pay once the profile has actually been deleted.",
  ldSub: (n) => ["We're fetching all reviews of ", n, " from Google Maps."], ldFound: "reviews found",
  nRev: (n) => (n === 1 ? "1 review" : n + " reviews"), selAll: "Select all", selNone: "Clear selection",
  noText: "Review without text",
  tag: { std: "approx. 90%", legal: "over 90%", sw: "Pre-check" },
  cat: { std: "Up to 4 weeks", legal: "Older than 4 weeks", nt: "No text", sw: "Special software" },
  selN: (n) => (!n ? "No review selected" : n === 1 ? "1 review selected" : n + " reviews selected"),
  selShort: (n) => (n ? n + " selected" : "None selected"), pickOne: "Select at least one review.",
  nudge: (k, p) => (k === 1 ? "1 more review" : k + " more reviews") + " for −" + p + "%",
  toCo: "Continue to checkout", payAfter: "Payment only after successful removal", subtotal: "Subtotal",
  sheet: {
    t1: ["Up to 4 weeks old", "Direct report to Google", "approx. 90% success rate"],
    t2: ["Older than 4 weeks", "Legal notice to Google first", "over 90% success rate"],
    t3: ["No text or from the USA", "Only possible with special software. We check upfront whether it works."],
    per: "per review", from: (n) => "from " + n, riskR: " You only pay once the review has been removed.",
  },
  protH: "Protection against re-publication",
  protSub: "Deleted profiles can reappear. With protection, we remove them again – free of charge.",
  protD: { monthly: "Free re-removal whenever you need it.", monitor: "We check daily and remove it automatically – no action needed.", lifetime: "Pay once, protected forever – monitoring included." },
  protNone: "No protection", protNoneD: "Can still be added later.", perMonth: " / month", cancel: "Cancel monthly", once: "one-time",
  warnB: "Without protection, we won't remove a reappeared profile for free.", warnR: " You then carry the risk of it being published again yourself.",
  exT: "How your profile can come back", exN: ["Third parties – often competitors – register it again", "Google pulls in data from websites", "The profile is back on Google Maps"],
  yourSel: "Your selection", fromDel: "from removal", today: "Due today", billNote: "Billed only after a successful removal.", todayShort: (v) => "Today " + v,
  coSub: "Just the essentials. You only pay after a successful removal.",
  f: { name: "Your name", email: "Email", phone: "Phone", optional: "optional", company: "Business" },
  order: "Place order with obligation to pay", nothingToday: "Nothing is charged today",
  payOnSuccess: "Payment after success", total: "Total on success", how: "How does billing work?",
  howA: [["We check and start.", " As soon as a payment method is saved in your dashboard, we get going."], ["You pay per removal.", " If only one of two reviews is removed, you only pay for that one."], ["No success, no fee.", " If it doesn't work, you pay nothing."]],
  howB: [["We start right away.", " You'll receive all next steps by email."], ["Billed after removal.", " Only once the profile is gone do you get the payment link and invoice – any protection starts from then."], ["No success, no fee.", " If it doesn't work, you pay nothing."]],
  lineSub: { std: "Direct report to Google", legal: "Legal notice to Google", nt: "Special software · pre-check" },
  delN: (n) => (n === 1 ? "Remove 1 review" : "Remove " + n + " reviews"),
  expressSub: "Handled in ~6 h",
  verified: "Verified review", tpFoot: (r, n) => [r, " from " + n + " reviews on Trustpilot"],
  thanksH: "Thank you.", thanksSub: "Your order has been received. The confirmation is on its way by email – we'll be in touch within 24 hours.", newOrder: "New order",
  sending: "Sending your order …",
};

const es = {
  ...en,
  sub0: "Elige el servicio que necesitas.", badgeTop: "El más elegido",
  tiles: {
    delete: ["Eliminar perfil de empresa de Google", "El perfil se elimina de forma permanente junto con todas sus reseñas."],
    reviews: ["Eliminar reseñas concretas", "Se eliminan las reseñas seleccionadas; el perfil se mantiene."],
    press: ["Prensa negativa o resultados de búsqueda", "Un artículo o resultado de Google que debe desaparecer."],
    unsure: ["¿No estás seguro?", "Dos preguntas rápidas y te indicamos el camino."],
  },
  labelsA: ["Empresa", "Búsqueda", "Confirmar", "Servicio", "Reseñas", "Pago", "Listo"],
  labelsB: ["Empresa", "Búsqueda", "Confirmar", "Servicio", "Protección", "Pago", "Listo"],
  stepOf: (n, t) => ["Paso " + n, " de " + t],
  eta2: "aprox. 2 min", eta1: "aprox. 1 min", almost: "Casi listo", doneLbl: "Listo",
  expert: "Hablar con un experto en Google", online: "Disponible ahora",
  sub1: "Buscamos tu perfil de empresa en Google.", find: "Buscar perfil",
  searchH: "Buscando tu perfil …", searchSub: (n) => ["Un momento: estamos buscando ", n, " en Google Maps."],
  checkH: "Comprobando tu perfil …", checkSub: (n) => ["Un momento: estamos comprobando ", n, "."],
  st: ["Buscando en Google Maps", "Comparando el perfil", "Comprobando si se puede eliminar"],
  altNotMineSub: "Buscar de nuevo con otro nombre", altNotFound: "¿No encuentras el perfil?",
  altNotFoundA: "Introducir enlaces a las reseñas", altNotFoundB: "Introducir un enlace de Google Maps",
  svcH: "¿Qué podemos hacer por ti?", svcSub: "Elige el servicio adecuado. Solo pagas tras una eliminación exitosa.",
  svcOk: "Tu perfil se puede eliminar",
  svc1: ["Eliminar perfil", "El perfil desaparece para siempre, y con él todas las reseñas.", ["Todas las reseñas fuera", "Normalmente en 24 h"]],
  svc2: ["Eliminar perfil + nuevo comienzo", "Eliminamos el perfil antiguo y creamos uno nuevo, con 0 reseñas.", ["Perfil nuevo y verificado", "Un comienzo limpio"]],
  reviewsNA: "No eliminamos reseñas concretas de perfiles en Alemania y Austria. Sí es posible eliminar el perfil completo.",
  naH: (c) => "No eliminamos reseñas concretas en {c}".replace("{c}", c), naSub: (c) => "Tu perfil está en {c}. Por la situación legal allí no podemos eliminar reseñas concretas de Google; eso está reservado a abogados. Para tu perfil existe esta opción:".replace("{c}", c), naOpts: "Opciones disponibles para tu perfil", naWrong: "¿Perfil equivocado? Buscar de nuevo", naLegal: "Información general, no asesoramiento jurídico.",
  change: "Cambiar", riskT: "Sin éxito, sin coste.", riskD: "Solo pagas cuando el perfil se haya eliminado realmente.",
  ldSub: (n) => ["Estamos cargando todas las reseñas de ", n, " desde Google Maps."], ldFound: "reseñas encontradas",
  nRev: (n) => (n === 1 ? "1 reseña" : n + " reseñas"), selAll: "Seleccionar todas", selNone: "Quitar selección",
  noText: "Reseña sin texto",
  tag: { std: "aprox. 90 %", legal: "más del 90 %", sw: "Comprobación previa" },
  cat: { std: "Hasta 4 semanas", legal: "Más de 4 semanas", nt: "Sin texto", sw: "Software especial" },
  selN: (n) => (!n ? "Ninguna reseña seleccionada" : n === 1 ? "1 reseña seleccionada" : n + " reseñas seleccionadas"),
  selShort: (n) => (n ? n + " seleccionadas" : "Ninguna"), pickOne: "Selecciona al menos una reseña.",
  nudge: (k, p) => (k === 1 ? "1 reseña más" : k + " reseñas más") + " para −" + p + " %",
  toCo: "Continuar al pago", payAfter: "Pago solo tras una eliminación exitosa", subtotal: "Subtotal",
  sheet: {
    t1: ["Hasta 4 semanas", "Denuncia directa a Google", "aprox. 90 % de éxito"],
    t2: ["Más de 4 semanas", "Primero un aviso legal a Google", "más del 90 % de éxito"],
    t3: ["Sin texto o de EE. UU.", "Solo posible con software especial. Comprobamos antes si funciona."],
    per: "por reseña", from: (n) => "desde " + n, riskR: " Solo pagas cuando la reseña se haya eliminado.",
  },
  protH: "Protección contra una nueva publicación",
  protSub: "Los perfiles eliminados pueden volver a aparecer. Con protección, los eliminamos de nuevo gratis.",
  protD: { monthly: "Nueva eliminación gratuita siempre que la necesites.", monitor: "Comprobamos a diario y eliminamos automáticamente, sin que hagas nada.", lifetime: "Pagas una vez, protegido para siempre, con monitorización incluida." },
  protNone: "Sin protección", protNoneD: "Se puede añadir más adelante.", perMonth: " / mes", cancel: "Cancelable cada mes", once: "pago único",
  warnB: "Sin protección, no eliminamos gratis un perfil que vuelva a aparecer.", warnR: " El riesgo de una nueva publicación corre entonces por tu cuenta.",
  exT: "Así puede volver tu perfil", exN: ["Terceros, a menudo competidores, lo registran de nuevo", "Google toma datos de sitios web", "El perfil vuelve a estar en Google Maps"],
  yourSel: "Tu selección", fromDel: "desde la eliminación", today: "A pagar hoy", billNote: "Se factura solo tras una eliminación exitosa.", todayShort: (v) => "Hoy " + v,
  coSub: "Solo lo imprescindible. Pagas tras una eliminación exitosa.",
  f: { name: "Tu nombre", email: "Correo electrónico", phone: "Teléfono", optional: "opcional", company: "Empresa" },
  order: "Pedido con obligación de pago", nothingToday: "Hoy no se cobra nada",
  payOnSuccess: "Pago tras el éxito", total: "Total si hay éxito", how: "¿Cómo se factura?",
  howA: [["Comprobamos y empezamos.", " En cuanto haya un método de pago guardado en tu panel, empezamos."], ["Pagas por eliminación.", " Si solo se elimina una de dos reseñas, pagas solo esa."], ["Sin éxito, sin coste.", " Si no funciona, no pagas nada."]],
  howB: [["Empezamos enseguida.", " Recibirás todos los siguientes pasos por email."], ["Facturación tras la eliminación.", " Solo cuando el perfil haya desaparecido recibes el enlace de pago y la factura; la protección empieza entonces."], ["Sin éxito, sin coste.", " Si no funciona, no pagas nada."]],
  lineSub: { std: "Denuncia directa a Google", legal: "Aviso legal a Google", nt: "Software especial · comprobación previa" },
  delN: (n) => (n === 1 ? "Eliminar 1 reseña" : "Eliminar " + n + " reseñas"),
  expressSub: "Gestión en ~6 h",
  verified: "Reseña verificada", tpFoot: (r, n) => [r, " de " + n + " reseñas en Trustpilot"],
  thanksH: "Muchas gracias.", thanksSub: "Hemos recibido tu pedido. La confirmación llegará por email; nos pondremos en contacto en 24 horas.", newOrder: "Nuevo pedido",
  sending: "Enviando tu pedido …",
};

const fr = {
  ...en,
  sub0: "Choisissez la prestation souhaitée.", badgeTop: "Le plus choisi",
  tiles: {
    delete: ["Supprimer la fiche d'établissement Google", "La fiche est supprimée définitivement, avec tous ses avis."],
    reviews: ["Supprimer des avis isolés", "Les avis sélectionnés sont supprimés, la fiche reste en ligne."],
    press: ["Presse négative ou résultats de recherche", "Un article ou un résultat Google qui doit disparaître."],
    unsure: ["Pas sûr ?", "Deux questions rapides, puis nous vous orientons."],
  },
  labelsA: ["Entreprise", "Recherche", "Confirmer", "Prestation", "Avis", "Paiement", "Terminé"],
  labelsB: ["Entreprise", "Recherche", "Confirmer", "Prestation", "Protection", "Paiement", "Terminé"],
  stepOf: (n, t) => ["Étape " + n, " sur " + t],
  eta2: "env. 2 min", eta1: "env. 1 min", almost: "Presque terminé", doneLbl: "Terminé",
  expert: "Parler à un expert Google", online: "Disponible maintenant",
  sub1: "Nous recherchons votre fiche d'établissement Google.", find: "Trouver la fiche",
  searchH: "Nous cherchons votre fiche …", searchSub: (n) => ["Un instant – nous recherchons ", n, " sur Google Maps."],
  checkH: "Nous vérifions votre fiche …", checkSub: (n) => ["Un instant – nous vérifions ", n, "."],
  st: ["Recherche sur Google Maps", "Correspondance de la fiche", "Vérification de la suppression"],
  altNotMineSub: "Rechercher à nouveau avec un autre nom", altNotFound: "Fiche introuvable ?",
  altNotFoundA: "Saisir les liens vers les avis", altNotFoundB: "Saisir un lien Google Maps",
  svcH: "Que pouvons-nous faire pour vous ?", svcSub: "Choisissez la prestation adaptée. Vous ne payez qu'après une suppression réussie.",
  svcOk: "Votre fiche peut être supprimée",
  svc1: ["Supprimer la fiche", "La fiche disparaît définitivement – et tous ses avis avec elle.", ["Tous les avis supprimés", "En 24 h en général"]],
  svc2: ["Supprimer la fiche + nouveau départ", "Nous supprimons l'ancienne fiche et en créons une nouvelle – avec 0 avis.", ["Nouvelle fiche vérifiée", "Un nouveau départ propre"]],
  reviewsNA: "Nous ne supprimons pas d'avis isolés pour les fiches en Allemagne et en Autriche. La suppression de la fiche entière est possible.",
  naH: (c) => "Nous ne supprimons pas d'avis isolés en {c}".replace("{c}", c), naSub: (c) => "Votre fiche se trouve en {c}. En raison de la situation juridique, nous ne pouvons pas supprimer d'avis Google isolés ; c'est réservé aux avocats. Voici ce que nous pouvons faire pour votre fiche :".replace("{c}", c), naOpts: "Options disponibles pour votre fiche", naWrong: "Mauvaise fiche ? Rechercher à nouveau", naLegal: "Information générale, pas un conseil juridique.",
  change: "Modifier", riskT: "Pas de succès, pas de frais.", riskD: "Vous ne payez que lorsque la fiche a réellement été supprimée.",
  ldSub: (n) => ["Nous récupérons tous les avis de ", n, " sur Google Maps."], ldFound: "avis trouvés",
  nRev: (n) => (n === 1 ? "1 avis" : n + " avis"), selAll: "Tout sélectionner", selNone: "Tout désélectionner",
  noText: "Avis sans texte",
  tag: { std: "env. 90 %", legal: "plus de 90 %", sw: "Vérification préalable" },
  cat: { std: "Jusqu'à 4 semaines", legal: "Plus de 4 semaines", nt: "Sans texte", sw: "Logiciel spécial" },
  selN: (n) => (!n ? "Aucun avis sélectionné" : n === 1 ? "1 avis sélectionné" : n + " avis sélectionnés"),
  selShort: (n) => (n ? n + " sélectionné(s)" : "Aucun"), pickOne: "Sélectionnez au moins un avis.",
  nudge: (k, p) => (k === 1 ? "Encore 1 avis" : "Encore " + k + " avis") + " pour −" + p + " %",
  toCo: "Passer au paiement", payAfter: "Paiement uniquement après suppression réussie", subtotal: "Sous-total",
  sheet: {
    t1: ["Jusqu'à 4 semaines", "Signalement direct à Google", "env. 90 % de réussite"],
    t2: ["Plus de 4 semaines", "D'abord une notification juridique à Google", "plus de 90 % de réussite"],
    t3: ["Sans texte ou des États-Unis", "Possible uniquement avec un logiciel spécial. Nous vérifions d'abord si c'est faisable."],
    per: "par avis", from: (n) => "dès " + n, riskR: " Vous ne payez que lorsque l'avis a été supprimé.",
  },
  protH: "Protection contre une nouvelle publication",
  protSub: "Les fiches supprimées peuvent réapparaître. Avec la protection, nous les supprimons à nouveau – gratuitement.",
  protD: { monthly: "Nouvelle suppression gratuite dès que vous en avez besoin.", monitor: "Nous vérifions chaque jour et supprimons automatiquement – sans action de votre part.", lifetime: "Payez une fois, protégé pour toujours – surveillance incluse." },
  protNone: "Sans protection", protNoneD: "Peut encore être ajoutée plus tard.", perMonth: " / mois", cancel: "Résiliable chaque mois", once: "unique",
  warnB: "Sans protection, nous ne supprimons pas gratuitement une fiche réapparue.", warnR: " Vous assumez alors vous-même le risque d'une nouvelle publication.",
  exT: "Comment votre fiche peut revenir", exN: ["Des tiers – souvent des concurrents – la recréent", "Google reprend des données de sites web", "La fiche est de retour sur Google Maps"],
  yourSel: "Votre sélection", fromDel: "dès la suppression", today: "À payer aujourd'hui", billNote: "Facturé uniquement après une suppression réussie.", todayShort: (v) => "Aujourd'hui " + v,
  coSub: "Juste l'essentiel. Vous ne payez qu'après une suppression réussie.",
  f: { name: "Votre nom", email: "E-mail", phone: "Téléphone", optional: "facultatif", company: "Entreprise" },
  order: "Commande avec obligation de paiement", nothingToday: "Rien n'est débité aujourd'hui",
  payOnSuccess: "Paiement après succès", total: "Total en cas de succès", how: "Comment se fait la facturation ?",
  howA: [["Nous vérifions et démarrons.", " Dès qu'un moyen de paiement est enregistré dans votre espace, nous commençons."], ["Vous payez par suppression.", " Si un seul avis sur deux est supprimé, vous ne payez que celui-là."], ["Pas de succès, pas de frais.", " Si cela ne fonctionne pas, vous ne payez rien."]],
  howB: [["Nous démarrons immédiatement.", " Vous recevez toutes les étapes suivantes par e-mail."], ["Facturation après suppression.", " Ce n'est qu'une fois la fiche supprimée que vous recevez le lien de paiement et la facture – la protection démarre alors."], ["Pas de succès, pas de frais.", " Si cela ne fonctionne pas, vous ne payez rien."]],
  lineSub: { std: "Signalement direct à Google", legal: "Notification juridique à Google", nt: "Logiciel spécial · vérification préalable" },
  delN: (n) => (n === 1 ? "Supprimer 1 avis" : "Supprimer " + n + " avis"),
  expressSub: "Traitement en ~6 h",
  verified: "Avis vérifié", tpFoot: (r, n) => [r, " sur " + n + " avis Trustpilot"],
  thanksH: "Merci beaucoup.", thanksSub: "Votre commande a bien été reçue. La confirmation arrive par e-mail – nous revenons vers vous sous 24 heures.", newOrder: "Nouvelle commande",
  sending: "Envoi de votre commande …",
};

const it = {
  ...en,
  sub0: "Scegli il servizio di cui hai bisogno.", badgeTop: "Il più scelto",
  tiles: {
    delete: ["Eliminare il profilo dell'attività su Google", "Il profilo viene rimosso definitivamente, insieme a tutte le recensioni."],
    reviews: ["Eliminare singole recensioni", "Le recensioni selezionate vengono rimosse, il profilo resta."],
    press: ["Stampa negativa o risultati di ricerca", "Un articolo o un risultato Google che deve sparire."],
    unsure: ["Non sei sicuro?", "Due domande veloci e ti indirizziamo."],
  },
  labelsA: ["Attività", "Ricerca", "Conferma", "Servizio", "Recensioni", "Cassa", "Fatto"],
  labelsB: ["Attività", "Ricerca", "Conferma", "Servizio", "Protezione", "Cassa", "Fatto"],
  stepOf: (n, t) => ["Passo " + n, " di " + t],
  eta2: "ca. 2 min", eta1: "ca. 1 min", almost: "Quasi fatto", doneLbl: "Fatto",
  expert: "Parla con un esperto Google", online: "Disponibile ora",
  sub1: "Cerchiamo il tuo profilo dell'attività su Google.", find: "Trova profilo",
  searchH: "Cerchiamo il tuo profilo …", searchSub: (n) => ["Un attimo: stiamo cercando ", n, " su Google Maps."],
  checkH: "Verifichiamo il tuo profilo …", checkSub: (n) => ["Un attimo: stiamo verificando ", n, "."],
  st: ["Ricerca su Google Maps", "Confronto del profilo", "Verifica della rimozione"],
  altNotMineSub: "Cerca di nuovo con un altro nome", altNotFound: "Profilo non trovato?",
  altNotFoundA: "Inserisci i link alle recensioni", altNotFoundB: "Inserisci un link di Google Maps",
  svcH: "Cosa possiamo fare per te?", svcSub: "Scegli il servizio giusto. Paghi solo dopo una rimozione riuscita.",
  svcOk: "Il tuo profilo può essere eliminato",
  svc1: ["Eliminare il profilo", "Il profilo scompare per sempre, e con lui tutte le recensioni.", ["Tutte le recensioni via", "Di solito in 24 h"]],
  svc2: ["Eliminare il profilo + nuovo inizio", "Eliminiamo il vecchio profilo e ne creiamo uno nuovo, con 0 recensioni.", ["Nuovo profilo verificato", "Un nuovo inizio pulito"]],
  reviewsNA: "Non rimuoviamo singole recensioni per profili in Germania e Austria. È possibile eliminare l'intero profilo.",
  naH: (c) => "Non rimuoviamo singole recensioni in {c}".replace("{c}", c), naSub: (c) => "Il tuo profilo si trova in {c}. Per la situazione legale non possiamo rimuovere singole recensioni Google: è riservato agli avvocati. Per il tuo profilo c'è questa possibilità:".replace("{c}", c), naOpts: "Opzioni disponibili per il tuo profilo", naWrong: "Profilo sbagliato? Cerca di nuovo", naLegal: "Informazione generale, non consulenza legale.",
  change: "Modifica", riskT: "Nessun successo, nessun costo.", riskD: "Paghi solo quando il profilo è stato davvero eliminato.",
  ldSub: (n) => ["Stiamo caricando tutte le recensioni di ", n, " da Google Maps."], ldFound: "recensioni trovate",
  nRev: (n) => (n === 1 ? "1 recensione" : n + " recensioni"), selAll: "Seleziona tutte", selNone: "Annulla selezione",
  noText: "Recensione senza testo",
  tag: { std: "ca. 90 %", legal: "oltre il 90 %", sw: "Verifica preliminare" },
  cat: { std: "Fino a 4 settimane", legal: "Oltre 4 settimane", nt: "Senza testo", sw: "Software speciale" },
  selN: (n) => (!n ? "Nessuna recensione selezionata" : n === 1 ? "1 recensione selezionata" : n + " recensioni selezionate"),
  selShort: (n) => (n ? n + " selezionate" : "Nessuna"), pickOne: "Seleziona almeno una recensione.",
  nudge: (k, p) => (k === 1 ? "Ancora 1 recensione" : "Ancora " + k + " recensioni") + " per −" + p + " %",
  toCo: "Vai alla cassa", payAfter: "Pagamento solo dopo una rimozione riuscita", subtotal: "Subtotale",
  sheet: {
    t1: ["Fino a 4 settimane", "Segnalazione diretta a Google", "ca. 90 % di successo"],
    t2: ["Oltre 4 settimane", "Prima una segnalazione legale a Google", "oltre il 90 % di successo"],
    t3: ["Senza testo o dagli USA", "Possibile solo con software speciale. Verifichiamo prima se funziona."],
    per: "per recensione", from: (n) => "da " + n, riskR: " Paghi solo quando la recensione è stata rimossa.",
  },
  protH: "Protezione da una nuova pubblicazione",
  protSub: "I profili eliminati possono ricomparire. Con la protezione li rimuoviamo di nuovo, gratis.",
  protD: { monthly: "Nuova rimozione gratuita ogni volta che serve.", monitor: "Controlliamo ogni giorno e rimuoviamo automaticamente, senza che tu faccia nulla.", lifetime: "Paghi una volta, protetto per sempre, monitoraggio incluso." },
  protNone: "Senza protezione", protNoneD: "Si può aggiungere anche più tardi.", perMonth: " / mese", cancel: "Disdici ogni mese", once: "una tantum",
  warnB: "Senza protezione non rimuoviamo gratis un profilo ricomparso.", warnR: " Il rischio di una nuova pubblicazione resta a tuo carico.",
  exT: "Come può tornare il tuo profilo", exN: ["Terzi, spesso concorrenti, lo registrano di nuovo", "Google riprende dati dai siti web", "Il profilo è di nuovo su Google Maps"],
  yourSel: "La tua scelta", fromDel: "dalla rimozione", today: "Da pagare oggi", billNote: "Addebito solo dopo una rimozione riuscita.", todayShort: (v) => "Oggi " + v,
  coSub: "Solo l'essenziale. Paghi solo dopo una rimozione riuscita.",
  f: { name: "Il tuo nome", email: "E-mail", phone: "Telefono", optional: "facoltativo", company: "Attività" },
  order: "Ordine con obbligo di pagamento", nothingToday: "Oggi non viene addebitato nulla",
  payOnSuccess: "Pagamento dopo il successo", total: "Totale in caso di successo", how: "Come funziona la fatturazione?",
  howA: [["Verifichiamo e partiamo.", " Appena nella dashboard è salvato un metodo di pagamento, iniziamo."], ["Paghi per rimozione.", " Se viene rimossa solo una recensione su due, paghi solo quella."], ["Nessun successo, nessun costo.", " Se non funziona, non paghi nulla."]],
  howB: [["Partiamo subito.", " Ricevi tutti i passi successivi via e-mail."], ["Fatturazione dopo la rimozione.", " Solo quando il profilo è sparito ricevi link di pagamento e fattura; la protezione parte da quel momento."], ["Nessun successo, nessun costo.", " Se non funziona, non paghi nulla."]],
  lineSub: { std: "Segnalazione diretta a Google", legal: "Segnalazione legale a Google", nt: "Software speciale · verifica preliminare" },
  delN: (n) => (n === 1 ? "Rimuovere 1 recensione" : "Rimuovere " + n + " recensioni"),
  expressSub: "Gestione in ~6 h",
  verified: "Recensione verificata", tpFoot: (r, n) => [r, " su " + n + " recensioni Trustpilot"],
  thanksH: "Grazie mille.", thanksSub: "Abbiamo ricevuto il tuo ordine. La conferma arriva via e-mail: ti contattiamo entro 24 ore.", newOrder: "Nuovo ordine",
  sending: "Invio dell'ordine …",
};

const nl = {
  ...en,
  sub0: "Kies de gewenste dienst.", badgeTop: "Meest gekozen",
  tiles: {
    delete: ["Google-bedrijfsprofiel verwijderen", "Het profiel wordt definitief verwijderd, samen met alle reviews."],
    reviews: ["Losse reviews verwijderen", "Geselecteerde reviews worden verwijderd, het profiel blijft bestaan."],
    press: ["Negatieve pers of zoekresultaten", "Een artikel of Google-resultaat dat moet verdwijnen."],
    unsure: ["Niet zeker?", "Twee korte vragen, dan sturen we u de juiste kant op."],
  },
  labelsA: ["Bedrijf", "Profiel zoeken", "Bevestigen", "Dienst", "Reviews", "Afrekenen", "Klaar"],
  labelsB: ["Bedrijf", "Profiel zoeken", "Bevestigen", "Dienst", "Bescherming", "Afrekenen", "Klaar"],
  stepOf: (n, t) => ["Stap " + n, " van " + t],
  eta2: "ca. 2 min", eta1: "ca. 1 min", almost: "Bijna klaar", doneLbl: "Klaar",
  expert: "Praat met een Google-expert", online: "Nu bereikbaar",
  sub1: "We zoeken uw Google-bedrijfsprofiel.", find: "Profiel vinden",
  searchH: "We zoeken uw profiel …", searchSub: (n) => ["Een moment – we doorzoeken Google Maps naar ", n, "."],
  checkH: "We controleren uw profiel …", checkSub: (n) => ["Een moment – we controleren ", n, "."],
  st: ["Google Maps doorzoeken", "Profiel vergelijken", "Verwijderbaarheid controleren"],
  altNotMineSub: "Opnieuw zoeken met een andere naam", altNotFound: "Profiel niet gevonden?",
  altNotFoundA: "Links naar de reviews invoeren", altNotFoundB: "Google Maps-link invoeren",
  svcH: "Wat kunnen we voor u doen?", svcSub: "Kies de passende dienst. U betaalt pas na een geslaagde verwijdering.",
  svcOk: "Uw profiel kan worden verwijderd",
  svc1: ["Profiel verwijderen", "Het profiel verdwijnt definitief – en daarmee alle reviews.", ["Alle reviews weg", "Meestal binnen 24 u"]],
  svc2: ["Profiel verwijderen + herstart", "We verwijderen het oude profiel en zetten een nieuw op – met 0 reviews.", ["Nieuw, geverifieerd profiel", "Een schone herstart"]],
  reviewsNA: "Losse reviews verwijderen we niet voor profielen in Duitsland en Oostenrijk. Het hele profiel verwijderen kan wel.",
  naH: (c) => "Losse reviews verwijderen kan niet in {c}".replace("{c}", c), naSub: (c) => "Uw profiel staat in {c}. Door de juridische situatie daar mogen wij geen losse Google-reviews verwijderen; dat is voorbehouden aan advocaten. Dit kunnen we wel voor uw profiel doen:".replace("{c}", c), naOpts: "Beschikbare opties voor uw profiel", naWrong: "Verkeerd profiel? Opnieuw zoeken", naLegal: "Algemene informatie, geen juridisch advies.",
  change: "Wijzigen", riskT: "Geen succes, geen kosten.", riskD: "U betaalt pas als het profiel echt verwijderd is.",
  ldSub: (n) => ["We halen alle reviews van ", n, " op uit Google Maps."], ldFound: "reviews gevonden",
  nRev: (n) => (n === 1 ? "1 review" : n + " reviews"), selAll: "Alles selecteren", selNone: "Selectie wissen",
  noText: "Review zonder tekst",
  tag: { std: "ca. 90%", legal: "meer dan 90%", sw: "Voorafcontrole" },
  cat: { std: "Tot 4 weken", legal: "Ouder dan 4 weken", nt: "Zonder tekst", sw: "Speciale software" },
  selN: (n) => (!n ? "Geen review geselecteerd" : n === 1 ? "1 review geselecteerd" : n + " reviews geselecteerd"),
  selShort: (n) => (n ? n + " geselecteerd" : "Geen geselecteerd"), pickOne: "Selecteer minstens één review.",
  nudge: (k, p) => (k === 1 ? "Nog 1 review" : "Nog " + k + " reviews") + " tot −" + p + "%",
  toCo: "Verder naar afrekenen", payAfter: "Betaling pas na geslaagde verwijdering", subtotal: "Subtotaal",
  sheet: {
    t1: ["Tot 4 weken oud", "Directe melding bij Google", "ca. 90% slagingskans"],
    t2: ["Ouder dan 4 weken", "Eerst een juridische melding bij Google", "meer dan 90% slagingskans"],
    t3: ["Zonder tekst of uit de VS", "Alleen mogelijk met speciale software. We controleren vooraf of het lukt."],
    per: "per review", from: (n) => "vanaf " + n, riskR: " U betaalt pas als de review verwijderd is.",
  },
  protH: "Bescherming tegen herpublicatie",
  protSub: "Verwijderde profielen kunnen terugkomen. Met bescherming verwijderen we ze opnieuw – gratis.",
  protD: { monthly: "Gratis opnieuw verwijderen wanneer u het nodig heeft.", monitor: "We controleren dagelijks en verwijderen automatisch – zonder dat u iets hoeft te doen.", lifetime: "Eenmalig betalen, voor altijd beschermd – inclusief monitoring." },
  protNone: "Zonder bescherming", protNoneD: "Kan later nog worden toegevoegd.", perMonth: " / maand", cancel: "Maandelijks opzegbaar", once: "eenmalig",
  warnB: "Zonder bescherming verwijderen we een teruggekeerd profiel niet gratis.", warnR: " Het risico van herpublicatie ligt dan bij uzelf.",
  exT: "Zo kan uw profiel terugkomen", exN: ["Derden – vaak concurrenten – melden het opnieuw aan", "Google neemt gegevens van websites over", "Het profiel staat weer op Google Maps"],
  yourSel: "Uw keuze", fromDel: "vanaf verwijdering", today: "Vandaag te betalen", billNote: "Pas gefactureerd na een geslaagde verwijdering.", todayShort: (v) => "Vandaag " + v,
  coSub: "Alleen het nodige. U betaalt pas na een geslaagde verwijdering.",
  f: { name: "Uw naam", email: "E-mail", phone: "Telefoon", optional: "optioneel", company: "Bedrijf" },
  order: "Bestellen met betalingsverplichting", nothingToday: "Vandaag wordt er niets afgeschreven",
  payOnSuccess: "Betaling na succes", total: "Totaal bij succes", how: "Hoe wordt er afgerekend?",
  howA: [["We controleren en starten.", " Zodra er in uw dashboard een betaalmethode staat, gaan we aan de slag."], ["U betaalt per verwijdering.", " Wordt maar één van twee reviews verwijderd, dan betaalt u alleen die."], ["Geen succes, geen kosten.", " Lukt het niet, dan betaalt u niets."]],
  howB: [["We starten meteen.", " Alle volgende stappen ontvangt u per e-mail."], ["Afrekening na verwijdering.", " Pas als het profiel weg is, ontvangt u betaallink en factuur – een bescherming start vanaf dan."], ["Geen succes, geen kosten.", " Lukt het niet, dan betaalt u niets."]],
  lineSub: { std: "Directe melding bij Google", legal: "Juridische melding bij Google", nt: "Speciale software · voorafcontrole" },
  delN: (n) => (n === 1 ? "1 review verwijderen" : n + " reviews verwijderen"),
  expressSub: "Afhandeling in ~6 u",
  verified: "Geverifieerde review", tpFoot: (r, n) => [r, " uit " + n + " reviews op Trustpilot"],
  thanksH: "Hartelijk dank.", thanksSub: "Uw bestelling is ontvangen. De bevestiging komt per e-mail – we nemen binnen 24 uur contact op.", newOrder: "Nieuwe bestelling",
  sending: "Bestelling wordt verzonden …",
};

const pt = {
  ...en,
  sub0: "Escolha o serviço pretendido.", badgeTop: "O mais escolhido",
  tiles: {
    delete: ["Excluir perfil de empresa no Google", "O perfil é removido definitivamente, com todas as avaliações."],
    reviews: ["Excluir avaliações individuais", "As avaliações selecionadas são removidas, o perfil mantém-se."],
    press: ["Imprensa negativa ou resultados de pesquisa", "Um artigo ou resultado do Google que deve desaparecer."],
    unsure: ["Não tem a certeza?", "Duas perguntas rápidas e indicamos-lhe o caminho."],
  },
  labelsA: ["Empresa", "Pesquisa", "Confirmar", "Serviço", "Avaliações", "Pagamento", "Concluído"],
  labelsB: ["Empresa", "Pesquisa", "Confirmar", "Serviço", "Proteção", "Pagamento", "Concluído"],
  stepOf: (n, t) => ["Passo " + n, " de " + t],
  eta2: "aprox. 2 min", eta1: "aprox. 1 min", almost: "Quase concluído", doneLbl: "Concluído",
  expert: "Falar com um especialista Google", online: "Disponível agora",
  sub1: "Procuramos o seu perfil de empresa no Google.", find: "Encontrar perfil",
  searchH: "A procurar o seu perfil …", searchSub: (n) => ["Um momento – estamos a procurar ", n, " no Google Maps."],
  checkH: "A verificar o seu perfil …", checkSub: (n) => ["Um momento – estamos a verificar ", n, "."],
  st: ["A pesquisar no Google Maps", "A comparar o perfil", "A verificar a remoção"],
  altNotMineSub: "Pesquisar de novo com outro nome", altNotFound: "Perfil não encontrado?",
  altNotFoundA: "Introduzir links das avaliações", altNotFoundB: "Introduzir um link do Google Maps",
  svcH: "O que podemos fazer por si?", svcSub: "Escolha o serviço adequado. Só paga após uma remoção bem-sucedida.",
  svcOk: "O seu perfil pode ser removido",
  svc1: ["Excluir perfil", "O perfil desaparece de vez – e com ele todas as avaliações.", ["Todas as avaliações fora", "Normalmente em 24 h"]],
  svc2: ["Excluir perfil + recomeço", "Removemos o perfil antigo e criamos um novo – com 0 avaliações.", ["Perfil novo e verificado", "Um recomeço limpo"]],
  reviewsNA: "Não removemos avaliações individuais de perfis na Alemanha e na Áustria. É possível remover o perfil completo.",
  naH: (c) => "Não removemos avaliações individuais na {c}".replace("{c}", c), naSub: (c) => "O seu perfil está na {c}. Devido à situação legal, não podemos remover avaliações individuais do Google; isso está reservado a advogados. Para o seu perfil existe esta opção:".replace("{c}", c), naOpts: "Opções disponíveis para o seu perfil", naWrong: "Perfil errado? Pesquisar de novo", naLegal: "Informação geral, não é aconselhamento jurídico.",
  change: "Alterar", riskT: "Sem sucesso, sem custos.", riskD: "Só paga quando o perfil tiver sido realmente removido.",
  ldSub: (n) => ["Estamos a carregar todas as avaliações de ", n, " do Google Maps."], ldFound: "avaliações encontradas",
  nRev: (n) => (n === 1 ? "1 avaliação" : n + " avaliações"), selAll: "Selecionar todas", selNone: "Limpar seleção",
  noText: "Avaliação sem texto",
  tag: { std: "aprox. 90 %", legal: "mais de 90 %", sw: "Verificação prévia" },
  cat: { std: "Até 4 semanas", legal: "Mais de 4 semanas", nt: "Sem texto", sw: "Software especial" },
  selN: (n) => (!n ? "Nenhuma avaliação selecionada" : n === 1 ? "1 avaliação selecionada" : n + " avaliações selecionadas"),
  selShort: (n) => (n ? n + " selecionadas" : "Nenhuma"), pickOne: "Selecione pelo menos uma avaliação.",
  nudge: (k, p) => (k === 1 ? "Mais 1 avaliação" : "Mais " + k + " avaliações") + " para −" + p + " %",
  toCo: "Continuar para o pagamento", payAfter: "Pagamento só após remoção bem-sucedida", subtotal: "Subtotal",
  sheet: {
    t1: ["Até 4 semanas", "Denúncia direta ao Google", "aprox. 90 % de sucesso"],
    t2: ["Mais de 4 semanas", "Primeiro um aviso legal ao Google", "mais de 90 % de sucesso"],
    t3: ["Sem texto ou dos EUA", "Só possível com software especial. Verificamos antes se resulta."],
    per: "por avaliação", from: (n) => "a partir de " + n, riskR: " Só paga quando a avaliação tiver sido removida.",
  },
  protH: "Proteção contra nova publicação",
  protSub: "Perfis removidos podem reaparecer. Com proteção, removemo-los de novo – gratuitamente.",
  protD: { monthly: "Nova remoção gratuita sempre que precisar.", monitor: "Verificamos diariamente e removemos automaticamente – sem nada a fazer.", lifetime: "Paga uma vez, protegido para sempre – monitorização incluída." },
  protNone: "Sem proteção", protNoneD: "Pode ser adicionada mais tarde.", perMonth: " / mês", cancel: "Cancelável mensalmente", once: "pagamento único",
  warnB: "Sem proteção, não removemos gratuitamente um perfil que reapareça.", warnR: " O risco de uma nova publicação fica então do seu lado.",
  exT: "Como o seu perfil pode voltar", exN: ["Terceiros – muitas vezes concorrentes – registam-no de novo", "O Google recolhe dados de websites", "O perfil volta a estar no Google Maps"],
  yourSel: "A sua seleção", fromDel: "a partir da remoção", today: "A pagar hoje", billNote: "Faturado só após uma remoção bem-sucedida.", todayShort: (v) => "Hoje " + v,
  coSub: "Só o essencial. Paga apenas após uma remoção bem-sucedida.",
  f: { name: "O seu nome", email: "E-mail", phone: "Telefone", optional: "opcional", company: "Empresa" },
  order: "Encomenda com obrigação de pagamento", nothingToday: "Hoje não é cobrado nada",
  payOnSuccess: "Pagamento após sucesso", total: "Total em caso de sucesso", how: "Como funciona a faturação?",
  howA: [["Verificamos e começamos.", " Assim que houver um método de pagamento no seu painel, começamos."], ["Paga por remoção.", " Se só uma de duas avaliações for removida, paga só essa."], ["Sem sucesso, sem custos.", " Se não resultar, não paga nada."]],
  howB: [["Começamos de imediato.", " Recebe todos os próximos passos por e-mail."], ["Faturação após a remoção.", " Só quando o perfil desaparecer recebe o link de pagamento e a fatura – a proteção começa a partir daí."], ["Sem sucesso, sem custos.", " Se não resultar, não paga nada."]],
  lineSub: { std: "Denúncia direta ao Google", legal: "Aviso legal ao Google", nt: "Software especial · verificação prévia" },
  delN: (n) => (n === 1 ? "Remover 1 avaliação" : "Remover " + n + " avaliações"),
  expressSub: "Tratamento em ~6 h",
  verified: "Avaliação verificada", tpFoot: (r, n) => [r, " de " + n + " avaliações no Trustpilot"],
  thanksH: "Muito obrigado.", thanksSub: "Recebemos a sua encomenda. A confirmação chega por e-mail – entramos em contacto em 24 horas.", newOrder: "Nova encomenda",
  sending: "A enviar a encomenda …",
};

const ja = {
  ...en,
  sub0: "ご希望のサービスを選択してください。", badgeTop: "いちばん人気",
  tiles: {
    delete: ["Googleビジネスプロフィールを削除", "プロフィールをすべての口コミとともに完全に削除します。"],
    reviews: ["個別の口コミを削除", "選んだ口コミだけを削除し、プロフィールは残ります。"],
    press: ["ネガティブな記事・検索結果", "消したい記事やGoogleの検索結果。"],
    unsure: ["よくわからない場合", "2つの簡単な質問で最適な窓口をご案内します。"],
  },
  labelsA: ["会社名", "検索", "確認", "サービス", "口コミ", "お支払い", "完了"],
  labelsB: ["会社名", "検索", "確認", "サービス", "保護", "お支払い", "完了"],
  stepOf: (n, t) => ["ステップ " + n, " / " + t],
  eta2: "約2分", eta1: "約1分", almost: "あと少し", doneLbl: "完了",
  expert: "Googleの専門家に相談", online: "ただいま対応可能",
  sub1: "Googleビジネスプロフィールを検索します。", find: "プロフィールを探す",
  searchH: "プロフィールを検索中 …", searchSub: (n) => ["少々お待ちください。Googleマップで「", n, "」を検索しています。"],
  checkH: "プロフィールを確認中 …", checkSub: (n) => ["少々お待ちください。「", n, "」を確認しています。"],
  st: ["Googleマップを検索", "プロフィールを照合", "削除可否を確認"],
  altNotMineSub: "別の名前で再検索", altNotFound: "プロフィールが見つかりませんか？",
  altNotFoundA: "口コミのリンクを入力", altNotFoundB: "Googleマップのリンクを入力",
  svcH: "ご希望の内容をお選びください", svcSub: "最適なサービスを選んでください。お支払いは削除成功後のみです。",
  svcOk: "このプロフィールは削除できます",
  svc1: ["プロフィールを削除", "プロフィールが完全に消え、すべての口コミも一緒に消えます。", ["口コミはすべて削除", "通常24時間以内"]],
  svc2: ["プロフィール削除＋再スタート", "古いプロフィールを削除し、口コミ0件の新しいプロフィールを作成します。", ["認証済みの新しいプロフィール", "まっさらな再スタート"]],
  reviewsNA: "ドイツとオーストリアのプロフィールについては、個別の口コミ削除は行っていません。プロフィール全体の削除は可能です。",
  naH: (c) => "{c}では個別の口コミ削除はできません".replace("{c}", c), naSub: (c) => "このプロフィールは{c}にあります。現地の法律上、個別のGoogle口コミの削除は弁護士にのみ認められているため、当社では対応できません。代わりに次の対応が可能です：".replace("{c}", c), naOpts: "このプロフィールで選べるサービス", naWrong: "プロフィールが違いますか？再検索", naLegal: "一般的な情報であり、法的助言ではありません。",
  change: "変更", riskT: "成功しなければ費用ゼロ。", riskD: "プロフィールが実際に削除されてからのお支払いです。",
  ldSub: (n) => ["Googleマップから「", n, "」の口コミを読み込んでいます。"], ldFound: "件の口コミ",
  nRev: (n) => n + "件の口コミ", selAll: "すべて選択", selNone: "選択を解除",
  noText: "本文のない口コミ",
  tag: { std: "約90%", legal: "90%以上", sw: "事前確認" },
  cat: { std: "4週間以内", legal: "4週間より前", nt: "本文なし", sw: "専用ソフトウェア" },
  selN: (n) => (!n ? "口コミが選択されていません" : n + "件を選択中"),
  selShort: (n) => (n ? n + "件選択" : "未選択"), pickOne: "口コミを1件以上選んでください。",
  nudge: (k, p) => "あと" + k + "件で−" + p + "%",
  toCo: "お支払いへ進む", payAfter: "お支払いは削除成功後のみ", subtotal: "小計",
  sheet: {
    t1: ["投稿から4週間以内", "Googleへ直接報告", "成功率 約90%"],
    t2: ["4週間より前", "まずGoogleへ法的通知", "成功率 90%以上"],
    t3: ["本文なし・米国の口コミ", "専用ソフトウェアでのみ対応可能。事前に可否を確認します。"],
    per: "1件あたり", from: (n) => n + "件〜", riskR: " 口コミが削除されてからのお支払いです。",
  },
  protH: "再掲載からの保護",
  protSub: "削除したプロフィールが再び表示されることがあります。保護があれば、無料で再削除します。",
  protD: { monthly: "必要なときはいつでも無料で再削除。", monitor: "毎日チェックし、自動で削除します。お手間はかかりません。", lifetime: "一度のお支払いで永久保護。モニタリング込み。" },
  protNone: "保護なし", protNoneD: "あとから追加することもできます。", perMonth: " / 月", cancel: "毎月解約可能", once: "一括",
  warnB: "保護がない場合、再表示されたプロフィールは無料では削除しません。", warnR: " 再掲載のリスクはお客様のご負担となります。",
  exT: "プロフィールが戻ってくる仕組み", exN: ["第三者（多くは競合）が再登録する", "Googleがウェブサイトから情報を取り込む", "プロフィールがGoogleマップに再表示"],
  yourSel: "ご選択内容", fromDel: "削除後から", today: "本日のお支払い", billNote: "請求は削除成功後のみです。", todayShort: (v) => "本日 " + v,
  coSub: "入力は最小限。お支払いは削除成功後のみです。",
  f: { name: "お名前", email: "メールアドレス", phone: "電話番号", optional: "任意", company: "会社名" },
  order: "支払義務のある注文を確定する", nothingToday: "本日の請求はありません",
  payOnSuccess: "成功後にお支払い", total: "成功時の合計", how: "請求の流れ",
  howA: [["確認して開始します。", " ダッシュボードにお支払い方法が登録され次第、作業を始めます。"], ["削除1件ごとのお支払い。", " 2件のうち1件だけ削除された場合、その1件分のみお支払いいただきます。"], ["成功しなければ費用ゼロ。", " うまくいかなければ一切かかりません。"]],
  howB: [["すぐに開始します。", " 次のステップはすべてメールでお知らせします。"], ["削除後に請求。", " プロフィールが削除されてから支払いリンクと請求書をお送りします。保護はそこから開始します。"], ["成功しなければ費用ゼロ。", " うまくいかなければ一切かかりません。"]],
  lineSub: { std: "Googleへ直接報告", legal: "Googleへ法的通知", nt: "専用ソフトウェア・事前確認" },
  delN: (n) => n + "件の口コミを削除",
  expressSub: "約6時間で対応",
  verified: "認証済みレビュー", tpFoot: (r, n) => [r, "（Trustpilotの" + n + "件のレビュー）"],
  thanksH: "ありがとうございます。", thanksSub: "ご注文を受け付けました。確認メールをお送りします。24時間以内にご連絡いたします。", newOrder: "新しいご注文",
  sending: "ご注文を送信中 …",
};

const sv = {
  ...en,
  sub0: "Välj den tjänst du behöver.", badgeTop: "Mest vald",
  tiles: {
    delete: ["Ta bort Google-företagsprofil", "Profilen tas bort permanent, tillsammans med alla omdömen."],
    reviews: ["Ta bort enskilda omdömen", "Valda omdömen tas bort, profilen finns kvar."],
    press: ["Negativ press eller sökresultat", "En artikel eller ett Google-resultat som ska försvinna."],
    unsure: ["Osäker?", "Två snabba frågor, sedan visar vi vägen."],
  },
  labelsA: ["Företag", "Profilsökning", "Bekräfta", "Tjänst", "Omdömen", "Kassa", "Klart"],
  labelsB: ["Företag", "Profilsökning", "Bekräfta", "Tjänst", "Skydd", "Kassa", "Klart"],
  stepOf: (n, t) => ["Steg " + n, " av " + t],
  eta2: "ca 2 min", eta1: "ca 1 min", almost: "Nästan klart", doneLbl: "Klart",
  expert: "Prata med en Google-expert", online: "Tillgänglig nu",
  sub1: "Vi söker efter din Google-företagsprofil.", find: "Hitta profil",
  searchH: "Vi söker efter din profil …", searchSub: (n) => ["Ett ögonblick – vi söker efter ", n, " på Google Maps."],
  checkH: "Vi kontrollerar din profil …", checkSub: (n) => ["Ett ögonblick – vi kontrollerar ", n, "."],
  st: ["Söker på Google Maps", "Matchar profilen", "Kontrollerar borttagning"],
  altNotMineSub: "Sök igen med ett annat namn", altNotFound: "Hittar du inte profilen?",
  altNotFoundA: "Ange länkar till omdömena", altNotFoundB: "Ange en Google Maps-länk",
  svcH: "Vad kan vi göra för dig?", svcSub: "Välj rätt tjänst. Du betalar först efter lyckad borttagning.",
  svcOk: "Din profil kan tas bort",
  svc1: ["Ta bort profil", "Profilen försvinner för gott – och alla omdömen med den.", ["Alla omdömen borta", "Oftast inom 24 h"]],
  svc2: ["Ta bort profil + nystart", "Vi tar bort den gamla profilen och skapar en ny – med 0 omdömen.", ["Ny, verifierad profil", "En ren nystart"]],
  reviewsNA: "Vi tar inte bort enskilda omdömen för profiler i Tyskland och Österrike. Hela profilen kan tas bort.",
  naH: (c) => "Vi tar inte bort enskilda omdömen i {c}".replace("{c}", c), naSub: (c) => "Din profil finns i {c}. På grund av den rättsliga situationen där får vi inte ta bort enskilda Google-omdömen; det är förbehållet advokater. Det här kan vi göra för din profil i stället:".replace("{c}", c), naOpts: "Tillgängliga alternativ för din profil", naWrong: "Fel profil? Sök igen", naLegal: "Allmän information, inte juridisk rådgivning.",
  change: "Ändra", riskT: "Ingen framgång, ingen kostnad.", riskD: "Du betalar först när profilen faktiskt har tagits bort.",
  ldSub: (n) => ["Vi hämtar alla omdömen för ", n, " från Google Maps."], ldFound: "omdömen hittade",
  nRev: (n) => (n === 1 ? "1 omdöme" : n + " omdömen"), selAll: "Välj alla", selNone: "Avmarkera alla",
  noText: "Omdöme utan text",
  tag: { std: "ca 90 %", legal: "över 90 %", sw: "Förhandskontroll" },
  cat: { std: "Upp till 4 veckor", legal: "Äldre än 4 veckor", nt: "Utan text", sw: "Specialprogram" },
  selN: (n) => (!n ? "Inget omdöme valt" : n === 1 ? "1 omdöme valt" : n + " omdömen valda"),
  selShort: (n) => (n ? n + " valda" : "Inga valda"), pickOne: "Välj minst ett omdöme.",
  nudge: (k, p) => (k === 1 ? "1 omdöme till" : k + " omdömen till") + " för −" + p + " %",
  toCo: "Vidare till kassan", payAfter: "Betalning först efter lyckad borttagning", subtotal: "Delsumma",
  sheet: {
    t1: ["Upp till 4 veckor", "Direkt anmälan till Google", "ca 90 % chans att lyckas"],
    t2: ["Äldre än 4 veckor", "Först ett juridiskt meddelande till Google", "över 90 % chans att lyckas"],
    t3: ["Utan text eller från USA", "Bara möjligt med specialprogram. Vi kontrollerar först om det går."],
    per: "per omdöme", from: (n) => "från " + n, riskR: " Du betalar först när omdömet har tagits bort.",
  },
  protH: "Skydd mot ny publicering",
  protSub: "Borttagna profiler kan dyka upp igen. Med skydd tar vi bort dem igen – kostnadsfritt.",
  protD: { monthly: "Gratis ny borttagning när du behöver det.", monitor: "Vi kontrollerar dagligen och tar bort automatiskt – utan att du gör något.", lifetime: "Betala en gång, skyddad för alltid – övervakning ingår." },
  protNone: "Utan skydd", protNoneD: "Kan läggas till senare.", perMonth: " / månad", cancel: "Sägs upp månadsvis", once: "engångs",
  warnB: "Utan skydd tar vi inte bort en återkommen profil gratis.", warnR: " Risken för ny publicering bär du då själv.",
  exT: "Så kan din profil komma tillbaka", exN: ["Tredje part – ofta konkurrenter – registrerar den igen", "Google hämtar data från webbplatser", "Profilen är tillbaka på Google Maps"],
  yourSel: "Ditt val", fromDel: "från borttagning", today: "Att betala idag", billNote: "Debiteras först efter lyckad borttagning.", todayShort: (v) => "Idag " + v,
  coSub: "Bara det nödvändigaste. Du betalar först efter lyckad borttagning.",
  f: { name: "Ditt namn", email: "E-post", phone: "Telefon", optional: "valfritt", company: "Företag" },
  order: "Beställ med betalningsskyldighet", nothingToday: "Inget dras idag",
  payOnSuccess: "Betalning efter framgång", total: "Totalt vid framgång", how: "Hur går faktureringen till?",
  howA: [["Vi kontrollerar och startar.", " Så snart en betalningsmetod finns i din översikt sätter vi igång."], ["Du betalar per borttagning.", " Tas bara ett av två omdömen bort betalar du bara för det."], ["Ingen framgång, ingen kostnad.", " Lyckas det inte betalar du ingenting."]],
  howB: [["Vi startar direkt.", " Alla nästa steg får du via e-post."], ["Fakturering efter borttagning.", " Först när profilen är borta får du betallänk och faktura – ett skydd startar från då."], ["Ingen framgång, ingen kostnad.", " Lyckas det inte betalar du ingenting."]],
  lineSub: { std: "Direkt anmälan till Google", legal: "Juridiskt meddelande till Google", nt: "Specialprogram · förhandskontroll" },
  delN: (n) => (n === 1 ? "Ta bort 1 omdöme" : "Ta bort " + n + " omdömen"),
  expressSub: "Hanteras på ~6 h",
  verified: "Verifierat omdöme", tpFoot: (r, n) => [r, " av " + n + " omdömen på Trustpilot"],
  thanksH: "Tack så mycket.", thanksSub: "Din beställning har tagits emot. Bekräftelsen kommer via e-post – vi hör av oss inom 24 timmar.", newOrder: "Ny beställning",
  sending: "Beställningen skickas …",
};

const da = {
  ...en,
  sub0: "Vælg den ydelse, du har brug for.", badgeTop: "Mest valgt",
  tiles: {
    delete: ["Slet Google-virksomhedsprofil", "Profilen fjernes permanent, sammen med alle anmeldelser."],
    reviews: ["Slet enkelte anmeldelser", "Valgte anmeldelser fjernes, profilen bliver."],
    press: ["Negativ presse eller søgeresultater", "En artikel eller et Google-resultat, der skal forsvinde."],
    unsure: ["Usikker?", "To hurtige spørgsmål, så viser vi vej."],
  },
  labelsA: ["Virksomhed", "Profilsøgning", "Bekræft", "Ydelse", "Anmeldelser", "Kasse", "Færdig"],
  labelsB: ["Virksomhed", "Profilsøgning", "Bekræft", "Ydelse", "Beskyttelse", "Kasse", "Færdig"],
  stepOf: (n, t) => ["Trin " + n, " af " + t],
  eta2: "ca. 2 min.", eta1: "ca. 1 min.", almost: "Næsten færdig", doneLbl: "Færdig",
  expert: "Tal med en Google-ekspert", online: "Tilgængelig nu",
  sub1: "Vi søger efter din Google-virksomhedsprofil.", find: "Find profil",
  searchH: "Vi søger efter din profil …", searchSub: (n) => ["Et øjeblik – vi søger efter ", n, " på Google Maps."],
  checkH: "Vi tjekker din profil …", checkSub: (n) => ["Et øjeblik – vi tjekker ", n, "."],
  st: ["Søger på Google Maps", "Matcher profilen", "Tjekker om den kan slettes"],
  altNotMineSub: "Søg igen med et andet navn", altNotFound: "Kan du ikke finde profilen?",
  altNotFoundA: "Indtast links til anmeldelserne", altNotFoundB: "Indtast et Google Maps-link",
  svcH: "Hvad kan vi gøre for dig?", svcSub: "Vælg den rette ydelse. Du betaler først efter en vellykket sletning.",
  svcOk: "Din profil kan slettes",
  svc1: ["Slet profil", "Profilen forsvinder for altid – og alle anmeldelser med den.", ["Alle anmeldelser væk", "Typisk inden for 24 timer"]],
  svc2: ["Slet profil + ny start", "Vi sletter den gamle profil og opretter en ny – med 0 anmeldelser.", ["Ny, verificeret profil", "En ren ny start"]],
  reviewsNA: "Vi sletter ikke enkelte anmeldelser for profiler i Tyskland og Østrig. Hele profilen kan slettes.",
  naH: (c) => "Vi sletter ikke enkelte anmeldelser i {c}".replace("{c}", c), naSub: (c) => "Din profil ligger i {c}. På grund af den juridiske situation dér må vi ikke fjerne enkelte Google-anmeldelser; det er forbeholdt advokater. Dette kan vi gøre for din profil i stedet:".replace("{c}", c), naOpts: "Mulige ydelser for din profil", naWrong: "Forkert profil? Søg igen", naLegal: "Generel information, ikke juridisk rådgivning.",
  change: "Ændr", riskT: "Ingen succes, ingen betaling.", riskD: "Du betaler først, når profilen faktisk er slettet.",
  ldSub: (n) => ["Vi henter alle anmeldelser af ", n, " fra Google Maps."], ldFound: "anmeldelser fundet",
  nRev: (n) => (n === 1 ? "1 anmeldelse" : n + " anmeldelser"), selAll: "Vælg alle", selNone: "Fravælg alle",
  noText: "Anmeldelse uden tekst",
  tag: { std: "ca. 90 %", legal: "over 90 %", sw: "Forhåndstjek" },
  cat: { std: "Op til 4 uger", legal: "Ældre end 4 uger", nt: "Uden tekst", sw: "Specialsoftware" },
  selN: (n) => (!n ? "Ingen anmeldelse valgt" : n === 1 ? "1 anmeldelse valgt" : n + " anmeldelser valgt"),
  selShort: (n) => (n ? n + " valgt" : "Ingen valgt"), pickOne: "Vælg mindst én anmeldelse.",
  nudge: (k, p) => (k === 1 ? "1 anmeldelse mere" : k + " anmeldelser mere") + " til −" + p + " %",
  toCo: "Videre til kassen", payAfter: "Betaling først efter vellykket sletning", subtotal: "Subtotal",
  sheet: {
    t1: ["Op til 4 uger gammel", "Direkte anmeldelse til Google", "ca. 90 % chance for succes"],
    t2: ["Ældre end 4 uger", "Først en juridisk meddelelse til Google", "over 90 % chance for succes"],
    t3: ["Uden tekst eller fra USA", "Kun muligt med specialsoftware. Vi tjekker først, om det lykkes."],
    per: "pr. anmeldelse", from: (n) => "fra " + n, riskR: " Du betaler først, når anmeldelsen er slettet.",
  },
  protH: "Beskyttelse mod genudgivelse",
  protSub: "Slettede profiler kan dukke op igen. Med beskyttelse fjerner vi dem igen – gratis.",
  protD: { monthly: "Gratis ny sletning, når du har brug for det.", monitor: "Vi tjekker dagligt og sletter automatisk – uden at du gør noget.", lifetime: "Betal én gang, beskyttet for altid – overvågning inkluderet." },
  protNone: "Uden beskyttelse", protNoneD: "Kan stadig tilføjes senere.", perMonth: " / md.", cancel: "Opsigeligt månedligt", once: "engangsbeløb",
  warnB: "Uden beskyttelse fjerner vi ikke en genopstået profil gratis.", warnR: " Risikoen for genudgivelse bærer du så selv.",
  exT: "Sådan kan din profil komme tilbage", exN: ["Tredjeparter – ofte konkurrenter – opretter den igen", "Google henter data fra hjemmesider", "Profilen er tilbage på Google Maps"],
  yourSel: "Dit valg", fromDel: "fra sletning", today: "Betales i dag", billNote: "Faktureres først efter vellykket sletning.", todayShort: (v) => "I dag " + v,
  coSub: "Kun det nødvendige. Du betaler først efter en vellykket sletning.",
  f: { name: "Dit navn", email: "E-mail", phone: "Telefon", optional: "valgfrit", company: "Virksomhed" },
  order: "Bestil med betalingspligt", nothingToday: "Der trækkes intet i dag",
  payOnSuccess: "Betaling efter succes", total: "I alt ved succes", how: "Hvordan foregår afregningen?",
  howA: [["Vi tjekker og går i gang.", " Så snart der er en betalingsmetode i dit dashboard, starter vi."], ["Du betaler pr. sletning.", " Fjernes kun én af to anmeldelser, betaler du kun for den."], ["Ingen succes, ingen betaling.", " Lykkes det ikke, betaler du intet."]],
  howB: [["Vi starter med det samme.", " Alle næste trin får du på e-mail."], ["Afregning efter sletning.", " Først når profilen er væk, får du betalingslink og faktura – en beskyttelse starter derfra."], ["Ingen succes, ingen betaling.", " Lykkes det ikke, betaler du intet."]],
  lineSub: { std: "Direkte anmeldelse til Google", legal: "Juridisk meddelelse til Google", nt: "Specialsoftware · forhåndstjek" },
  delN: (n) => (n === 1 ? "Slet 1 anmeldelse" : "Slet " + n + " anmeldelser"),
  expressSub: "Behandles på ~6 t",
  verified: "Verificeret anmeldelse", tpFoot: (r, n) => [r, " ud af " + n + " anmeldelser på Trustpilot"],
  thanksH: "Mange tak.", thanksSub: "Vi har modtaget din bestilling. Bekræftelsen kommer på e-mail – vi kontakter dig inden for 24 timer.", newOrder: "Ny bestilling",
  sending: "Bestillingen sendes …",
};

const no = {
  ...en,
  sub0: "Velg tjenesten du trenger.", badgeTop: "Mest valgt",
  tiles: {
    delete: ["Slett Google-bedriftsprofil", "Profilen fjernes permanent, sammen med alle omtaler."],
    reviews: ["Slett enkeltomtaler", "Valgte omtaler fjernes, profilen blir stående."],
    press: ["Negativ presse eller søkeresultater", "En artikkel eller et Google-treff som skal forsvinne."],
    unsure: ["Usikker?", "To raske spørsmål, så viser vi vei."],
  },
  labelsA: ["Bedrift", "Profilsøk", "Bekreft", "Tjeneste", "Omtaler", "Kasse", "Ferdig"],
  labelsB: ["Bedrift", "Profilsøk", "Bekreft", "Tjeneste", "Beskyttelse", "Kasse", "Ferdig"],
  stepOf: (n, t) => ["Steg " + n, " av " + t],
  eta2: "ca. 2 min", eta1: "ca. 1 min", almost: "Nesten ferdig", doneLbl: "Ferdig",
  expert: "Snakk med en Google-ekspert", online: "Tilgjengelig nå",
  sub1: "Vi søker etter Google-bedriftsprofilen din.", find: "Finn profil",
  searchH: "Vi søker etter profilen din …", searchSub: (n) => ["Et øyeblikk – vi søker etter ", n, " på Google Maps."],
  checkH: "Vi sjekker profilen din …", checkSub: (n) => ["Et øyeblikk – vi sjekker ", n, "."],
  st: ["Søker på Google Maps", "Sammenligner profilen", "Sjekker om den kan slettes"],
  altNotMineSub: "Søk på nytt med et annet navn", altNotFound: "Finner du ikke profilen?",
  altNotFoundA: "Skriv inn lenker til omtalene", altNotFoundB: "Skriv inn en Google Maps-lenke",
  svcH: "Hva kan vi gjøre for deg?", svcSub: "Velg riktig tjeneste. Du betaler først etter vellykket sletting.",
  svcOk: "Profilen din kan slettes",
  svc1: ["Slett profil", "Profilen forsvinner for godt – og alle omtaler med den.", ["Alle omtaler borte", "Vanligvis innen 24 t"]],
  svc2: ["Slett profil + ny start", "Vi sletter den gamle profilen og oppretter en ny – med 0 omtaler.", ["Ny, verifisert profil", "En ren ny start"]],
  reviewsNA: "Vi sletter ikke enkeltomtaler for profiler i Tyskland og Østerrike. Hele profilen kan slettes.",
  naH: (c) => "Vi sletter ikke enkeltomtaler i {c}".replace("{c}", c), naSub: (c) => "Profilen din ligger i {c}. På grunn av den juridiske situasjonen der får vi ikke fjerne enkeltomtaler på Google; det er forbeholdt advokater. Dette kan vi gjøre for profilen din i stedet:".replace("{c}", c), naOpts: "Tilgjengelige tjenester for profilen din", naWrong: "Feil profil? Søk på nytt", naLegal: "Generell informasjon, ikke juridisk rådgivning.",
  change: "Endre", riskT: "Ingen suksess, ingen kostnad.", riskD: "Du betaler først når profilen faktisk er slettet.",
  ldSub: (n) => ["Vi henter alle omtaler av ", n, " fra Google Maps."], ldFound: "omtaler funnet",
  nRev: (n) => (n === 1 ? "1 omtale" : n + " omtaler"), selAll: "Velg alle", selNone: "Fjern valg",
  noText: "Omtale uten tekst",
  tag: { std: "ca. 90 %", legal: "over 90 %", sw: "Forhåndssjekk" },
  cat: { std: "Opptil 4 uker", legal: "Eldre enn 4 uker", nt: "Uten tekst", sw: "Spesialprogramvare" },
  selN: (n) => (!n ? "Ingen omtale valgt" : n === 1 ? "1 omtale valgt" : n + " omtaler valgt"),
  selShort: (n) => (n ? n + " valgt" : "Ingen valgt"), pickOne: "Velg minst én omtale.",
  nudge: (k, p) => (k === 1 ? "1 omtale til" : k + " omtaler til") + " for −" + p + " %",
  toCo: "Videre til kassen", payAfter: "Betaling først etter vellykket sletting", subtotal: "Delsum",
  sheet: {
    t1: ["Opptil 4 uker gammel", "Direkte melding til Google", "ca. 90 % sjanse for suksess"],
    t2: ["Eldre enn 4 uker", "Først en juridisk melding til Google", "over 90 % sjanse for suksess"],
    t3: ["Uten tekst eller fra USA", "Bare mulig med spesialprogramvare. Vi sjekker først om det går."],
    per: "per omtale", from: (n) => "fra " + n, riskR: " Du betaler først når omtalen er slettet.",
  },
  protH: "Beskyttelse mot ny publisering",
  protSub: "Slettede profiler kan dukke opp igjen. Med beskyttelse fjerner vi dem igjen – gratis.",
  protD: { monthly: "Gratis ny sletting når du trenger det.", monitor: "Vi sjekker daglig og sletter automatisk – uten at du gjør noe.", lifetime: "Betal én gang, beskyttet for alltid – overvåking inkludert." },
  protNone: "Uten beskyttelse", protNoneD: "Kan legges til senere.", perMonth: " / mnd.", cancel: "Kan sies opp månedlig", once: "engangsbeløp",
  warnB: "Uten beskyttelse fjerner vi ikke en profil som dukker opp igjen gratis.", warnR: " Risikoen for ny publisering bærer du da selv.",
  exT: "Slik kan profilen din komme tilbake", exN: ["Tredjeparter – ofte konkurrenter – oppretter den igjen", "Google henter data fra nettsider", "Profilen er tilbake på Google Maps"],
  yourSel: "Ditt valg", fromDel: "fra sletting", today: "Betales i dag", billNote: "Faktureres først etter vellykket sletting.", todayShort: (v) => "I dag " + v,
  coSub: "Bare det nødvendige. Du betaler først etter vellykket sletting.",
  f: { name: "Ditt navn", email: "E-post", phone: "Telefon", optional: "valgfritt", company: "Bedrift" },
  order: "Bestill med betalingsplikt", nothingToday: "Ingenting trekkes i dag",
  payOnSuccess: "Betaling etter suksess", total: "Totalt ved suksess", how: "Hvordan foregår faktureringen?",
  howA: [["Vi sjekker og starter.", " Så snart en betalingsmåte ligger i dashbordet ditt, setter vi i gang."], ["Du betaler per sletting.", " Fjernes bare én av to omtaler, betaler du bare for den."], ["Ingen suksess, ingen kostnad.", " Lykkes det ikke, betaler du ingenting."]],
  howB: [["Vi starter med en gang.", " Alle neste steg får du på e-post."], ["Fakturering etter sletting.", " Først når profilen er borte, får du betalingslenke og faktura – en beskyttelse starter fra da."], ["Ingen suksess, ingen kostnad.", " Lykkes det ikke, betaler du ingenting."]],
  lineSub: { std: "Direkte melding til Google", legal: "Juridisk melding til Google", nt: "Spesialprogramvare · forhåndssjekk" },
  delN: (n) => (n === 1 ? "Slett 1 omtale" : "Slett " + n + " omtaler"),
  expressSub: "Behandles på ~6 t",
  verified: "Verifisert omtale", tpFoot: (r, n) => [r, " av " + n + " omtaler på Trustpilot"],
  thanksH: "Tusen takk.", thanksSub: "Vi har mottatt bestillingen din. Bekreftelsen kommer på e-post – vi tar kontakt innen 24 timer.", newOrder: "Ny bestilling",
  sending: "Bestillingen sendes …",
};

export const BP_COPY = { de, en, es, fr, it, nl, pt, ja, sv, da, no };
export const bpCopy = (code) => BP_COPY[code] || en;
