/* Gemeinsame Definition des Bestell-Fragebogens.
   Genutzt von der Funnel-Danke-Seite, der öffentlichen Ausfüll-Seite und dem Admin.
   `t` = Frage je Sprache; `short` = deutsches Kurzlabel (Admin ist immer DE). */
export const FORM_QUESTIONS = [
  {
    key: "verified", short: "Verifizierter Inhaber",
    t: {
      de: "Sind Sie verifizierter Inhaber Ihres Google-Unternehmensprofils?",
      en: "Are you the verified owner of your Google Business Profile?",
      es: "¿Es usted el propietario verificado de su perfil de empresa de Google?",
      fr: "Êtes-vous le propriétaire vérifié de votre fiche d'établissement Google ?",
      it: "Sei il proprietario verificato del tuo profilo dell'attività su Google?",
      nl: "Bent u de geverifieerde eigenaar van uw Google-bedrijfsprofiel?",
      pt: "Você é o proprietário verificado do seu Perfil da Empresa no Google?",
      ja: "ご自身がGoogleビジネスプロフィールの確認済みオーナーですか？",
      sv: "Är du den verifierade ägaren av din Google Företagsprofil?",
      da: "Er du den verificerede ejer af din Google Virksomhedsprofil?",
      no: "Er du den verifiserte eieren av din Google bedriftsprofil?",
    },
  },
  {
    key: "smsOk", short: "Telefon empfängt SMS",
    t: {
      de: "Ist die in Ihrem Profil eingetragene Telefonnummer korrekt und kann Textnachrichten (SMS) empfangen?",
      en: "Is the phone number listed in your profile correct and able to receive text messages (SMS)?",
      es: "¿El número de teléfono que figura en su perfil es correcto y puede recibir mensajes de texto (SMS)?",
      fr: "Le numéro de téléphone indiqué sur votre fiche est-il correct et peut-il recevoir des SMS ?",
      it: "Il numero di telefono indicato nel tuo profilo è corretto e può ricevere messaggi (SMS)?",
      nl: "Is het telefoonnummer in uw profiel correct en kan het sms-berichten ontvangen?",
      pt: "O número de telefone no seu perfil está correto e pode receber mensagens de texto (SMS)?",
      ja: "プロフィールに登録された電話番号は正しく、テキストメッセージ（SMS）を受信できますか？",
      sv: "Är telefonnumret i din profil korrekt och kan ta emot textmeddelanden (SMS)?",
      da: "Er telefonnummeret i din profil korrekt og kan modtage tekstbeskeder (SMS)?",
      no: "Er telefonnummeret i profilen din korrekt og kan motta tekstmeldinger (SMS)?",
    },
  },
  {
    key: "nameChange", short: "Namensänderung ok",
    t: {
      de: "Sind Sie einverstanden, wenn sich der sichtbare Name Ihres Unternehmensprofils kurzfristig ändert? (kann manchmal für eine Löschung notwendig sein)",
      en: "Do you agree if the visible name of your business profile changes temporarily? (sometimes necessary for a removal)",
      es: "¿Está de acuerdo con que el nombre visible de su perfil de empresa cambie temporalmente? (a veces necesario para una eliminación)",
      fr: "Acceptez-vous que le nom visible de votre fiche change temporairement ? (parfois nécessaire pour une suppression)",
      it: "Sei d'accordo se il nome visibile del tuo profilo cambia temporaneamente? (a volte necessario per una rimozione)",
      nl: "Gaat u ermee akkoord als de zichtbare naam van uw bedrijfsprofiel tijdelijk verandert? (soms nodig voor een verwijdering)",
      pt: "Você concorda se o nome visível do seu perfil mudar temporariamente? (às vezes necessário para uma remoção)",
      ja: "ビジネスプロフィールの表示名が一時的に変更されることに同意しますか？（削除のために必要な場合があります）",
      sv: "Godkänner du att det synliga namnet på din företagsprofil ändras tillfälligt? (ibland nödvändigt för en borttagning)",
      da: "Accepterer du, at det synlige navn på din virksomhedsprofil ændres midlertidigt? (nogle gange nødvendigt for en sletning)",
      no: "Godtar du at det synlige navnet på bedriftsprofilen din endres midlertidig? (noen ganger nødvendig for en sletting)",
    },
  },
  {
    key: "owner", short: "Berechtigt / Inhaber",
    t: {
      de: "Sind Sie der rechtmäßige Inhaber des Unternehmens oder wurden Sie von Ihrem Vorgesetzten beauftragt, die Löschung in Auftrag zu geben?",
      en: "Are you the rightful owner of the business, or were you authorized by your superior to order the removal?",
      es: "¿Es usted el propietario legítimo de la empresa o ha sido autorizado por su superior para solicitar la eliminación?",
      fr: "Êtes-vous le propriétaire légitime de l'entreprise ou avez-vous été autorisé par votre supérieur à demander la suppression ?",
      it: "Sei il legittimo proprietario dell'attività o sei stato autorizzato dal tuo superiore a richiedere la rimozione?",
      nl: "Bent u de rechtmatige eigenaar van het bedrijf of bent u door uw leidinggevende gemachtigd om de verwijdering aan te vragen?",
      pt: "Você é o proprietário legítimo da empresa ou foi autorizado pelo seu superior a solicitar a remoção?",
      ja: "あなたは事業の正当な所有者ですか、または上司から削除を依頼する権限を与えられていますか？",
      sv: "Är du företagets rättmätiga ägare eller har du fått tillstånd av din chef att beställa borttagningen?",
      da: "Er du virksomhedens retmæssige ejer, eller er du blevet bemyndiget af din overordnede til at bestille sletningen?",
      no: "Er du den rettmessige eieren av virksomheten, eller har du fått fullmakt av din overordnede til å bestille slettingen?",
    },
  },
  {
    key: "payment48", short: "48-Std-Zahlung bewusst",
    t: {
      de: "Ist Ihnen bewusst, dass nach der Löschung eine Zahlung innerhalb von 48 Stunden erfolgen muss, da das Unternehmen ansonsten automatisch wieder online gestellt wird?",
      en: "Are you aware that after removal, payment must be made within 48 hours, otherwise the business is automatically restored online?",
      es: "¿Es consciente de que, tras la eliminación, el pago debe realizarse en un plazo de 48 horas, ya que de lo contrario la empresa se restablecerá automáticamente en línea?",
      fr: "Êtes-vous conscient qu'après la suppression, le paiement doit être effectué sous 48 heures, faute de quoi l'établissement sera automatiquement remis en ligne ?",
      it: "Sei consapevole che, dopo la rimozione, il pagamento deve avvenire entro 48 ore, altrimenti l'attività viene automaticamente ripristinata online?",
      nl: "Bent u zich ervan bewust dat na de verwijdering de betaling binnen 48 uur moet plaatsvinden, omdat het bedrijf anders automatisch weer online wordt gezet?",
      pt: "Você está ciente de que, após a remoção, o pagamento deve ser feito em até 48 horas, caso contrário a empresa é automaticamente restaurada online?",
      ja: "削除後、48時間以内に支払いが必要であり、そうしない場合は事業が自動的に再びオンラインに戻ることをご承知ですか？",
      sv: "Är du medveten om att betalning måste ske inom 48 timmar efter borttagningen, annars återställs företaget automatiskt online?",
      da: "Er du klar over, at betaling skal ske inden for 48 timer efter sletningen, da virksomheden ellers automatisk gøres online igen?",
      no: "Er du klar over at betaling må skje innen 48 timer etter slettingen, ellers settes virksomheten automatisk online igjen?",
    },
  },
];
