/* RapidRemove — Texte der Landingpage „Einzelne Bewertung löschen".
   Liegt als reines Datenmodul hier (nicht in der "use client"-Komponente),
   weil auch Server-Code sie braucht: JSON-LD der Landingpage und der
   Service-Hinweis-Block in den Bewertungs-Ratgeberartikeln.
   en/es/fr/it/nl/pt: freigegebene Handoff-Texte; ja/sv/da/no im selben Ton.
   KEIN Deutsch — das Produkt gibt es nicht in DACH. */
export const RVW = {
  en: {
    eyebrow: "New service",
    h1: "Remove a single Google review.",
    lead: "Sometimes it's not the whole profile — it's one review that is unfair or simply false. We take care of exactly that one. You pay per removed review, nothing upfront.",
    price: "$179", per: "per removed review",
    priceNote: "You're only charged once the review is actually gone. If we can't remove it, you pay nothing.",
    condNote: "Please note: the review must be no older than 4 weeks and must contain text — star-only ratings can't be removed.",
    cta: "Send us the review",
    assure: ["Nothing upfront", "Pay per removed review", "Honest assessment first"],
    stepsEyebrow: "How it works", stepsH: "Three steps, no paperwork.",
    steps: [
      { t: "Send the link", d: "Open the review, tap share, and paste the link into the form — one per review, the + adds more." },
      { t: "We take a look", d: "Someone from our team reads it and tells you honestly whether we can remove it." },
      { t: "Gone — then you pay", d: "If the review comes down, you pay $179. If it stays, you pay nothing." },
    ],
    honestyEyebrow: "Honestly", honestyH: "What we can remove — and what we can't.",
    yesH: "Good chances", noH: "We won't promise",
    yes: ["Fake reviews and competitor attacks", "Reviews from people who were never customers", "Insults and false claims", "Reviews that break Google's rules"],
    no: ["Honest criticism from real customers", "A guarantee for every review — nobody can give that"],
    formEyebrow: "Free assessment", formH: "Send us the review.",
    formSub: "We'll reply with an honest answer: yes we can, or no we can't. Free either way.",
    how: { eyebrow: "Where do I find the link?", h: "Copying the review link takes ten seconds.", steps: ["Find the review on your Google profile and tap it to open it.", "Tap the share icon below the review.", "Copy the link and paste it into the form — one per review, as many as you like."], alt: "No share option there? Then simply enter the reviewer's name and the review text instead — that identifies the review just as well.", copyHint: "Click to copy the link", shareT: "Share review", copied: "Copied" },
    faqEyebrow: "Questions", faqH: "Good to know.",
    faq: [
      { q: "How long does it take?", a: "Usually a few days, sometimes up to three weeks. We keep you posted." },
      { q: "What if the review can't be removed?", a: "Then you pay nothing. We tell you upfront if we think the chances are poor." },
      { q: "Will the reviewer find out it was me?", a: "No. The reviewer is not told who requested the removal." },
      { q: "I have several reviews.", a: "The price is per review. Add as many as you like in the form with the + — and you only pay for the ones actually removed." },
    ],
    finalH: "One review shouldn't define your business.",
    finalCta: "Send us the review",
    demoRemoved: "Removed",
    demoName: "Your business",
  },
  es: {
    eyebrow: "Nuevo servicio",
    h1: "Elimina una reseña concreta de Google.",
    lead: "A veces no es todo el perfil: es una reseña injusta o simplemente falsa. Nos ocupamos exactamente de esa. Pagas por reseña eliminada, nada por adelantado.",
    price: "179 €", per: "por reseña eliminada",
    priceNote: "Solo se cobra cuando la reseña ha desaparecido. Si no podemos eliminarla, no pagas nada.",
    condNote: "Importante: la reseña debe tener como máximo 4 semanas y debe contener texto — las valoraciones solo con estrellas no se pueden eliminar.",
    cta: "Envíanos la reseña",
    assure: ["Nada por adelantado", "Pago por reseña eliminada", "Primero una valoración honesta"],
    stepsEyebrow: "Cómo funciona", stepsH: "Tres pasos, sin papeleo.",
    steps: [
      { t: "Envía el enlace", d: "Abre la reseña, toca compartir y pega el enlace en el formulario — uno por reseña, con el + añades más." },
      { t: "La revisamos", d: "Alguien de nuestro equipo la lee y te dice con franqueza si podemos eliminarla." },
      { t: "Desaparece — y entonces pagas", d: "Si la reseña se retira, pagas 179 €. Si se queda, no pagas nada." },
    ],
    honestyEyebrow: "Con franqueza", honestyH: "Qué podemos eliminar — y qué no.",
    yesH: "Buenas posibilidades", noH: "No prometemos",
    yes: ["Reseñas falsas y ataques de competidores", "Reseñas de personas que nunca fueron clientes", "Insultos y afirmaciones falsas", "Reseñas que incumplen las normas de Google"],
    no: ["Críticas honestas de clientes reales", "Una garantía para cualquier reseña — nadie puede darla"],
    formEyebrow: "Valoración gratuita", formH: "Envíanos la reseña.",
    formSub: "Te responderemos con una respuesta honesta: sí podemos, o no podemos. Gratis en ambos casos.",
    how: { eyebrow: "¿Dónde está el enlace?", h: "Copiar el enlace de la reseña lleva diez segundos.", steps: ["Busca la reseña en tu perfil de Google y tócala para abrirla.", "Toca el icono de compartir debajo de la reseña.", "Copia el enlace y pégalo en el formulario — uno por reseña, tantas como quieras."], alt: "¿No aparece la opción de compartir? Entonces indica el nombre del autor y el texto de la reseña — la identifica igual de bien.", copyHint: "Haz clic para copiar el enlace", shareT: "Compartir reseña", copied: "Copiado" },
    faqEyebrow: "Preguntas", faqH: "Bueno saberlo.",
    faq: [
      { q: "¿Cuánto tarda?", a: "Normalmente unos días, a veces hasta tres semanas. Te mantenemos informado." },
      { q: "¿Y si no se puede eliminar?", a: "Entonces no pagas nada. Si vemos pocas posibilidades, te lo decimos desde el principio." },
      { q: "¿Sabrá el autor que fui yo?", a: "No. Al autor no se le comunica quién solicitó la eliminación." },
      { q: "Tengo varias reseñas.", a: "El precio es por reseña. Añade tantas como quieras en el formulario con el + — y solo pagas las que realmente se eliminan." },
    ],
    finalH: "Una reseña no debería definir tu negocio.",
    finalCta: "Envíanos la reseña",
    demoRemoved: "Eliminada",
    demoName: "Tu negocio",
  },
  fr: {
    eyebrow: "Nouveau service",
    h1: "Supprimez un avis Google précis.",
    lead: "Parfois ce n'est pas toute la fiche — c'est un avis injuste ou tout simplement faux. Nous nous occupons exactement de celui-là. Vous payez par avis supprimé, rien d'avance.",
    price: "179 €", per: "par avis supprimé",
    priceNote: "Vous n'êtes débité que lorsque l'avis a réellement disparu. Si nous ne pouvons pas le supprimer, vous ne payez rien.",
    condNote: "À savoir : l'avis doit dater de 4 semaines au maximum et contenir du texte — les notes composées uniquement d'étoiles ne peuvent pas être supprimées.",
    cta: "Envoyez-nous l'avis",
    assure: ["Rien d'avance", "Paiement par avis supprimé", "D'abord un avis honnête"],
    stepsEyebrow: "Comment ça marche", stepsH: "Trois étapes, zéro paperasse.",
    steps: [
      { t: "Envoyez le lien", d: "Ouvrez l'avis, touchez « Partager » et collez le lien dans le formulaire — un par avis, le + en ajoute d'autres." },
      { t: "Nous le lisons", d: "Quelqu'un de notre équipe le lit et vous dit franchement si nous pouvons le supprimer." },
      { t: "Disparu — vous payez alors", d: "Si l'avis est retiré, vous payez 179 €. S'il reste, vous ne payez rien." },
    ],
    honestyEyebrow: "Franchement", honestyH: "Ce que nous pouvons supprimer — et ce que non.",
    yesH: "Bonnes chances", noH: "Nous ne promettons pas",
    yes: ["Faux avis et attaques de concurrents", "Avis de personnes qui n'ont jamais été clientes", "Insultes et affirmations fausses", "Avis contraires aux règles de Google"],
    no: ["Critiques honnêtes de vrais clients", "Une garantie pour chaque avis — personne ne peut la donner"],
    formEyebrow: "Évaluation gratuite", formH: "Envoyez-nous l'avis.",
    formSub: "Nous vous répondrons honnêtement : oui c'est possible, ou non. Gratuit dans les deux cas.",
    how: { eyebrow: "Où trouver le lien ?", h: "Copier le lien de l'avis prend dix secondes.", steps: ["Trouvez l'avis sur votre fiche Google et touchez-le pour l'ouvrir.", "Touchez l'icône de partage sous l'avis.", "Copiez le lien et collez-le dans le formulaire — un par avis, autant que vous voulez."], alt: "Pas d'option de partage ? Indiquez alors le nom de l'auteur et le texte de l'avis — cela l'identifie tout aussi bien.", copyHint: "Cliquez pour copier le lien", shareT: "Partager l'avis", copied: "Copié" },
    faqEyebrow: "Questions", faqH: "Bon à savoir.",
    faq: [
      { q: "Combien de temps cela prend-il ?", a: "En général quelques jours, parfois jusqu'à trois semaines. Nous vous tenons informé." },
      { q: "Et si l'avis ne peut pas être supprimé ?", a: "Alors vous ne payez rien. Si les chances nous semblent faibles, nous vous le disons d'emblée." },
      { q: "L'auteur saura-t-il que c'est moi ?", a: "Non. L'auteur n'est pas informé de qui a demandé la suppression." },
      { q: "J'ai plusieurs avis.", a: "Le prix est par avis. Ajoutez-en autant que vous voulez dans le formulaire avec le + — et vous ne payez que ceux réellement supprimés." },
    ],
    finalH: "Un avis ne devrait pas définir votre entreprise.",
    finalCta: "Envoyez-nous l'avis",
    demoRemoved: "Supprimé",
    demoName: "Votre entreprise",
  },
  it: {
    eyebrow: "Nuovo servizio",
    h1: "Elimina una singola recensione Google.",
    lead: "A volte non è tutto il profilo — è una recensione ingiusta o semplicemente falsa. Ci occupiamo esattamente di quella. Paghi per recensione eliminata, niente in anticipo.",
    price: "179 €", per: "per recensione eliminata",
    priceNote: "L'addebito avviene solo quando la recensione è davvero sparita. Se non riusciamo a eliminarla, non paghi nulla.",
    condNote: "Da sapere: la recensione non deve avere più di 4 settimane e deve contenere testo — le valutazioni con sole stelle non si possono eliminare.",
    cta: "Inviaci la recensione",
    assure: ["Niente in anticipo", "Paghi per recensione eliminata", "Prima una valutazione onesta"],
    stepsEyebrow: "Come funziona", stepsH: "Tre passi, zero burocrazia.",
    steps: [
      { t: "Invia il link", d: "Apri la recensione, tocca condividi e incolla il link nel modulo — uno per recensione, col + ne aggiungi altre." },
      { t: "La leggiamo", d: "Qualcuno del nostro team la legge e ti dice onestamente se possiamo eliminarla." },
      { t: "Sparita — poi paghi", d: "Se la recensione viene rimossa, paghi 179 €. Se resta, non paghi nulla." },
    ],
    honestyEyebrow: "Onestamente", honestyH: "Cosa possiamo eliminare — e cosa no.",
    yesH: "Buone probabilità", noH: "Non promettiamo",
    yes: ["Recensioni false e attacchi di concorrenti", "Recensioni di persone mai state clienti", "Insulti e affermazioni false", "Recensioni contro le regole di Google"],
    no: ["Critiche oneste di clienti veri", "Una garanzia per ogni recensione — nessuno può darla"],
    formEyebrow: "Valutazione gratuita", formH: "Inviaci la recensione.",
    formSub: "Ti risponderemo con onestà: sì possiamo, oppure no. Gratis in entrambi i casi.",
    how: { eyebrow: "Dove trovo il link?", h: "Copiare il link della recensione richiede dieci secondi.", steps: ["Trova la recensione sul tuo profilo Google e toccala per aprirla.", "Tocca l'icona di condivisione sotto la recensione.", "Copia il link e incollalo nel modulo — uno per recensione, quante vuoi."], alt: "Non c'è l'opzione di condivisione? Inserisci allora il nome dell'autore e il testo della recensione — la identifica altrettanto bene.", copyHint: "Clicca per copiare il link", shareT: "Condividi recensione", copied: "Copiato" },
    faqEyebrow: "Domande", faqH: "Da sapere.",
    faq: [
      { q: "Quanto ci vuole?", a: "Di solito qualche giorno, a volte fino a tre settimane. Ti teniamo aggiornato." },
      { q: "E se non si può eliminare?", a: "Allora non paghi nulla. Se le probabilità ci sembrano basse, te lo diciamo subito." },
      { q: "L'autore saprà che sono stato io?", a: "No. All'autore non viene comunicato chi ha chiesto la rimozione." },
      { q: "Ho più recensioni.", a: "Il prezzo è per recensione. Aggiungine quante vuoi nel modulo con il + — e paghi solo quelle davvero rimosse." },
    ],
    finalH: "Una recensione non dovrebbe definire la tua attività.",
    finalCta: "Inviaci la recensione",
    demoRemoved: "Rimossa",
    demoName: "La tua attività",
  },
  nl: {
    eyebrow: "Nieuwe dienst",
    h1: "Laat één losse Google-review verwijderen.",
    lead: "Soms is het niet het hele profiel — maar die ene review die oneerlijk of gewoon onwaar is. Precies die pakken wij aan. U betaalt per verwijderde review, niets vooraf.",
    price: "€ 179", per: "per verwijderde review",
    priceNote: "U betaalt pas als de review echt weg is. Kunnen we hem niet verwijderen, dan betaalt u niets.",
    condNote: "Let op: de review mag maximaal 4 weken oud zijn en moet tekst bevatten — beoordelingen met alleen sterren kunnen niet worden verwijderd.",
    cta: "Stuur ons de review",
    assure: ["Niets vooraf", "Betalen per verwijderde review", "Eerst een eerlijke inschatting"],
    stepsEyebrow: "Zo werkt het", stepsH: "Drie stappen, geen papierwerk.",
    steps: [
      { t: "Stuur de link", d: "Open de review, tik op delen en plak de link in het formulier — één per review, met de + voegt u er meer toe." },
      { t: "Wij kijken ernaar", d: "Iemand van ons team leest de review en zegt eerlijk of we hem kunnen verwijderen." },
      { t: "Weg — dan pas betalen", d: "Gaat de review eraf, dan betaalt u € 179. Blijft hij staan, dan betaalt u niets." },
    ],
    honestyEyebrow: "Eerlijk gezegd", honestyH: "Wat we kunnen verwijderen — en wat niet.",
    yesH: "Goede kansen", noH: "Dat beloven we niet",
    yes: ["Nepreviews en aanvallen van concurrenten", "Reviews van mensen die nooit klant waren", "Beledigingen en onware beweringen", "Reviews die de regels van Google schenden"],
    no: ["Eerlijke kritiek van echte klanten", "Een garantie voor elke review — die kan niemand geven"],
    formEyebrow: "Gratis inschatting", formH: "Stuur ons de review.",
    formSub: "U krijgt een eerlijk antwoord: ja het kan, of nee het kan niet. In beide gevallen gratis.",
    how: { eyebrow: "Waar vind ik de link?", h: "De link kopiëren duurt tien seconden.", steps: ["Zoek de review op uw Google-profiel en tik erop om hem te openen.", "Tik op het deelicoon onder de review.", "Kopieer de link en plak hem in het formulier — één per review, zoveel u wilt."], alt: "Geen deeloptie? Vul dan de naam van de schrijver en de tekst van de review in — dat identificeert hem net zo goed.", copyHint: "Klik om de link te kopiëren", shareT: "Review delen", copied: "Gekopieerd" },
    faqEyebrow: "Vragen", faqH: "Goed om te weten.",
    faq: [
      { q: "Hoe lang duurt het?", a: "Meestal een paar dagen, soms tot drie weken. We houden u op de hoogte." },
      { q: "En als de review niet weg kan?", a: "Dan betaalt u niets. Schatten we de kans laag in, dan zeggen we dat vooraf." },
      { q: "Weet de schrijver dat ik het was?", a: "Nee. De schrijver krijgt niet te horen wie om verwijdering heeft gevraagd." },
      { q: "Ik heb meerdere reviews.", a: "De prijs geldt per review. Voeg er in het formulier met de + zoveel toe als u wilt — u betaalt alleen voor wat echt verwijderd is." },
    ],
    finalH: "Eén review zou uw zaak niet mogen bepalen.",
    finalCta: "Stuur ons de review",
    demoRemoved: "Verwijderd",
    demoName: "Uw bedrijf",
  },
  pt: {
    eyebrow: "Novo serviço",
    h1: "Remova uma avaliação específica do Google.",
    lead: "Às vezes não é o perfil inteiro — é uma avaliação injusta ou simplesmente falsa. Cuidamos exatamente dessa. Paga por avaliação removida, nada adiantado.",
    price: "179 €", per: "por avaliação removida",
    priceNote: "Só é cobrado quando a avaliação desaparecer de facto. Se não conseguirmos removê-la, não paga nada.",
    condNote: "Atenção: a avaliação não pode ter mais de 4 semanas e tem de conter texto — classificações só com estrelas não podem ser removidas.",
    cta: "Envie-nos a avaliação",
    assure: ["Nada adiantado", "Pagamento por avaliação removida", "Primeiro uma opinião honesta"],
    stepsEyebrow: "Como funciona", stepsH: "Três passos, sem burocracia.",
    steps: [
      { t: "Envie o link", d: "Abra a avaliação, toque em partilhar e cole o link no formulário — um por avaliação, o + adiciona mais." },
      { t: "Nós analisamos", d: "Alguém da nossa equipa lê a avaliação e diz com honestidade se podemos removê-la." },
      { t: "Removida — só então paga", d: "Se a avaliação sair, paga 179 €. Se ficar, não paga nada." },
    ],
    honestyEyebrow: "Com honestidade", honestyH: "O que podemos remover — e o que não.",
    yesH: "Boas hipóteses", noH: "Não prometemos",
    yes: ["Avaliações falsas e ataques de concorrentes", "Avaliações de quem nunca foi cliente", "Insultos e afirmações falsas", "Avaliações que violam as regras do Google"],
    no: ["Críticas honestas de clientes reais", "Uma garantia para qualquer avaliação — ninguém pode dar isso"],
    formEyebrow: "Análise gratuita", formH: "Envie-nos a avaliação.",
    formSub: "Respondemos com honestidade: sim conseguimos, ou não conseguimos. Grátis nos dois casos.",
    how: { eyebrow: "Onde encontro o link?", h: "Copiar o link da avaliação leva dez segundos.", steps: ["Encontre a avaliação no seu perfil do Google e toque nela para a abrir.", "Toque no ícone de partilha por baixo da avaliação.", "Copie o link e cole-o no formulário — um por avaliação, quantas quiser."], alt: "Não há opção de partilha? Então indique o nome do autor e o texto da avaliação — identifica-a igualmente bem.", copyHint: "Clique para copiar o link", shareT: "Partilhar avaliação", copied: "Copiado" },
    faqEyebrow: "Perguntas", faqH: "Bom saber.",
    faq: [
      { q: "Quanto tempo demora?", a: "Normalmente alguns dias, às vezes até três semanas. Vamos mantendo-o informado." },
      { q: "E se não for possível remover?", a: "Então não paga nada. Se as hipóteses nos parecerem baixas, dizemos logo no início." },
      { q: "O autor saberá que fui eu?", a: "Não. O autor não é informado de quem pediu a remoção." },
      { q: "Tenho várias avaliações.", a: "O preço é por avaliação. Adicione quantas quiser no formulário com o + — e só paga as que forem mesmo removidas." },
    ],
    finalH: "Uma avaliação não devia definir o seu negócio.",
    finalCta: "Envie-nos a avaliação",
    demoRemoved: "Removida",
    demoName: "O seu negócio",
  },
  ja: {
    eyebrow: "新サービス",
    h1: "Googleの口コミを1件から削除。",
    lead: "プロフィール全体ではなく、不当な、あるいは事実と異なる口コミが1件だけ——そんなときは、その1件だけを私たちが対応します。お支払いは削除できた口コミの分だけ。前払いはありません。",
    price: "$179", per: "削除1件あたり",
    priceNote: "請求は口コミが実際に消えてからです。削除できなければ、お支払いは発生しません。",
    condNote: "ご注意：口コミは投稿から4週間以内で、本文があるものに限ります。星のみの評価は削除できません。",
    cta: "口コミを送る",
    assure: ["前払いなし", "削除1件ごとのお支払い", "まず正直な見立てから"],
    stepsEyebrow: "ご利用の流れ", stepsH: "3ステップ、面倒な手続きなし。",
    steps: [
      { t: "リンクを送る", d: "口コミを開いて共有をタップし、リンクをフォームに貼り付けます。1件につき1リンク、「+」で追加できます。" },
      { t: "内容を確認", d: "チームの担当者が口コミを読み、削除できるかどうかを正直にお伝えします。" },
      { t: "消えたら、お支払い", d: "口コミが削除されたら$179のお支払い。残った場合は何も支払いません。" },
    ],
    honestyEyebrow: "正直に", honestyH: "削除できるもの——できないもの。",
    yesH: "見込みが高いもの", noH: "お約束できないこと",
    yes: ["やらせの口コミ・競合による攻撃", "利用実績のない人による口コミ", "侮辱や事実と異なる主張", "Googleのルールに違反する口コミ"],
    no: ["実際のお客様による率直な批判", "どんな口コミでも消せるという保証——それは誰にもできません"],
    formEyebrow: "無料診断", formH: "口コミをお送りください。",
    formSub: "「できます」か「できません」か、正直にお答えします。どちらでも無料です。",
    how: { eyebrow: "リンクはどこに？", h: "口コミのリンクコピーは10秒で終わります。", steps: ["Googleプロフィールで口コミを見つけて、タップして開きます。", "口コミの下にある共有アイコンをタップします。", "リンクをコピーしてフォームに貼り付けます。1件につき1リンク、何件でも。"], alt: "共有ボタンが見つからない場合は、投稿者名と口コミ本文を入力してください。それでも同じように特定できます。", copyHint: "クリックしてリンクをコピー", shareT: "クチコミを共有", copied: "コピーしました" },
    faqEyebrow: "よくある質問", faqH: "知っておきたいこと。",
    faq: [
      { q: "どのくらいかかりますか？", a: "通常は数日、長い場合で3週間ほどです。進捗は随時ご連絡します。" },
      { q: "削除できなかったら？", a: "その場合、お支払いはありません。見込みが低いと判断したときは、最初にそうお伝えします。" },
      { q: "投稿者に依頼者が知られますか？", a: "いいえ。誰が削除を依頼したかが投稿者に伝わることはありません。" },
      { q: "口コミが複数あります。", a: "料金は1件ごとです。フォームの「+」で何件でも追加でき、実際に削除できた分だけのお支払いです。" },
    ],
    finalH: "たった1件の口コミに、お店の評価を決めさせない。",
    finalCta: "口コミを送る",
    demoRemoved: "削除済み",
    demoName: "あなたのお店",
  },
  sv: {
    eyebrow: "Ny tjänst",
    h1: "Ta bort ett enskilt Google-omdöme.",
    lead: "Ibland är det inte hela profilen — det är ett enda omdöme som är orättvist eller helt enkelt falskt. Vi tar hand om exakt det. Du betalar per borttaget omdöme, inget i förskott.",
    price: "179 €", per: "per borttaget omdöme",
    priceNote: "Du betalar först när omdömet faktiskt är borta. Kan vi inte ta bort det betalar du ingenting.",
    condNote: "Observera: omdömet får vara högst 4 veckor gammalt och måste innehålla text — betyg med enbart stjärnor kan inte tas bort.",
    cta: "Skicka omdömet till oss",
    assure: ["Inget i förskott", "Betala per borttaget omdöme", "Först en ärlig bedömning"],
    stepsEyebrow: "Så fungerar det", stepsH: "Tre steg, inget pappersarbete.",
    steps: [
      { t: "Skicka länken", d: "Öppna omdömet, tryck på dela och klistra in länken i formuläret — en per omdöme, med + lägger du till fler." },
      { t: "Vi tittar på det", d: "Någon i vårt team läser omdömet och säger ärligt om vi kan ta bort det." },
      { t: "Borta — då betalar du", d: "Tas omdömet bort betalar du 179 €. Står det kvar betalar du ingenting." },
    ],
    honestyEyebrow: "Ärligt talat", honestyH: "Vad vi kan ta bort — och vad vi inte kan.",
    yesH: "Goda chanser", noH: "Det lovar vi inte",
    yes: ["Falska omdömen och angrepp från konkurrenter", "Omdömen från personer som aldrig varit kunder", "Förolämpningar och osanna påståenden", "Omdömen som bryter mot Googles regler"],
    no: ["Ärlig kritik från riktiga kunder", "En garanti för varje omdöme — det kan ingen ge"],
    formEyebrow: "Gratis bedömning", formH: "Skicka omdömet till oss.",
    formSub: "Du får ett ärligt svar: ja det går, eller nej det går inte. Gratis i båda fallen.",
    how: { eyebrow: "Var hittar jag länken?", h: "Att kopiera länken tar tio sekunder.", steps: ["Hitta omdömet på din Google-profil och tryck på det för att öppna det.", "Tryck på delningsikonen under omdömet.", "Kopiera länken och klistra in den i formuläret — en per omdöme, så många du vill."], alt: "Ingen delningsknapp? Ange då recensentens namn och omdömets text — det identifierar omdömet lika bra.", copyHint: "Klicka för att kopiera länken", shareT: "Dela omdöme", copied: "Kopierad" },
    faqEyebrow: "Frågor", faqH: "Bra att veta.",
    faq: [
      { q: "Hur lång tid tar det?", a: "Oftast några dagar, ibland upp till tre veckor. Vi håller dig uppdaterad." },
      { q: "Och om omdömet inte kan tas bort?", a: "Då betalar du ingenting. Bedömer vi chanserna som små säger vi det från början." },
      { q: "Får recensenten veta att det var jag?", a: "Nej. Recensenten får inte veta vem som begärde borttagningen." },
      { q: "Jag har flera omdömen.", a: "Priset gäller per omdöme. Lägg till så många du vill i formuläret med + — och du betalar bara för dem som faktiskt tas bort." },
    ],
    finalH: "Ett omdöme ska inte definiera ditt företag.",
    finalCta: "Skicka omdömet till oss",
    demoRemoved: "Borttaget",
    demoName: "Ditt företag",
  },
  da: {
    eyebrow: "Ny ydelse",
    h1: "Fjern en enkelt Google-anmeldelse.",
    lead: "Nogle gange er det ikke hele profilen — det er én anmeldelse, der er urimelig eller simpelthen falsk. Vi tager os af præcis den. Du betaler pr. fjernet anmeldelse, intet på forhånd.",
    price: "179 €", per: "pr. fjernet anmeldelse",
    priceNote: "Du betaler først, når anmeldelsen faktisk er væk. Kan vi ikke fjerne den, betaler du ingenting.",
    condNote: "Bemærk: anmeldelsen må højst være 4 uger gammel og skal indeholde tekst — bedømmelser med kun stjerner kan ikke fjernes.",
    cta: "Send os anmeldelsen",
    assure: ["Intet på forhånd", "Betal pr. fjernet anmeldelse", "Først en ærlig vurdering"],
    stepsEyebrow: "Sådan fungerer det", stepsH: "Tre trin, intet papirarbejde.",
    steps: [
      { t: "Send linket", d: "Åbn anmeldelsen, tryk på del og indsæt linket i formularen — ét pr. anmeldelse, med + tilføjer du flere." },
      { t: "Vi kigger på den", d: "En fra vores team læser anmeldelsen og siger ærligt, om vi kan fjerne den." },
      { t: "Væk — så betaler du", d: "Fjernes anmeldelsen, betaler du 179 €. Bliver den stående, betaler du ingenting." },
    ],
    honestyEyebrow: "Ærligt talt", honestyH: "Hvad vi kan fjerne — og hvad vi ikke kan.",
    yesH: "Gode chancer", noH: "Det lover vi ikke",
    yes: ["Falske anmeldelser og angreb fra konkurrenter", "Anmeldelser fra folk, der aldrig var kunder", "Fornærmelser og usande påstande", "Anmeldelser, der bryder Googles regler"],
    no: ["Ærlig kritik fra rigtige kunder", "En garanti for enhver anmeldelse — det kan ingen give"],
    formEyebrow: "Gratis vurdering", formH: "Send os anmeldelsen.",
    formSub: "Du får et ærligt svar: ja vi kan, eller nej vi kan ikke. Gratis i begge tilfælde.",
    how: { eyebrow: "Hvor finder jeg linket?", h: "At kopiere linket tager ti sekunder.", steps: ["Find anmeldelsen på din Google-profil, og tryk på den for at åbne den.", "Tryk på deleikonet under anmeldelsen.", "Kopiér linket og indsæt det i formularen — ét pr. anmeldelse, så mange du vil."], alt: "Ingen delemulighed? Angiv i stedet anmelderens navn og anmeldelsens tekst — det identificerer den lige så godt.", copyHint: "Klik for at kopiere linket", shareT: "Del anmeldelse", copied: "Kopieret" },
    faqEyebrow: "Spørgsmål", faqH: "Godt at vide.",
    faq: [
      { q: "Hvor lang tid tager det?", a: "Som regel få dage, nogle gange op til tre uger. Vi holder dig opdateret." },
      { q: "Hvad hvis anmeldelsen ikke kan fjernes?", a: "Så betaler du ingenting. Vurderer vi chancerne som små, siger vi det fra starten." },
      { q: "Finder anmelderen ud af, det var mig?", a: "Nej. Anmelderen får ikke at vide, hvem der bad om fjernelsen." },
      { q: "Jeg har flere anmeldelser.", a: "Prisen gælder pr. anmeldelse. Tilføj så mange du vil i formularen med + — og du betaler kun for dem, der faktisk fjernes." },
    ],
    finalH: "Én anmeldelse bør ikke definere din virksomhed.",
    finalCta: "Send os anmeldelsen",
    demoRemoved: "Fjernet",
    demoName: "Din virksomhed",
  },
  no: {
    eyebrow: "Ny tjeneste",
    h1: "Fjern én enkelt Google-omtale.",
    lead: "Noen ganger er det ikke hele profilen — det er én omtale som er urettferdig eller rett og slett falsk. Vi tar oss av akkurat den. Du betaler per fjernet omtale, ingenting på forskudd.",
    price: "179 €", per: "per fjernet omtale",
    priceNote: "Du betaler først når omtalen faktisk er borte. Klarer vi ikke å fjerne den, betaler du ingenting.",
    condNote: "Merk: omtalen kan maks være 4 uker gammel og må inneholde tekst — vurderinger med bare stjerner kan ikke fjernes.",
    cta: "Send oss omtalen",
    assure: ["Ingenting på forskudd", "Betal per fjernet omtale", "Først en ærlig vurdering"],
    stepsEyebrow: "Slik fungerer det", stepsH: "Tre steg, ikke noe papirarbeid.",
    steps: [
      { t: "Send lenken", d: "Åpne omtalen, trykk på del og lim inn lenken i skjemaet — én per omtale, med + legger du til flere." },
      { t: "Vi ser på den", d: "Noen fra teamet vårt leser omtalen og sier ærlig om vi kan fjerne den." },
      { t: "Borte — da betaler du", d: "Fjernes omtalen, betaler du 179 €. Blir den stående, betaler du ingenting." },
    ],
    honestyEyebrow: "Ærlig talt", honestyH: "Hva vi kan fjerne — og hva vi ikke kan.",
    yesH: "Gode sjanser", noH: "Det lover vi ikke",
    yes: ["Falske omtaler og angrep fra konkurrenter", "Omtaler fra folk som aldri var kunder", "Fornærmelser og usanne påstander", "Omtaler som bryter Googles regler"],
    no: ["Ærlig kritikk fra ekte kunder", "En garanti for enhver omtale — det kan ingen gi"],
    formEyebrow: "Gratis vurdering", formH: "Send oss omtalen.",
    formSub: "Du får et ærlig svar: ja vi kan, eller nei vi kan ikke. Gratis uansett.",
    how: { eyebrow: "Hvor finner jeg lenken?", h: "Å kopiere lenken tar ti sekunder.", steps: ["Finn omtalen på Google-profilen din og trykk på den for å åpne den.", "Trykk på deleikonet under omtalen.", "Kopier lenken og lim den inn i skjemaet — én per omtale, så mange du vil."], alt: "Ingen delemulighet? Oppgi da anmelderens navn og omtalens tekst — det identifiserer den like godt.", copyHint: "Klikk for å kopiere lenken", shareT: "Del omtale", copied: "Kopiert" },
    faqEyebrow: "Spørsmål", faqH: "Godt å vite.",
    faq: [
      { q: "Hvor lang tid tar det?", a: "Vanligvis noen dager, av og til opptil tre uker. Vi holder deg oppdatert." },
      { q: "Hva om omtalen ikke kan fjernes?", a: "Da betaler du ingenting. Vurderer vi sjansene som små, sier vi det med en gang." },
      { q: "Får anmelderen vite at det var meg?", a: "Nei. Anmelderen får ikke vite hvem som ba om fjerningen." },
      { q: "Jeg har flere omtaler.", a: "Prisen gjelder per omtale. Legg til så mange du vil i skjemaet med + — og du betaler bare for dem som faktisk fjernes." },
    ],
    finalH: "Én omtale bør ikke definere bedriften din.",
    finalCta: "Send oss omtalen",
    demoRemoved: "Fjernet",
    demoName: "Din bedrift",
  },
};
