/* RapidRemove — Texte der Landingpage „Einzelne Bewertung löschen".
   Liegt als reines Datenmodul hier (nicht in der "use client"-Komponente),
   weil auch Server-Code sie braucht: JSON-LD der Landingpage und der
   Service-Hinweis-Block in den Bewertungs-Ratgeberartikeln.
   en/es/fr/it/nl/pt: freigegebene Handoff-Texte; ja/sv/da/no im selben Ton.
   KEIN Deutsch — das Produkt gibt es nicht in DACH. */
import { RVW_SEO_A } from "@/lib/reviews-copy-seo-a";
import { RVW_SEO_B } from "@/lib/reviews-copy-seo-b";

export const RVW = {
  en: {
    eyebrow: "New service",
    h1: "Remove a Google review – pay only if it's gone.",
    lead: "Sometimes it's not the whole profile — it's one review that is unfair or simply false. We take care of exactly that one. You pay per removed review, nothing upfront.",
    price: "$179", per: "per removed review",
    priceNote: "You store a card or PayPal when ordering. Nothing is charged upfront – each review is charged only once it's actually gone. If it stays online, you pay nothing for it.",
    condNote: "Prices per removed review: reviews with text up to 4 weeks old $179 (approx. 90 % success chance), older reviews $229 (approx. 50 %). Complex cases cost $300: ratings without text, and reviews older than 4 weeks from the USA, because they require a more extensive procedure. In individual cases an older review that is still online after the standard procedure can become a complex case – we only continue with your consent. Volume discount: 3+ reviews −10 %, 5+ −15 %, 10+ −30 %. Every review is charged only after it has been removed.",
    cta: "Send us the review",
    assure: ["Nothing upfront", "Pay per removed review", "Honest assessment first"],
    stepsEyebrow: "How it works", stepsH: "Three steps, no paperwork.",
    steps: [
      { t: "Pick your reviews", d: "Search your business — we load your latest Google reviews. Tick the ones that should go, or paste their links." },
      { t: "We take a look", d: "Someone from our team reads it and tells you honestly whether we can remove it." },
      { t: "Gone — then you pay", d: "If the review comes down, it is charged to your stored card or PayPal – $179 for a recent review. If it stays, you pay nothing." },
    ],
    honestyEyebrow: "Honestly", honestyH: "What we can remove — and what we can't.",
    yesH: "Good chances", noH: "We won't promise",
    yes: ["Fake reviews and competitor attacks", "Reviews from people who were never customers", "Insults and false claims", "Reviews that break Google's rules", "Star-only ratings without text (complex case)"],
    no: ["Honest criticism from real customers", "A guarantee for every review — nobody can give that"],
    formEyebrow: "Free assessment", formH: "Send us the review.",
    formSub: "We'll reply with an honest answer: yes we can, or no we can't. Free either way.",
    how: { eyebrow: "Where do I find the link?", h: "Copying the review link takes ten seconds.", steps: ["Find the review on your Google profile and tap it to open it.", "Tap the share icon below the review.", "Copy the link and paste it into the form — one per review, as many as you like."], alt: "No share option there? Then simply enter the reviewer's name and the review text instead — that identifies the review just as well.", copyHint: "Click to copy the link", shareT: "Share review", copied: "Copied" },
    faqEyebrow: "Questions", faqH: "Good to know.",
    faq: [
      { q: "How long does it take?", a: "Usually 1–2 weeks – sometimes faster, occasionally a little longer. Star-only reviews via our special software: approx. 1–3 days. We keep you posted." },
      { q: "What if the review can't be removed?", a: "Then you pay nothing. We tell you at the start if we think the chances are poor." },
      { q: "Will the reviewer find out it was me?", a: "No. The reviewer is not told who requested the removal." },
      { q: "I have several reviews.", a: "The price is per review — select as many as you like. From 3 accepted reviews you get 10 % off, from 5 15 % and from 10 30 % – applied to every review we remove. You only pay for the ones actually removed." },
    ],
    finalH: "One review shouldn't define your business.",
    finalCta: "Send us the review",
    demoRemoved: "Removed",
    demoName: "Your business",
    // --- SEO-Ausbau (Okt 2026): Google-Richtlinien, Ablauf, Vergleich, Erpressung, mehr FAQ ---
    trust: ["1,600+ Google profiles removed since 2023", "Rated 5.0 on Trustpilot", "Only Google's official processes"],
    policyEyebrow: "Google's rules", policyH: "Which reviews Google actually removes",
    policyLead: "Google only removes reviews that break its content policies or the law. Before you pay anything, we check every review against these categories:",
    policy: [
      { t: "Fake engagement", d: "Reviews from people who were never customers, bought reviews, or ratings left by bots and review rings." },
      { t: "Conflict of interest", d: "Reviews written by competitors, former employees or anyone with a personal stake in hurting you." },
      { t: "Harassment & hate", d: "Insults, threats, personal attacks and discriminatory language against you or your staff." },
      { t: "Personal information", d: "Reviews that expose staff names, phone numbers, addresses or other private details." },
      { t: "Off-topic or wrong business", d: "Rants about politics or unrelated events – or a review clearly meant for another business." },
      { t: "Spam & repetition", d: "Copy-paste reviews, the same person posting again and again, links and advertising." },
      { t: "Review extortion", d: "A wave of 1-star reviews followed by a demand for money or free services." },
      { t: "Unlawful content", d: "False statements of fact and defamation – removable through Google's legal removal request." },
    ],
    processEyebrow: "Behind the scenes", processH: "How a removal actually works",
    process: [
      { t: "Assessment", d: "We read the review and match it to a specific Google policy or legal ground. If there is none, we tell you – and you pay nothing.", time: "Same day" },
      { t: "Report through Google", d: "We file the report under the matching violation, together with the evidence that supports it.", time: "Days 1–3" },
      { t: "Appeal if needed", d: "If Google's first check misses it, we escalate through the appeal in Google's Reviews Management Tool.", time: "Days 3–14" },
      { t: "Legal removal request", d: "For defamatory or unlawful reviews we use Google's legal removal form with a precise legal basis.", time: "1–3 weeks" },
    ],
    processNote: "No fake accounts, no bots, no fake legal notices – only the procedures Google itself provides, on behalf of the business owner.",
    compareEyebrow: "Compared", compareH: "Your options to get a Google review removed",
    compareHead: ["", "Report it yourself", "Lawyer", "RapidRemove"],
    compareRows: [
      ["Cost", "Free", "Hourly fees, often paid upfront", "From $179 per removed review"],
      ["Pay only on success", "–", "No", "Yes"],
      ["Typical duration", "Days to weeks – often rejected", "Weeks to months", "Usually 1–2 weeks"],
      ["Your effort", "High: policies, evidence, appeals", "Briefings and documents", "Paste the link – that's it"],
      ["Routes used", "One report", "Legal route only", "Report, appeal and legal request"],
    ],
    extortionEyebrow: "Review extortion", extortionH: "1-star reviews and a demand for money?",
    extortionP: [
      "It's a known scam: a sudden wave of 1- and 2-star reviews, then a message offering to make them disappear for a fee. Never pay – it rarely ends there.",
      "Keep screenshots of every message and send us the reviews. Extortion reviews are among the ones Google removes most reliably – and you still only pay for the reviews that are actually gone.",
    ],
    guidesEyebrow: "Guides", guidesH: "Everything about removing Google reviews",
    faqMore: [
      { q: "Is it legal to have Google reviews removed?", a: "Yes. We only use the procedures Google offers every business: policy reports, the appeal in the Reviews Management Tool and Google's legal removal request. We act on behalf of the business owner and never use fake accounts or fake legal notices." },
      { q: "Which reviews can't be removed?", a: "Honest, factual criticism from real customers – even when it's harsh. Google protects genuine experiences, and so do we. If a review doesn't break any rule, we tell you right away instead of taking your money." },
      { q: "Can a removed review come back?", a: "Rarely. If the same person posts it again, send it to us – a repost of a removed review is usually removed again quickly." },
      { q: "Will reporting reviews hurt my Google profile?", a: "No. Reporting reviews that break Google's policies is a normal, intended process and has no negative effect on your profile or ranking." },
      { q: "Can you remove 1-star ratings without text?", a: "Yes. Ratings without text are a complex case: they require a more extensive procedure and cost $300 per removed rating; the volume discount applies. As with all reviews, you store a card or PayPal when ordering – nothing is charged upfront, and the rating is charged only after it has been removed. If it stays online, you pay nothing for it." },
      { q: "How do I pay?", a: "When you order, you store a card or PayPal. Nothing is charged upfront: each review is charged automatically only after it has been removed, and you receive a confirmation. If a review stays online, you pay nothing for it." },
    ],
  },
  es: {
    eyebrow: "Nuevo servicio",
    h1: "Elimina una reseña concreta de Google.",
    lead: "A veces no es todo el perfil: es una reseña injusta o simplemente falsa. Nos ocupamos exactamente de esa. Pagas por reseña eliminada, nada por adelantado.",
    price: "179 €", per: "por reseña eliminada",
    priceNote: "Al hacer el pedido guardas una tarjeta o PayPal. No se cobra nada por adelantado: cada reseña se cobra solo cuando ha desaparecido de verdad. Si sigue publicada, no pagas nada por ella.",
    condNote: "Precios por reseña eliminada: reseñas con texto de hasta 4 semanas 179 € (aprox. 90 % de éxito), reseñas más antiguas 229 € (aprox. 50 %). Los casos complejos cuestan 300 €: valoraciones sin texto y, en EE. UU., reseñas de más de 4 semanas (300 $), porque requieren un procedimiento más amplio. En casos puntuales, una reseña antigua que sigue publicada tras el procedimiento estándar puede convertirse en un caso complejo; solo continuamos con tu consentimiento. Descuento por volumen: desde 3 reseñas −10 %, desde 5 −15 %, desde 10 −30 %. Cada reseña se cobra solo después de su eliminación.",
    cta: "Envíanos la reseña",
    assure: ["Nada por adelantado", "Pago por reseña eliminada", "Primero una valoración honesta"],
    stepsEyebrow: "Cómo funciona", stepsH: "Tres pasos, sin papeleo.",
    steps: [
      { t: "Elige tus reseñas", d: "Busca tu empresa: cargamos tus reseñas de Google más recientes. Marca las que deben desaparecer o pega sus enlaces." },
      { t: "La revisamos", d: "Alguien de nuestro equipo la lee y te dice con franqueza si podemos eliminarla." },
      { t: "Desaparece — y entonces pagas", d: "Si la reseña se retira, se cobra a la tarjeta o PayPal que guardaste: 179 € por una reseña reciente. Si se queda, no pagas nada." },
    ],
    honestyEyebrow: "Con franqueza", honestyH: "Qué podemos eliminar — y qué no.",
    yesH: "Buenas posibilidades", noH: "No prometemos",
    yes: ["Reseñas falsas y ataques de competidores", "Reseñas de personas que nunca fueron clientes", "Insultos y afirmaciones falsas", "Reseñas que incumplen las normas de Google", "Valoraciones sin texto, solo estrellas (caso complejo)"],
    no: ["Críticas honestas de clientes reales", "Una garantía para cualquier reseña — nadie puede darla"],
    formEyebrow: "Valoración gratuita", formH: "Envíanos la reseña.",
    formSub: "Te responderemos con una respuesta honesta: sí podemos, o no podemos. Gratis en ambos casos.",
    how: { eyebrow: "¿Dónde está el enlace?", h: "Copiar el enlace de la reseña lleva diez segundos.", steps: ["Busca la reseña en tu perfil de Google y tócala para abrirla.", "Toca el icono de compartir debajo de la reseña.", "Copia el enlace y pégalo en el formulario — uno por reseña, tantas como quieras."], alt: "¿No aparece la opción de compartir? Entonces indica el nombre del autor y el texto de la reseña — la identifica igual de bien.", copyHint: "Haz clic para copiar el enlace", shareT: "Compartir reseña", copied: "Copiado" },
    faqEyebrow: "Preguntas", faqH: "Bueno saberlo.",
    faq: [
      { q: "¿Cuánto tarda?", a: "Normalmente 1–2 semanas; a veces más rápido y en casos puntuales algo más. Reseñas solo con estrellas mediante nuestro software especial: aprox. 1–3 días. Te mantenemos informado." },
      { q: "¿Y si no se puede eliminar?", a: "Entonces no pagas nada. Si vemos pocas posibilidades, te lo decimos desde el principio." },
      { q: "¿Sabrá el autor que fui yo?", a: "No. Al autor no se le comunica quién solicitó la eliminación." },
      { q: "Tengo varias reseñas.", a: "El precio es por reseña: selecciona tantas como quieras. Desde 3 reseñas −10 %, desde 5 −15 % y desde 10 −30 %. Solo pagas las que realmente se eliminan." },
    ],
    finalH: "Una reseña no debería definir tu negocio.",
    finalCta: "Envíanos la reseña",
    demoRemoved: "Eliminada",
    demoName: "Tu negocio",
  },
  fr: {
    eyebrow: "Nouveau service",
    h1: "Supprimez un avis Google précis.",
    lead: "Parfois ce n'est pas toute la fiche — c'est un avis injuste ou tout simplement faux. Nous nous occupons exactement de celui-là. Vous payez par avis supprimé, rien d'avance.",
    price: "179 €", per: "par avis supprimé",
    priceNote: "Lors de la commande, vous enregistrez une carte ou PayPal. Rien n'est débité d'avance : chaque avis n'est facturé qu'une fois réellement supprimé. S'il reste en ligne, vous ne payez rien pour lui.",
    condNote: "Prix par avis supprimé : avis avec texte de 4 semaines maximum 179 € (env. 90 % de réussite), avis plus anciens 229 € (env. 50 %). Les cas complexes coûtent 300 € : notes sans texte et, aux États-Unis, avis de plus de 4 semaines (300 $), car ils nécessitent une procédure plus approfondie. Dans certains cas, un avis plus ancien encore en ligne après la procédure standard peut devenir un cas complexe – nous ne poursuivons qu'avec votre accord. Remise sur quantité : dès 3 avis −10 %, dès 5 −15 %, dès 10 −30 %. Chaque avis n'est facturé qu'après sa suppression.",
    cta: "Envoyez-nous l'avis",
    assure: ["Rien d'avance", "Paiement par avis supprimé", "D'abord un avis honnête"],
    stepsEyebrow: "Comment ça marche", stepsH: "Trois étapes, zéro paperasse.",
    steps: [
      { t: "Choisissez vos avis", d: "Recherchez votre entreprise : nous chargeons vos derniers avis Google. Cochez ceux à supprimer, ou collez leurs liens." },
      { t: "Nous le lisons", d: "Quelqu'un de notre équipe le lit et vous dit franchement si nous pouvons le supprimer." },
      { t: "Disparu — vous payez alors", d: "Si l'avis est retiré, le montant est débité de la carte ou du compte PayPal enregistré : 179 € pour un avis récent. S'il reste, vous ne payez rien." },
    ],
    honestyEyebrow: "Franchement", honestyH: "Ce que nous pouvons supprimer — et ce que non.",
    yesH: "Bonnes chances", noH: "Nous ne promettons pas",
    yes: ["Faux avis et attaques de concurrents", "Avis de personnes qui n'ont jamais été clientes", "Insultes et affirmations fausses", "Avis contraires aux règles de Google", "Notes sans texte, étoiles seules (cas complexe)"],
    no: ["Critiques honnêtes de vrais clients", "Une garantie pour chaque avis — personne ne peut la donner"],
    formEyebrow: "Évaluation gratuite", formH: "Envoyez-nous l'avis.",
    formSub: "Nous vous répondrons honnêtement : oui c'est possible, ou non. Gratuit dans les deux cas.",
    how: { eyebrow: "Où trouver le lien ?", h: "Copier le lien de l'avis prend dix secondes.", steps: ["Trouvez l'avis sur votre fiche Google et touchez-le pour l'ouvrir.", "Touchez l'icône de partage sous l'avis.", "Copiez le lien et collez-le dans le formulaire — un par avis, autant que vous voulez."], alt: "Pas d'option de partage ? Indiquez alors le nom de l'auteur et le texte de l'avis — cela l'identifie tout aussi bien.", copyHint: "Cliquez pour copier le lien", shareT: "Partager l'avis", copied: "Copié" },
    faqEyebrow: "Questions", faqH: "Bon à savoir.",
    faq: [
      { q: "Combien de temps cela prend-il ?", a: "En général 1 à 2 semaines, parfois moins, dans certains cas un peu plus. Avis sans texte via notre logiciel spécial : env. 1 à 3 jours. Nous vous tenons informé." },
      { q: "Et si l'avis ne peut pas être supprimé ?", a: "Alors vous ne payez rien. Si les chances nous semblent faibles, nous vous le disons d'emblée." },
      { q: "L'auteur saura-t-il que c'est moi ?", a: "Non. L'auteur n'est pas informé de qui a demandé la suppression." },
      { q: "J'ai plusieurs avis.", a: "Le prix est par avis — sélectionnez-en autant que vous voulez. Dès 3 avis −10 %, dès 5 −15 % et dès 10 −30 %. Vous ne payez que ceux réellement supprimés." },
    ],
    finalH: "Un avis ne devrait pas définir votre entreprise.",
    finalCta: "Envoyez-nous l'avis",
    demoRemoved: "Supprimé",
    demoName: "Votre entreprise",
  },
  it: {
    eyebrow: "Nuovo servizio",
    h1: "Elimina una singola recensione Google.",
    lead: "A volte non è tutto il profilo — è una recensione ingiusta o semplicemente falsa. Ci occupiamo esattamente di quella. Paghi per recensione eliminata, niente in anticipo.",
    price: "179 €", per: "per recensione eliminata",
    priceNote: "Al momento dell'ordine registri una carta o PayPal. Nulla viene addebitato in anticipo: ogni recensione viene addebitata solo quando è davvero sparita. Se resta online, non paghi nulla.",
    condNote: "Prezzi per recensione rimossa: recensioni con testo fino a 4 settimane 179 € (ca. 90 % di successo), recensioni più vecchie 229 € (ca. 50 %). I casi complessi costano 300 €: valutazioni senza testo e, negli USA, recensioni più vecchie di 4 settimane (300 $), perché richiedono una procedura più approfondita. In singoli casi una recensione più vecchia ancora online dopo la procedura standard può diventare un caso complesso – proseguiamo solo con il tuo consenso. Sconto quantità: da 3 recensioni −10 %, da 5 −15 %, da 10 −30 %. Ogni recensione viene addebitata solo dopo la rimozione.",
    cta: "Inviaci la recensione",
    assure: ["Niente in anticipo", "Paghi per recensione eliminata", "Prima una valutazione onesta"],
    stepsEyebrow: "Come funziona", stepsH: "Tre passi, zero burocrazia.",
    steps: [
      { t: "Scegli le recensioni", d: "Cerca la tua attività: carichiamo le tue ultime recensioni Google. Spunta quelle da eliminare o incolla i loro link." },
      { t: "La leggiamo", d: "Qualcuno del nostro team la legge e ti dice onestamente se possiamo eliminarla." },
      { t: "Sparita — poi paghi", d: "Se la recensione viene rimossa, l'importo viene addebitato sulla carta o su PayPal registrati: 179 € per una recensione recente. Se resta, non paghi nulla." },
    ],
    honestyEyebrow: "Onestamente", honestyH: "Cosa possiamo eliminare — e cosa no.",
    yesH: "Buone probabilità", noH: "Non promettiamo",
    yes: ["Recensioni false e attacchi di concorrenti", "Recensioni di persone mai state clienti", "Insulti e affermazioni false", "Recensioni contro le regole di Google", "Valutazioni senza testo, solo stelle (caso complesso)"],
    no: ["Critiche oneste di clienti veri", "Una garanzia per ogni recensione — nessuno può darla"],
    formEyebrow: "Valutazione gratuita", formH: "Inviaci la recensione.",
    formSub: "Ti risponderemo con onestà: sì possiamo, oppure no. Gratis in entrambi i casi.",
    how: { eyebrow: "Dove trovo il link?", h: "Copiare il link della recensione richiede dieci secondi.", steps: ["Trova la recensione sul tuo profilo Google e toccala per aprirla.", "Tocca l'icona di condivisione sotto la recensione.", "Copia il link e incollalo nel modulo — uno per recensione, quante vuoi."], alt: "Non c'è l'opzione di condivisione? Inserisci allora il nome dell'autore e il testo della recensione — la identifica altrettanto bene.", copyHint: "Clicca per copiare il link", shareT: "Condividi recensione", copied: "Copiato" },
    faqEyebrow: "Domande", faqH: "Da sapere.",
    faq: [
      { q: "Quanto ci vuole?", a: "Di solito 1–2 settimane, a volte meno, in singoli casi un po' di più. Recensioni solo stelle con il nostro software speciale: ca. 1–3 giorni. Ti teniamo aggiornato." },
      { q: "E se non si può eliminare?", a: "Allora non paghi nulla. Se le probabilità ci sembrano basse, te lo diciamo subito." },
      { q: "L'autore saprà che sono stato io?", a: "No. All'autore non viene comunicato chi ha chiesto la rimozione." },
      { q: "Ho più recensioni.", a: "Il prezzo è per recensione: selezionane quante vuoi. Da 3 recensioni −10 %, da 5 −15 % e da 10 −30 %. Paghi solo quelle davvero rimosse." },
    ],
    finalH: "Una recensione non dovrebbe definire la tua attività.",
    finalCta: "Inviaci la recensione",
    demoRemoved: "Rimossa",
    demoName: "La tua attività",
  },
  nl: {
    eyebrow: "Nieuwe dienst",
    h1: "Laat één losse Google-review verwijderen.",
    lead: "Soms is het niet het hele profiel — maar die ene review die oneerlijk of gewoon onwaar is. Precies die pakken wij aan. U betaalt per verwijderde review, niets vooraf.",
    price: "€ 179", per: "per verwijderde review",
    priceNote: "Bij het bestellen legt u een kaart of PayPal vast. Er wordt niets vooraf afgeschreven: elke review wordt pas afgerekend als hij echt weg is. Blijft hij online, dan betaalt u er niets voor.",
    condNote: "Prijzen per verwijderde review: reviews met tekst tot 4 weken oud € 179 (ca. 90 % slagingskans), oudere reviews € 229 (ca. 50 %). Complexe gevallen kosten € 300: beoordelingen zonder tekst en, in de VS, reviews ouder dan 4 weken ($ 300), omdat ze een uitgebreidere procedure vereisen. In afzonderlijke gevallen kan een oudere review die na de standaardprocedure nog online staat een complex geval worden – we gaan alleen verder met uw toestemming. Staffelkorting: vanaf 3 reviews −10 %, vanaf 5 −15 %, vanaf 10 −30 %. Elke review wordt pas na verwijdering afgerekend.",
    cta: "Stuur ons de review",
    assure: ["Niets vooraf", "Betalen per verwijderde review", "Eerst een eerlijke inschatting"],
    stepsEyebrow: "Zo werkt het", stepsH: "Drie stappen, geen papierwerk.",
    steps: [
      { t: "Kies uw reviews", d: "Zoek uw bedrijf — wij laden uw nieuwste Google-reviews. Vink aan welke weg moeten, of plak hun links." },
      { t: "Wij kijken ernaar", d: "Iemand van ons team leest de review en zegt eerlijk of we hem kunnen verwijderen." },
      { t: "Weg — dan pas betalen", d: "Gaat de review eraf, dan wordt het bedrag van uw vastgelegde kaart of PayPal afgeschreven: € 179 voor een recente review. Blijft hij staan, dan betaalt u niets." },
    ],
    honestyEyebrow: "Eerlijk gezegd", honestyH: "Wat we kunnen verwijderen — en wat niet.",
    yesH: "Goede kansen", noH: "Dat beloven we niet",
    yes: ["Nepreviews en aanvallen van concurrenten", "Reviews van mensen die nooit klant waren", "Beledigingen en onware beweringen", "Reviews die de regels van Google schenden", "Beoordelingen zonder tekst, alleen sterren (complex geval)"],
    no: ["Eerlijke kritiek van echte klanten", "Een garantie voor elke review — die kan niemand geven"],
    formEyebrow: "Gratis inschatting", formH: "Stuur ons de review.",
    formSub: "U krijgt een eerlijk antwoord: ja het kan, of nee het kan niet. In beide gevallen gratis.",
    how: { eyebrow: "Waar vind ik de link?", h: "De link kopiëren duurt tien seconden.", steps: ["Zoek de review op uw Google-profiel en tik erop om hem te openen.", "Tik op het deelicoon onder de review.", "Kopieer de link en plak hem in het formulier — één per review, zoveel u wilt."], alt: "Geen deeloptie? Vul dan de naam van de schrijver en de tekst van de review in — dat identificeert hem net zo goed.", copyHint: "Klik om de link te kopiëren", shareT: "Review delen", copied: "Gekopieerd" },
    faqEyebrow: "Vragen", faqH: "Goed om te weten.",
    faq: [
      { q: "Hoe lang duurt het?", a: "Meestal 1–2 weken, soms sneller, in enkele gevallen iets langer. Reviews met alleen sterren via onze speciale software: ca. 1–3 dagen. We houden u op de hoogte." },
      { q: "En als de review niet weg kan?", a: "Dan betaalt u niets. Schatten we de kans laag in, dan zeggen we dat vooraf." },
      { q: "Weet de schrijver dat ik het was?", a: "Nee. De schrijver krijgt niet te horen wie om verwijdering heeft gevraagd." },
      { q: "Ik heb meerdere reviews.", a: "De prijs geldt per review — selecteer er zoveel als u wilt. Vanaf 3 reviews −10 %, vanaf 5 −15 % en vanaf 10 −30 %. U betaalt alleen voor wat echt verwijderd is." },
    ],
    finalH: "Eén review zou uw zaak niet mogen bepalen.",
    finalCta: "Stuur ons de review",
    demoRemoved: "Verwijderd",
    demoName: "Uw bedrijf",
  },
  pt: {
    eyebrow: "Novo serviço",
    h1: "Remova uma avaliação específica do Google.",
    lead: "Às vezes não é o perfil inteiro — é uma avaliação injusta ou simplesmente falsa. Cuidamos exatamente dessa. Paga por avaliação removida, nada adiantado.",
    price: "179 €", per: "por avaliação removida",
    priceNote: "Ao encomendar, regista um cartão ou PayPal. Nada é cobrado antecipadamente: cada avaliação só é cobrada quando desaparecer de facto. Se continuar online, não paga nada por ela.",
    condNote: "Preços por avaliação removida: avaliações com texto até 4 semanas 179 € (aprox. 90 % de sucesso), avaliações mais antigas 229 € (aprox. 50 %). Os casos complexos custam 300 €: classificações sem texto e, nos EUA, avaliações com mais de 4 semanas (300 $), porque exigem um procedimento mais extenso. Em casos pontuais, uma avaliação mais antiga que continue online após o procedimento padrão pode tornar-se um caso complexo – só continuamos com o seu consentimento. Desconto por quantidade: a partir de 3 avaliações −10 %, de 5 −15 %, de 10 −30 %. Cada avaliação só é cobrada depois de removida.",
    cta: "Envie-nos a avaliação",
    assure: ["Nada adiantado", "Pagamento por avaliação removida", "Primeiro uma opinião honesta"],
    stepsEyebrow: "Como funciona", stepsH: "Três passos, sem burocracia.",
    steps: [
      { t: "Escolha as avaliações", d: "Pesquise a sua empresa — carregamos as suas avaliações Google mais recentes. Marque as que devem sair ou cole os links." },
      { t: "Nós analisamos", d: "Alguém da nossa equipa lê a avaliação e diz com honestidade se podemos removê-la." },
      { t: "Removida — só então paga", d: "Se a avaliação sair, o valor é cobrado no cartão ou PayPal registado: 179 € por uma avaliação recente. Se ficar, não paga nada." },
    ],
    honestyEyebrow: "Com honestidade", honestyH: "O que podemos remover — e o que não.",
    yesH: "Boas hipóteses", noH: "Não prometemos",
    yes: ["Avaliações falsas e ataques de concorrentes", "Avaliações de quem nunca foi cliente", "Insultos e afirmações falsas", "Avaliações que violam as regras do Google", "Classificações sem texto, só estrelas (caso complexo)"],
    no: ["Críticas honestas de clientes reais", "Uma garantia para qualquer avaliação — ninguém pode dar isso"],
    formEyebrow: "Análise gratuita", formH: "Envie-nos a avaliação.",
    formSub: "Respondemos com honestidade: sim conseguimos, ou não conseguimos. Grátis nos dois casos.",
    how: { eyebrow: "Onde encontro o link?", h: "Copiar o link da avaliação leva dez segundos.", steps: ["Encontre a avaliação no seu perfil do Google e toque nela para a abrir.", "Toque no ícone de partilha por baixo da avaliação.", "Copie o link e cole-o no formulário — um por avaliação, quantas quiser."], alt: "Não há opção de partilha? Então indique o nome do autor e o texto da avaliação — identifica-a igualmente bem.", copyHint: "Clique para copiar o link", shareT: "Partilhar avaliação", copied: "Copiado" },
    faqEyebrow: "Perguntas", faqH: "Bom saber.",
    faq: [
      { q: "Quanto tempo demora?", a: "Normalmente 1–2 semanas, por vezes menos, em casos pontuais um pouco mais. Avaliações só com estrelas através do nosso software especial: cerca de 1–3 dias. Vamos mantendo-o informado." },
      { q: "E se não for possível remover?", a: "Então não paga nada. Se as hipóteses nos parecerem baixas, dizemos logo no início." },
      { q: "O autor saberá que fui eu?", a: "Não. O autor não é informado de quem pediu a remoção." },
      { q: "Tenho várias avaliações.", a: "O preço é por avaliação — selecione quantas quiser. A partir de 3 avaliações −10 %, de 5 −15 % e de 10 −30 %. Só paga as que forem mesmo removidas." },
    ],
    finalH: "Uma avaliação não devia definir o seu negócio.",
    finalCta: "Envie-nos a avaliação",
    demoRemoved: "Removida",
    demoName: "O seu negócio",
  },
  ja: {
    eyebrow: "新サービス",
    h1: "Googleの口コミを1件から削除。",
    lead: "プロフィール全体ではなく、不当な、あるいは事実と異なる口コミが1件だけ——そんなときは、その1件だけを私たちが対応します。お支払いは削除できた口コミの分だけ。前払いはありません。",
    price: "$179", per: "削除1件あたり",
    priceNote: "ご注文時にカードまたはPayPalをご登録いただきます。事前の請求はなく、口コミが実際に削除されてから1件ごとに請求されます。削除されなかった口コミには料金はかかりません。",
    condNote: "削除1件あたりの料金：投稿から4週間以内の本文ありの口コミ $179（成功率 約90%）、それより古い口コミ $229（約50%）。複雑なケースは $300：本文のない星だけの評価と、米国の投稿から4週間を超える口コミが該当し、より手間のかかる手続きが必要になります。個別のケースでは、標準手続きの後も残っている古い口コミが複雑なケースに移行することがありますが、続行するのはお客様の同意をいただいた場合のみです。まとめ割：3件以上 −10%、5件以上 −15%、10件以上 −30%。いずれも削除後にのみ請求されます。",
    cta: "口コミを送る",
    assure: ["前払いなし", "削除1件ごとのお支払い", "まず正直な見立てから"],
    stepsEyebrow: "ご利用の流れ", stepsH: "3ステップ、面倒な手続きなし。",
    steps: [
      { t: "口コミを選ぶ", d: "店舗名で検索すると最新のGoogle口コミを読み込みます。削除したい口コミにチェックを入れるか、リンクを貼り付けてください。" },
      { t: "内容を確認", d: "チームの担当者が口コミを読み、削除できるかどうかを正直にお伝えします。" },
      { t: "消えたら、お支払い", d: "口コミが削除されたら、ご登録のカードまたはPayPalに請求されます（新しい口コミは$179）。残った場合は何も支払いません。" },
    ],
    honestyEyebrow: "正直に", honestyH: "削除できるもの——できないもの。",
    yesH: "見込みが高いもの", noH: "お約束できないこと",
    yes: ["やらせの口コミ・競合による攻撃", "利用実績のない人による口コミ", "侮辱や事実と異なる主張", "Googleのルールに違反する口コミ", "本文のない星だけの評価（複雑なケース）"],
    no: ["実際のお客様による率直な批判", "どんな口コミでも消せるという保証——それは誰にもできません"],
    formEyebrow: "無料診断", formH: "口コミをお送りください。",
    formSub: "「できます」か「できません」か、正直にお答えします。どちらでも無料です。",
    how: { eyebrow: "リンクはどこに？", h: "口コミのリンクコピーは10秒で終わります。", steps: ["Googleプロフィールで口コミを見つけて、タップして開きます。", "口コミの下にある共有アイコンをタップします。", "リンクをコピーしてフォームに貼り付けます。1件につき1リンク、何件でも。"], alt: "共有ボタンが見つからない場合は、投稿者名と口コミ本文を入力してください。それでも同じように特定できます。", copyHint: "クリックしてリンクをコピー", shareT: "クチコミを共有", copied: "コピーしました" },
    faqEyebrow: "よくある質問", faqH: "知っておきたいこと。",
    faq: [
      { q: "どのくらいかかりますか？", a: "通常は1〜2週間です（早まることも、まれに少し長くなることもあります）。星のみの口コミは専用ソフトウェアで約1〜3日です。進捗は随時ご連絡します。" },
      { q: "削除できなかったら？", a: "その場合、お支払いはありません。見込みが低いと判断したときは、最初にそうお伝えします。" },
      { q: "投稿者に依頼者が知られますか？", a: "いいえ。誰が削除を依頼したかが投稿者に伝わることはありません。" },
      { q: "口コミが複数あります。", a: "料金は1件ごとです。何件でも選択でき、3件以上で−10%、5件以上で−15%、10件以上で−30%。実際に削除できた分だけのお支払いです。" },
    ],
    finalH: "たった1件の口コミに、お店の評価を決めさせない。",
    finalCta: "口コミを送る",
    demoRemoved: "削除済み",
    demoName: "あなたのお店",
  },
  sv: {
    eyebrow: "Ny tjänst",
    h1: "Ta bort ett enskilt Google-omdöme.",
    lead: "Ibland är det inte hela profilen — det är ett enda omdöme som är orättvist eller helt enkelt falskt. Vi tar hand om exakt det. Du betalar per borttaget omdöme, inget i förskott.",
    price: "179 €", per: "per borttaget omdöme",
    priceNote: "När du beställer registrerar du ett kort eller PayPal. Inget dras i förväg – varje omdöme debiteras först när det faktiskt är borta. Ligger det kvar betalar du ingenting för det.",
    condNote: "Priser per borttaget omdöme: omdömen med text upp till 4 veckor gamla 179 € (ca. 90 % chans att lyckas), äldre omdömen 229 € (ca. 50 %). Komplexa fall kostar 300 €: betyg utan text samt omdömen från USA som är äldre än 4 veckor (300 $), eftersom de kräver ett mer omfattande förfarande. I enskilda fall kan ett äldre omdöme som ligger kvar efter standardförfarandet bli ett komplext fall – vi fortsätter bara med ditt samtycke. Mängdrabatt: från 3 omdömen −10 %, från 5 −15 %, från 10 −30 %. Varje omdöme debiteras först efter att det tagits bort.",
    cta: "Skicka omdömet till oss",
    assure: ["Inget i förskott", "Betala per borttaget omdöme", "Först en ärlig bedömning"],
    stepsEyebrow: "Så fungerar det", stepsH: "Tre steg, inget pappersarbete.",
    steps: [
      { t: "Välj dina omdömen", d: "Sök upp ditt företag — vi laddar dina senaste Google-omdömen. Bocka i dem som ska bort, eller klistra in länkarna." },
      { t: "Vi tittar på det", d: "Någon i vårt team läser omdömet och säger ärligt om vi kan ta bort det." },
      { t: "Borta — då betalar du", d: "Tas omdömet bort debiteras ditt registrerade kort eller PayPal: 179 € för ett nytt omdöme. Står det kvar betalar du ingenting." },
    ],
    honestyEyebrow: "Ärligt talat", honestyH: "Vad vi kan ta bort — och vad vi inte kan.",
    yesH: "Goda chanser", noH: "Det lovar vi inte",
    yes: ["Falska omdömen och angrepp från konkurrenter", "Omdömen från personer som aldrig varit kunder", "Förolämpningar och osanna påståenden", "Omdömen som bryter mot Googles regler", "Betyg utan text, bara stjärnor (komplext fall)"],
    no: ["Ärlig kritik från riktiga kunder", "En garanti för varje omdöme — det kan ingen ge"],
    formEyebrow: "Gratis bedömning", formH: "Skicka omdömet till oss.",
    formSub: "Du får ett ärligt svar: ja det går, eller nej det går inte. Gratis i båda fallen.",
    how: { eyebrow: "Var hittar jag länken?", h: "Att kopiera länken tar tio sekunder.", steps: ["Hitta omdömet på din Google-profil och tryck på det för att öppna det.", "Tryck på delningsikonen under omdömet.", "Kopiera länken och klistra in den i formuläret — en per omdöme, så många du vill."], alt: "Ingen delningsknapp? Ange då recensentens namn och omdömets text — det identifierar omdömet lika bra.", copyHint: "Klicka för att kopiera länken", shareT: "Dela omdöme", copied: "Kopierad" },
    faqEyebrow: "Frågor", faqH: "Bra att veta.",
    faq: [
      { q: "Hur lång tid tar det?", a: "Oftast 1–2 veckor, ibland snabbare, i enstaka fall något längre. Betyg utan text via vår specialprogramvara: ca 1–3 dagar. Vi håller dig uppdaterad." },
      { q: "Och om omdömet inte kan tas bort?", a: "Då betalar du ingenting. Bedömer vi chanserna som små säger vi det från början." },
      { q: "Får recensenten veta att det var jag?", a: "Nej. Recensenten får inte veta vem som begärde borttagningen." },
      { q: "Jag har flera omdömen.", a: "Priset gäller per omdöme — välj så många du vill. Från 3 omdömen −10 %, från 5 −15 % och från 10 −30 %. Du betalar bara för dem som faktiskt tas bort." },
    ],
    finalH: "Ett omdöme ska inte definiera ditt företag.",
    finalCta: "Skicka omdömet till oss",
    demoRemoved: "Borttaget",
    demoName: "Ditt företag",
  },
  da: {
    eyebrow: "Ny ydelse",
    h1: "Fjern en enkelt Google-anmeldelse.",
    lead: "Nogle gange er det ikke hele profilen — det er én anmeldelse, der er urimelig eller simpelthen falsk. Vi tager os af præcis den. Du betaler pr. fjernet anmeldelse, intet på forhånd.",
    price: "179 €", per: "pr. fjernet anmeldelse",
    priceNote: "Når du bestiller, gemmer du et kort eller PayPal. Intet trækkes på forhånd – hver anmeldelse opkræves først, når den faktisk er væk. Bliver den stående, betaler du ingenting for den.",
    condNote: "Priser pr. fjernet anmeldelse: anmeldelser med tekst op til 4 uger gamle 179 € (ca. 90 % succesrate), ældre anmeldelser 229 € (ca. 50 %). Komplekse tilfælde koster 300 €: bedømmelser uden tekst samt anmeldelser fra USA, der er ældre end 4 uger (300 $), fordi de kræver en mere omfattende procedure. I enkelte tilfælde kan en ældre anmeldelse, der stadig er online efter standardproceduren, blive et komplekst tilfælde – vi fortsætter kun med dit samtykke. Mængderabat: fra 3 anmeldelser −10 %, fra 5 −15 %, fra 10 −30 %. Hver anmeldelse opkræves først, når den er fjernet.",
    cta: "Send os anmeldelsen",
    assure: ["Intet på forhånd", "Betal pr. fjernet anmeldelse", "Først en ærlig vurdering"],
    stepsEyebrow: "Sådan fungerer det", stepsH: "Tre trin, intet papirarbejde.",
    steps: [
      { t: "Vælg dine anmeldelser", d: "Søg din virksomhed frem — vi henter dine nyeste Google-anmeldelser. Sæt flueben ved dem, der skal væk, eller indsæt linkene." },
      { t: "Vi kigger på den", d: "En fra vores team læser anmeldelsen og siger ærligt, om vi kan fjerne den." },
      { t: "Væk — så betaler du", d: "Fjernes anmeldelsen, opkræves beløbet på dit gemte kort eller PayPal: 179 € for en ny anmeldelse. Bliver den stående, betaler du ingenting." },
    ],
    honestyEyebrow: "Ærligt talt", honestyH: "Hvad vi kan fjerne — og hvad vi ikke kan.",
    yesH: "Gode chancer", noH: "Det lover vi ikke",
    yes: ["Falske anmeldelser og angreb fra konkurrenter", "Anmeldelser fra folk, der aldrig var kunder", "Fornærmelser og usande påstande", "Anmeldelser, der bryder Googles regler", "Bedømmelser uden tekst, kun stjerner (komplekst tilfælde)"],
    no: ["Ærlig kritik fra rigtige kunder", "En garanti for enhver anmeldelse — det kan ingen give"],
    formEyebrow: "Gratis vurdering", formH: "Send os anmeldelsen.",
    formSub: "Du får et ærligt svar: ja vi kan, eller nej vi kan ikke. Gratis i begge tilfælde.",
    how: { eyebrow: "Hvor finder jeg linket?", h: "At kopiere linket tager ti sekunder.", steps: ["Find anmeldelsen på din Google-profil, og tryk på den for at åbne den.", "Tryk på deleikonet under anmeldelsen.", "Kopiér linket og indsæt det i formularen — ét pr. anmeldelse, så mange du vil."], alt: "Ingen delemulighed? Angiv i stedet anmelderens navn og anmeldelsens tekst — det identificerer den lige så godt.", copyHint: "Klik for at kopiere linket", shareT: "Del anmeldelse", copied: "Kopieret" },
    faqEyebrow: "Spørgsmål", faqH: "Godt at vide.",
    faq: [
      { q: "Hvor lang tid tager det?", a: "Som regel 1–2 uger, nogle gange hurtigere, i enkelte tilfælde lidt længere. Anmeldelser uden tekst via vores specialsoftware: ca. 1–3 dage. Vi holder dig opdateret." },
      { q: "Hvad hvis anmeldelsen ikke kan fjernes?", a: "Så betaler du ingenting. Vurderer vi chancerne som små, siger vi det fra starten." },
      { q: "Finder anmelderen ud af, det var mig?", a: "Nej. Anmelderen får ikke at vide, hvem der bad om fjernelsen." },
      { q: "Jeg har flere anmeldelser.", a: "Prisen gælder pr. anmeldelse — vælg så mange du vil. Fra 3 anmeldelser −10 %, fra 5 −15 % og fra 10 −30 %. Du betaler kun for dem, der faktisk fjernes." },
    ],
    finalH: "Én anmeldelse bør ikke definere din virksomhed.",
    finalCta: "Send os anmeldelsen",
    demoRemoved: "Fjernet",
    demoName: "Din virksomhed",
  },
  no: {
    eyebrow: "Ny tjeneste",
    h1: "Fjern én enkelt Google-omtale.",
    lead: "Noen ganger er det ikke hele profilen — det er én omtale som er urettferdig eller rett og slett falsk. Vi tar oss av akkurat den. Du betaler per fjernet omtale, ingenting på forskudd.",
    price: "179 €", per: "per fjernet omtale",
    priceNote: "Når du bestiller, registrerer du et kort eller PayPal. Ingenting trekkes på forhånd – hver omtale belastes først når den faktisk er borte. Blir den liggende, betaler du ingenting for den.",
    condNote: "Priser per fjernet anmeldelse: anmeldelser med tekst opptil 4 uker gamle 179 € (ca. 90 % sjanse for å lykkes), eldre anmeldelser 229 € (ca. 50 %). Komplekse tilfeller koster 300 €: vurderinger uten tekst og anmeldelser fra USA som er eldre enn 4 uker (300 $), fordi de krever en mer omfattende prosedyre. I enkelte tilfeller kan en eldre anmeldelse som fortsatt er synlig etter standardprosedyren, bli et komplekst tilfelle – vi fortsetter bare med ditt samtykke. Mengderabatt: fra 3 anmeldelser −10 %, fra 5 −15 %, fra 10 −30 %. Hver anmeldelse belastes først etter at den er fjernet.",
    cta: "Send oss omtalen",
    assure: ["Ingenting på forskudd", "Betal per fjernet omtale", "Først en ærlig vurdering"],
    stepsEyebrow: "Slik fungerer det", stepsH: "Tre steg, ikke noe papirarbeid.",
    steps: [
      { t: "Velg omtalene dine", d: "Søk opp bedriften din — vi laster inn de nyeste Google-anmeldelsene. Huk av dem som skal bort, eller lim inn lenkene." },
      { t: "Vi ser på den", d: "Noen fra teamet vårt leser omtalen og sier ærlig om vi kan fjerne den." },
      { t: "Borte — da betaler du", d: "Fjernes omtalen, belastes beløpet på kortet eller PayPal-kontoen du har registrert: 179 € for en ny omtale. Blir den stående, betaler du ingenting." },
    ],
    honestyEyebrow: "Ærlig talt", honestyH: "Hva vi kan fjerne — og hva vi ikke kan.",
    yesH: "Gode sjanser", noH: "Det lover vi ikke",
    yes: ["Falske omtaler og angrep fra konkurrenter", "Omtaler fra folk som aldri var kunder", "Fornærmelser og usanne påstander", "Omtaler som bryter Googles regler", "Vurderinger uten tekst, bare stjerner (komplekst tilfelle)"],
    no: ["Ærlig kritikk fra ekte kunder", "En garanti for enhver omtale — det kan ingen gi"],
    formEyebrow: "Gratis vurdering", formH: "Send oss omtalen.",
    formSub: "Du får et ærlig svar: ja vi kan, eller nei vi kan ikke. Gratis uansett.",
    how: { eyebrow: "Hvor finner jeg lenken?", h: "Å kopiere lenken tar ti sekunder.", steps: ["Finn omtalen på Google-profilen din og trykk på den for å åpne den.", "Trykk på deleikonet under omtalen.", "Kopier lenken og lim den inn i skjemaet — én per omtale, så mange du vil."], alt: "Ingen delemulighet? Oppgi da anmelderens navn og omtalens tekst — det identifiserer den like godt.", copyHint: "Klikk for å kopiere lenken", shareT: "Del omtale", copied: "Kopiert" },
    faqEyebrow: "Spørsmål", faqH: "Godt å vite.",
    faq: [
      { q: "Hvor lang tid tar det?", a: "Vanligvis 1–2 uker, noen ganger raskere, i enkelte tilfeller litt lenger. Anmeldelser uten tekst via vår spesialprogramvare: ca. 1–3 dager. Vi holder deg oppdatert." },
      { q: "Hva om omtalen ikke kan fjernes?", a: "Da betaler du ingenting. Vurderer vi sjansene som små, sier vi det med en gang." },
      { q: "Får anmelderen vite at det var meg?", a: "Nei. Anmelderen får ikke vite hvem som ba om fjerningen." },
      { q: "Jeg har flere omtaler.", a: "Prisen gjelder per omtale — velg så mange du vil. Fra 3 anmeldelser −10 %, fra 5 −15 % og fra 10 −30 %. Du betaler bare for dem som faktisk fjernes." },
    ],
    finalH: "Én omtale bør ikke definere bedriften din.",
    finalCta: "Send oss omtalen",
    demoRemoved: "Fjernet",
    demoName: "Din bedrift",
  },
};

// SEO-Ausbau (Okt 2026) der übrigen Sprachen einmischen (h1, faq, Richtlinien, Ablauf, Vergleich …).
for (const src of [RVW_SEO_A, RVW_SEO_B]) for (const l of Object.keys(src)) Object.assign(RVW[l], src[l]);
