/* Fortschritt + Zwischenzahlung (Einzelbewertungen, 08.10.2026): Texte für die Update-Mail bei jeder Löschung,
 * die freundlichen Erinnerungen während der Bearbeitung und den Zahlungsstopp ab der Schwelle (PAY_HOLD_AMOUNT).
 * Platzhalter: {r} gelöscht, {n} gesamt, {k} pausiert, {a} Betrag. */
type L = "de" | "en" | "es" | "fr" | "it" | "nl" | "pt" | "ja" | "sv" | "da" | "no";
interface P { good: string; removed: string; inProgress: string; waiting: string; due: string; pay: string; hint: string; hold: string; holdSubj: string; holdTitle: string; progSubj: string; progTitle: string; progP: string }
const T: Record<L, P> = {
  en: { good: "Good news – {r} of your {n} reviews removed so far.", removed: "removed", inProgress: "in progress", waiting: "waiting for your decision", due: "Amount due for removed reviews", pay: "Pay now", hint: "You only pay for reviews that are actually removed – new removals are simply added to the amount.", hold: "Interim payment needed: we've paused the remaining {k} reviews and will continue as soon as this payment arrives.", holdSubj: "Interim payment needed – {a} open", holdTitle: "Interim payment needed", progSubj: "Your order update: {r} of {n} removed – {a} open", progTitle: "Your order update", progP: "Here's where your order stands." },
  de: { good: "Gute Nachricht – bisher {r} von {n} Bewertungen gelöscht.", removed: "gelöscht", inProgress: "in Bearbeitung", waiting: "warten auf Ihre Entscheidung", due: "Offen für gelöschte Bewertungen", pay: "Jetzt bezahlen", hint: "Sie zahlen nur für tatsächlich gelöschte Bewertungen – neue Löschungen kommen einfach zum Betrag dazu.", hold: "Zwischenzahlung nötig: Wir haben die restlichen {k} Bewertungen pausiert und machen weiter, sobald diese Zahlung eingegangen ist.", holdSubj: "Zwischenzahlung nötig – {a} offen", holdTitle: "Zwischenzahlung nötig", progSubj: "Ihr Auftrag: {r} von {n} gelöscht – {a} offen", progTitle: "Stand Ihres Auftrags", progP: "So steht Ihr Auftrag gerade." },
  es: { good: "Buenas noticias: ya se han eliminado {r} de tus {n} reseñas.", removed: "eliminadas", inProgress: "en curso", waiting: "esperan tu decisión", due: "Importe pendiente por reseñas eliminadas", pay: "Pagar ahora", hint: "Solo pagas por las reseñas realmente eliminadas; las nuevas eliminaciones se suman al importe.", hold: "Pago parcial necesario: hemos pausado las {k} reseñas restantes y seguiremos en cuanto recibamos este pago.", holdSubj: "Pago parcial necesario – {a} pendiente", holdTitle: "Pago parcial necesario", progSubj: "Tu pedido: {r} de {n} eliminadas – {a} pendiente", progTitle: "Estado de tu pedido", progP: "Así va tu pedido." },
  fr: { good: "Bonne nouvelle – {r} de tes {n} avis déjà supprimés.", removed: "supprimés", inProgress: "en cours", waiting: "attendent ta décision", due: "Montant dû pour les avis supprimés", pay: "Payer maintenant", hint: "Tu ne paies que les avis réellement supprimés – les nouvelles suppressions s’ajoutent simplement au montant.", hold: "Paiement intermédiaire nécessaire : nous avons mis en pause les {k} avis restants et reprenons dès réception de ce paiement.", holdSubj: "Paiement intermédiaire nécessaire – {a} dû", holdTitle: "Paiement intermédiaire nécessaire", progSubj: "Ta commande : {r} sur {n} supprimés – {a} dû", progTitle: "Point sur ta commande", progP: "Voici où en est ta commande." },
  it: { good: "Buone notizie: finora {r} delle tue {n} recensioni sono state rimosse.", removed: "rimosse", inProgress: "in lavorazione", waiting: "attendono la tua decisione", due: "Importo dovuto per le recensioni rimosse", pay: "Paga ora", hint: "Paghi solo le recensioni effettivamente rimosse – le nuove rimozioni si aggiungono semplicemente all’importo.", hold: "Pagamento intermedio necessario: abbiamo messo in pausa le {k} recensioni restanti e riprendiamo appena arriva questo pagamento.", holdSubj: "Pagamento intermedio necessario – {a} da pagare", holdTitle: "Pagamento intermedio necessario", progSubj: "Il tuo ordine: {r} di {n} rimosse – {a} da pagare", progTitle: "Stato del tuo ordine", progP: "Ecco a che punto è il tuo ordine." },
  nl: { good: "Goed nieuws – tot nu toe {r} van uw {n} reviews verwijderd.", removed: "verwijderd", inProgress: "in behandeling", waiting: "wachten op uw beslissing", due: "Openstaand voor verwijderde reviews", pay: "Nu betalen", hint: "U betaalt alleen voor reviews die echt zijn verwijderd – nieuwe verwijderingen komen er gewoon bij.", hold: "Tussentijdse betaling nodig: we hebben de overige {k} reviews gepauzeerd en gaan verder zodra deze betaling binnen is.", holdSubj: "Tussentijdse betaling nodig – {a} open", holdTitle: "Tussentijdse betaling nodig", progSubj: "Uw opdracht: {r} van {n} verwijderd – {a} open", progTitle: "Stand van uw opdracht", progP: "Zo staat uw opdracht ervoor." },
  pt: { good: "Boas notícias – até agora foram removidas {r} das tuas {n} avaliações.", removed: "removidas", inProgress: "em curso", waiting: "aguardam a tua decisão", due: "Valor em dívida pelas avaliações removidas", pay: "Pagar agora", hint: "Só pagas as avaliações realmente removidas – as novas remoções somam-se ao valor.", hold: "Pagamento intermédio necessário: pausámos as {k} avaliações restantes e continuamos assim que este pagamento chegar.", holdSubj: "Pagamento intermédio necessário – {a} em dívida", holdTitle: "Pagamento intermédio necessário", progSubj: "A tua encomenda: {r} de {n} removidas – {a} em dívida", progTitle: "Ponto da tua encomenda", progP: "Eis o ponto da tua encomenda." },
  ja: { good: "朗報です。{n}件中{r}件の口コミが削除されました。", removed: "削除済み", inProgress: "対応中", waiting: "ご判断待ち", due: "削除済み口コミの未払い額", pay: "今すぐ支払う", hint: "実際に削除された口コミ分のみのお支払いです。新たに削除された分は金額に加算されます。", hold: "中間支払いが必要です：残り{k}件の対応を一時停止しています。お支払いを確認次第、再開します。", holdSubj: "中間支払いのお願い – 未払い{a}", holdTitle: "中間支払いのお願い", progSubj: "ご依頼の状況：{n}件中{r}件削除 – 未払い{a}", progTitle: "ご依頼の状況", progP: "現在のご依頼状況です。" },
  sv: { good: "Goda nyheter – hittills har {r} av dina {n} omdömen tagits bort.", removed: "borttagna", inProgress: "pågår", waiting: "väntar på ditt beslut", due: "Att betala för borttagna omdömen", pay: "Betala nu", hint: "Du betalar bara för omdömen som faktiskt tagits bort – nya borttagningar läggs till beloppet.", hold: "Delbetalning krävs: vi har pausat de återstående {k} omdömena och fortsätter så snart betalningen kommit in.", holdSubj: "Delbetalning krävs – {a} obetalt", holdTitle: "Delbetalning krävs", progSubj: "Din beställning: {r} av {n} borttagna – {a} obetalt", progTitle: "Status för din beställning", progP: "Så här ligger din beställning till." },
  da: { good: "Gode nyheder – indtil nu er {r} af dine {n} anmeldelser fjernet.", removed: "fjernet", inProgress: "i gang", waiting: "venter på din beslutning", due: "Skyldigt for fjernede anmeldelser", pay: "Betal nu", hint: "Du betaler kun for anmeldelser, der faktisk er fjernet – nye fjernelser lægges blot til beløbet.", hold: "Delbetaling nødvendig: vi har sat de resterende {k} anmeldelser på pause og fortsætter, så snart betalingen er modtaget.", holdSubj: "Delbetaling nødvendig – {a} udestående", holdTitle: "Delbetaling nødvendig", progSubj: "Din ordre: {r} af {n} fjernet – {a} udestående", progTitle: "Status på din ordre", progP: "Sådan står din ordre lige nu." },
  no: { good: "Gode nyheter – så langt er {r} av {n} omtaler fjernet.", removed: "fjernet", inProgress: "pågår", waiting: "venter på din beslutning", due: "Utestående for fjernede omtaler", pay: "Betal nå", hint: "Du betaler bare for omtaler som faktisk er fjernet – nye fjerninger legges til beløpet.", hold: "Delbetaling nødvendig: vi har satt de resterende {k} omtalene på pause og fortsetter så snart betalingen er mottatt.", holdSubj: "Delbetaling nødvendig – {a} utestående", holdTitle: "Delbetaling nødvendig", progSubj: "Bestillingen din: {r} av {n} fjernet – {a} utestående", progTitle: "Status for bestillingen din", progP: "Slik står bestillingen din nå." },
};
export const progT = (lang?: string): P => T[(lang && lang in T ? lang : "en") as L];
export const fillP = (s: string, v: { r?: number; n?: number; k?: number; a?: string }) =>
  s.replace("{r}", String(v.r ?? "")).replace("{n}", String(v.n ?? "")).replace("{k}", String(v.k ?? "")).replace("{a}", v.a ?? "");
/** Fortschritt eines Bewertungs-Auftrags (aus der Dashboard-Ansicht). */
export type Progress = { total: number; removed: number; inProgress: number; waiting: number; due: number; cur: string; hold?: boolean };
