/* Template: Hinweis zum Schutzmodell – Upsell nach Einmal-Löschung (DE/EN).
   3 Varianten für eine Serie über ~2 Wochen (Tag 0 / 7 / 14):
     variant 1 = Erstansprache (Wortlaut 1:1 aus make.com Module 43/44),
     variant 2 = freundliches Nachfassen,
     variant 3 = letzte Erinnerung.
   Wird nach einer Einmalzahlung ohne Abo verschickt und bewirbt den
   monatlichen Schutz. */
import * as React from "react";
import { EmailShell, P, A, NoteBox, CtaButton } from "./components";
import { Section } from "@react-email/components";

export interface SchutzhinweisProps { lang?: "de" | "en" | "es" | "fr" | "it" | "nl" | "pt" | "ja" | "sv" | "da" | "no"; variant?: 1 | 2 | 3; protectionUrl?: string; }

/** Bestehende Stripe-Zahlungslinks für den monatlichen Schutz (24,90 €/$24.90). */
const PROTECTION_URL = {
  de: "https://buy.stripe.com/3cs3fN2RS5lE9Z6dRi",
  en: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  es: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  fr: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  it: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  nl: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  pt: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  ja: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  sv: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  da: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
  no: "https://buy.stripe.com/3cs7w3css15o6MU7t5",
};
const GOOGLE_HELP = {
  de: "https://support.google.com/maps/answer/6320846?hl=de&co=GENIE.Platform%3DDesktop",
  en: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  es: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  fr: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  it: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  nl: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  pt: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  ja: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  sv: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  da: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
  no: "https://support.google.com/maps/answer/6320846?hl=en&co=GENIE.Platform%3DDesktop",
};
const PHONE_DISPLAY = "+43 6245 93053 00";
const PHONE_TEL = "+4362459305300";

interface Copy {
  title: string; preview: string; greeting: string; p1: string; p2: string;
  noteA: string; noteB: string; noteLink: string; noteC: string;
  offer: string; cta: string; price: string;
  questionsA: string; questionsB: string; signoff1: string; signoff2: string; subject: string;
}

const QUESTIONS_DE = { questionsA: "Wenn es noch Fragen gibt, bitte jederzeit gerne antworten oder telefonisch unter ", questionsB: " 😉", signoff1: "Liebe Grüße aus Salzburg", signoff2: "Maximilian Hölzl" };
const QUESTIONS_EN = { questionsA: "If you have any further questions, please feel free to reply", questionsB: " 😉", signoff1: "Best regards from Salzburg,", signoff2: "Max from RapidRemove" };
const QUESTIONS_ES = { questionsA: "Si tiene alguna otra pregunta, no dude en responder", questionsB: " 😉", signoff1: "Un cordial saludo desde Salzburgo,", signoff2: "Max de RapidRemove" };
const QUESTIONS_FR = { questionsA: "Si vous avez d'autres questions, n'hésitez pas à répondre", questionsB: " 😉", signoff1: "Cordialement depuis Salzbourg,", signoff2: "Max de RapidRemove" };
const QUESTIONS_IT = { questionsA: "Se ha altre domande, non esiti a rispondere", questionsB: " 😉", signoff1: "Cordiali saluti da Salisburgo,", signoff2: "Max di RapidRemove" };
const QUESTIONS_NL = { questionsA: "Mocht u nog vragen hebben, beantwoord dan gerust deze e-mail", questionsB: " 😉", signoff1: "Hartelijke groeten uit Salzburg,", signoff2: "Max van RapidRemove" };
const QUESTIONS_PT = { questionsA: "Se tiver mais alguma questão, não hesite em responder", questionsB: " 😉", signoff1: "Com os melhores cumprimentos de Salzburgo,", signoff2: "Max da RapidRemove" };
const QUESTIONS_JA = { questionsA: "ご不明な点がございましたら、お気軽にご返信ください", questionsB: " 😉", signoff1: "ザルツブルクより", signoff2: "RapidRemove マックス" };
const QUESTIONS_SV = { questionsA: "Om du har fler frågor är du välkommen att svara", questionsB: " 😉", signoff1: "Vänliga hälsningar från Salzburg,", signoff2: "Max från RapidRemove" };
const QUESTIONS_DA = { questionsA: "Hvis du har flere spørgsmål, er du velkommen til at svare", questionsB: " 😉", signoff1: "Med venlig hilsen fra Salzburg,", signoff2: "Max fra RapidRemove" };
const QUESTIONS_NO = { questionsA: "Hvis du har flere spørsmål, er du velkommen til å svare", questionsB: " 😉", signoff1: "Vennlig hilsen fra Salzburg,", signoff2: "Max fra RapidRemove" };

const T: Record<"de" | "en" | "es" | "fr" | "it" | "nl" | "pt" | "ja" | "sv" | "da" | "no", Copy[]> = {
  de: [
    {
      title: "Hinweis zum Schutz Ihres Profils",
      preview: "Das Profil wurde entfernt – so schützen Sie sich vor erneutem Auftauchen.",
      greeting: "Guten Tag,",
      p1: "vielen Dank für die rasche Bezahlung. Ein Hinweis meinerseits noch …",
      p2: "Das Profil wurde vollständig entfernt und kann so auch nicht mehr auftauchen.",
      noteA: "Aber: ",
      noteB: "Dritte, Kunden, Mitarbeiter etc. können theoretisch jederzeit wieder ein neues Profil einstellen – das liegt an der Offenheit des Google-Systems (",
      noteLink: "siehe hier",
      noteC: ").",
      offer: "Falls Sie auch dagegen geschützt sein möchten, bieten wir eine Schutz-Lösung an, die dann sofort aktiv ist:",
      cta: "Schutz jetzt buchen",
      price: "Der Schutz kostet 24,90 € pro Monat und verhindert bei Wiederauftauchen, dass die Löschung erneut bezahlt werden muss. Das Abo ist jederzeit kündbar.",
      ...QUESTIONS_DE,
      subject: "Hinweis zum Schutzmodell",
    },
    {
      title: "Schon an den Schutz gedacht?",
      preview: "Kurze Erinnerung – so verhindern Sie, dass Ihr Profil erneut auftaucht.",
      greeting: "Guten Tag,",
      p1: "ich wollte mich kurz noch einmal melden. Ihre Löschung ist erledigt – das Profil ist aktuell verschwunden.",
      p2: "Erfahrungsgemäß werden gelöschte Einträge aber oft innerhalb weniger Wochen erneut angelegt: durch Mitbewerber, ehemalige Mitarbeiter oder automatisch durch Google.",
      noteA: "Wichtig: ",
      noteB: "Taucht das Profil ohne Schutz wieder auf, fällt erneut die volle Löschgebühr an. Mit unserem Schutzmodell übernehmen wir jede weitere Entfernung für Sie – das liegt an der Offenheit des Google-Systems (",
      noteLink: "siehe hier",
      noteC: ").",
      offer: "Mit dem monatlichen Schutz sind Sie ab sofort auf der sicheren Seite:",
      cta: "Schutz aktivieren",
      price: "Der Schutz kostet 24,90 € pro Monat, ist jederzeit kündbar – und Sie zahlen nie wieder für eine erneute Löschung.",
      ...QUESTIONS_DE,
      subject: "Ist Ihr Profil schon geschützt?",
    },
    {
      title: "Letzte Erinnerung zum Profilschutz",
      preview: "Ihr Eintrag ist aktuell ohne Schutz – danach lasse ich Sie damit in Ruhe.",
      greeting: "Guten Tag,",
      p1: "das ist meine letzte Erinnerung zum Thema Schutz – danach lasse ich Sie damit in Ruhe 😊.",
      p2: "Ihr Profil wurde erfolgreich entfernt, ist momentan aber nicht gegen ein erneutes Auftauchen abgesichert.",
      noteA: "Zur Erinnerung: ",
      noteB: "Sollte der Eintrag wieder erscheinen, müssten Sie die Löschung erneut beauftragen und bezahlen. Genau das nimmt Ihnen das Schutzmodell ab – Hintergrund zum Google-System (",
      noteLink: "hier",
      noteC: ").",
      offer: "Wenn Sie dauerhaft Ruhe haben möchten, aktivieren Sie den Schutz hier:",
      cta: "Jetzt absichern",
      price: "24,90 € pro Monat, jederzeit kündbar. Bei erneutem Auftauchen übernehmen wir die Löschung für Sie kostenlos.",
      ...QUESTIONS_DE,
      subject: "Letzte Erinnerung: Profil noch ungeschützt",
    },
  ],
  en: [
    {
      title: "A note on protecting your profile",
      preview: "Your profile has been removed – here's how to stay protected.",
      greeting: "Hello again,",
      p1: "thank you very much for the prompt payment. Just one more note from my side …",
      p2: "The profile has been completely removed and cannot reappear in its current form.",
      noteA: "However: ",
      noteB: "Third parties, customers, employees, etc. could theoretically create a new profile at any time, due to the openness of the Google system (",
      noteLink: "see here",
      noteC: ").",
      offer: "If you would like to be protected against this as well, we offer a protection solution that becomes active immediately:",
      cta: "Book protection now",
      price: "This protection costs $24.90 per month and ensures that if the profile reappears, you will not have to pay for deletion again. The subscription can be canceled at any time.",
      ...QUESTIONS_EN,
      subject: "Important: No protection plan booked",
    },
    {
      title: "Have you considered protection yet?",
      preview: "A quick reminder – here's how to stop your profile from reappearing.",
      greeting: "Hello again,",
      p1: "I just wanted to follow up briefly. Your deletion is complete – the profile is currently gone.",
      p2: "In our experience, however, deleted entries are often re-created within a few weeks: by competitors, former employees, or automatically by Google.",
      noteA: "Important: ",
      noteB: "If the profile reappears without protection, the full deletion fee applies again. With our protection plan we take care of every further removal for you – this is due to the openness of the Google system (",
      noteLink: "see here",
      noteC: ").",
      offer: "With the monthly protection you're on the safe side from now on:",
      cta: "Activate protection",
      price: "Protection costs $24.90 per month, can be canceled at any time – and you'll never pay for another deletion again.",
      ...QUESTIONS_EN,
      subject: "Is your profile protected yet?",
    },
    {
      title: "Last reminder about protecting your profile",
      preview: "Your listing is currently unprotected – then I'll leave you in peace.",
      greeting: "Hello again,",
      p1: "this is my last reminder about protection – after this I'll leave you in peace 😊.",
      p2: "Your profile has been removed successfully, but it is currently not protected against reappearing.",
      noteA: "As a reminder: ",
      noteB: "Should the entry show up again, you would have to order and pay for the deletion once more. That's exactly what the protection plan takes off your plate – background on the Google system (",
      noteLink: "here",
      noteC: ").",
      offer: "If you'd like lasting peace of mind, activate protection here:",
      cta: "Protect my profile",
      price: "$24.90 per month, cancel anytime. If the profile reappears, we'll remove it again free of charge.",
      ...QUESTIONS_EN,
      subject: "Last reminder: your profile is still unprotected",
    },
  ],
  es: [
    {
      title: "Una nota sobre la protección de su perfil",
      preview: "Su perfil ha sido eliminado: así puede mantenerse protegido.",
      greeting: "Buenos días:",
      p1: "muchas gracias por el rápido pago. Permítame solo un apunte más…",
      p2: "El perfil se ha eliminado por completo y, por tanto, ya no puede volver a aparecer en su forma actual.",
      noteA: "Sin embargo: ",
      noteB: "terceros, clientes, empleados, etc., podrían, en teoría, crear un nuevo perfil en cualquier momento, debido a la apertura del sistema de Google (",
      noteLink: "ver aquí",
      noteC: ").",
      offer: "Si desea estar protegido también frente a esto, le ofrecemos una solución de protección que se activa de inmediato:",
      cta: "Contratar la protección ahora",
      price: "La protección cuesta 24,90 € al mes y evita que, si el perfil vuelve a aparecer, tenga que pagar de nuevo por la eliminación. La suscripción puede cancelarse en cualquier momento.",
      ...QUESTIONS_ES,
      subject: "Aviso sobre el modelo de protección",
    },
    {
      title: "¿Ya ha pensado en la protección?",
      preview: "Un breve recordatorio: así evita que su perfil vuelva a aparecer.",
      greeting: "Buenos días:",
      p1: "quería ponerme en contacto con usted brevemente una vez más. Su eliminación está finalizada: el perfil ha desaparecido por el momento.",
      p2: "Sin embargo, la experiencia demuestra que las entradas eliminadas suelen recrearse en pocas semanas: por competidores, antiguos empleados o automáticamente por Google.",
      noteA: "Importante: ",
      noteB: "si el perfil vuelve a aparecer sin protección, se aplica de nuevo la tarifa completa de eliminación. Con nuestro modelo de protección nos encargamos por usted de cada nueva eliminación, debido a la apertura del sistema de Google (",
      noteLink: "ver aquí",
      noteC: ").",
      offer: "Con la protección mensual estará en el lado seguro a partir de ahora:",
      cta: "Activar la protección",
      price: "La protección cuesta 24,90 € al mes, puede cancelarse en cualquier momento, y nunca volverá a pagar por otra eliminación.",
      ...QUESTIONS_ES,
      subject: "¿Su perfil ya está protegido?",
    },
    {
      title: "Último recordatorio sobre la protección de su perfil",
      preview: "Su ficha está actualmente sin protección; después le dejaré tranquilo.",
      greeting: "Buenos días:",
      p1: "este es mi último recordatorio sobre la protección; después le dejaré tranquilo 😊.",
      p2: "Su perfil se ha eliminado correctamente, pero por el momento no está protegido frente a una nueva aparición.",
      noteA: "Como recordatorio: ",
      noteB: "si la entrada volviera a aparecer, tendría que solicitar y pagar la eliminación de nuevo. Eso es precisamente lo que le evita el modelo de protección; información de fondo sobre el sistema de Google (",
      noteLink: "aquí",
      noteC: ").",
      offer: "Si desea tranquilidad duradera, active aquí la protección:",
      cta: "Protegerme ahora",
      price: "24,90 € al mes, cancelable en cualquier momento. Si el perfil vuelve a aparecer, lo eliminamos de nuevo sin coste alguno.",
      ...QUESTIONS_ES,
      subject: "Último recordatorio: su perfil sigue sin protección",
    },
  ],
  fr: [
    {
      title: "Une note sur la protection de votre profil",
      preview: "Votre profil a été supprimé : voici comment rester protégé.",
      greeting: "Bonjour,",
      p1: "merci beaucoup pour ce paiement rapide. Juste une remarque de ma part…",
      p2: "Le profil a été entièrement supprimé et ne peut donc plus réapparaître sous sa forme actuelle.",
      noteA: "Cependant : ",
      noteB: "des tiers, des clients, des employés, etc. pourraient en théorie créer un nouveau profil à tout moment, en raison de l'ouverture du système Google (",
      noteLink: "voir ici",
      noteC: ").",
      offer: "Si vous souhaitez être également protégé contre cela, nous proposons une solution de protection qui s'active immédiatement :",
      cta: "Réserver la protection",
      price: "La protection coûte 24,90 € par mois et évite, en cas de réapparition du profil, d'avoir à payer une nouvelle fois la suppression. L'abonnement est résiliable à tout moment.",
      ...QUESTIONS_FR,
      subject: "Information sur le modèle de protection",
    },
    {
      title: "Avez-vous déjà pensé à la protection ?",
      preview: "Un bref rappel : voici comment empêcher votre profil de réapparaître.",
      greeting: "Bonjour,",
      p1: "je voulais simplement revenir brièvement vers vous. Votre suppression est terminée : le profil a disparu pour le moment.",
      p2: "L'expérience montre toutefois que les fiches supprimées sont souvent recréées en quelques semaines : par des concurrents, d'anciens employés ou automatiquement par Google.",
      noteA: "Important : ",
      noteB: "si le profil réapparaît sans protection, les frais de suppression complets s'appliquent à nouveau. Avec notre modèle de protection, nous prenons en charge pour vous chaque nouvelle suppression, en raison de l'ouverture du système Google (",
      noteLink: "voir ici",
      noteC: ").",
      offer: "Avec la protection mensuelle, vous êtes désormais du bon côté :",
      cta: "Activer la protection",
      price: "La protection coûte 24,90 € par mois, est résiliable à tout moment, et vous ne paierez plus jamais pour une nouvelle suppression.",
      ...QUESTIONS_FR,
      subject: "Votre profil est-il déjà protégé ?",
    },
    {
      title: "Dernier rappel concernant la protection de votre profil",
      preview: "Votre fiche est actuellement sans protection ; ensuite je vous laisse tranquille.",
      greeting: "Bonjour,",
      p1: "c'est mon dernier rappel au sujet de la protection ; ensuite, je vous laisse tranquille 😊.",
      p2: "Votre profil a bien été supprimé, mais il n'est pour l'instant pas protégé contre une réapparition.",
      noteA: "Pour rappel : ",
      noteB: "si la fiche venait à réapparaître, vous devriez commander et payer la suppression une nouvelle fois. C'est précisément ce dont le modèle de protection vous décharge ; contexte sur le système Google (",
      noteLink: "ici",
      noteC: ").",
      offer: "Si vous souhaitez une tranquillité durable, activez la protection ici :",
      cta: "Protéger mon profil",
      price: "24,90 € par mois, résiliable à tout moment. En cas de réapparition du profil, nous le supprimons à nouveau gratuitement.",
      ...QUESTIONS_FR,
      subject: "Dernier rappel : votre profil n'est toujours pas protégé",
    },
  ],
  it: [
    {
      title: "Una nota sulla protezione del suo profilo",
      preview: "Il suo profilo è stato rimosso: ecco come restare protetto.",
      greeting: "Buongiorno,",
      p1: "la ringrazio molto per il rapido pagamento. Solo un'ulteriore nota da parte mia…",
      p2: "Il profilo è stato completamente rimosso e quindi non può più ricomparire nella sua forma attuale.",
      noteA: "Tuttavia: ",
      noteB: "terzi, clienti, dipendenti, ecc. potrebbero in teoria creare un nuovo profilo in qualsiasi momento, a causa dell'apertura del sistema di Google (",
      noteLink: "vedi qui",
      noteC: ").",
      offer: "Se desidera essere protetto anche da questo, le offriamo una soluzione di protezione che si attiva immediatamente:",
      cta: "Attiva subito la protezione",
      price: "La protezione costa 24,90 € al mese ed evita che, in caso di ricomparsa del profilo, debba pagare nuovamente la rimozione. L'abbonamento è disdicibile in qualsiasi momento.",
      ...QUESTIONS_IT,
      subject: "Informazioni sul modello di protezione",
    },
    {
      title: "Ha già pensato alla protezione?",
      preview: "Un breve promemoria: ecco come impedire che il suo profilo ricompaia.",
      greeting: "Buongiorno,",
      p1: "volevo ricontattarla brevemente. La sua rimozione è completata: al momento il profilo è scomparso.",
      p2: "L'esperienza dimostra però che le schede rimosse vengono spesso ricreate nel giro di poche settimane: da concorrenti, ex dipendenti o automaticamente da Google.",
      noteA: "Importante: ",
      noteB: "se il profilo ricompare senza protezione, viene nuovamente addebitato l'intero costo della rimozione. Con il nostro modello di protezione ci occupiamo noi di ogni ulteriore rimozione per lei, a causa dell'apertura del sistema di Google (",
      noteLink: "vedi qui",
      noteC: ").",
      offer: "Con la protezione mensile, da ora è al sicuro:",
      cta: "Attiva la protezione",
      price: "La protezione costa 24,90 € al mese, è disdicibile in qualsiasi momento e non pagherà mai più per un'ulteriore rimozione.",
      ...QUESTIONS_IT,
      subject: "Il suo profilo è già protetto?",
    },
    {
      title: "Ultimo promemoria sulla protezione del suo profilo",
      preview: "La sua scheda è attualmente senza protezione; dopo non la disturbo più.",
      greeting: "Buongiorno,",
      p1: "questo è il mio ultimo promemoria sul tema della protezione; dopo non la disturbo più 😊.",
      p2: "Il suo profilo è stato rimosso con successo, ma al momento non è protetto contro una ricomparsa.",
      noteA: "Per ricordarle: ",
      noteB: "se la scheda dovesse ricomparire, dovrebbe ordinare e pagare nuovamente la rimozione. È proprio questo che il modello di protezione le risparmia; informazioni sul sistema di Google (",
      noteLink: "qui",
      noteC: ").",
      offer: "Se desidera una tranquillità duratura, attivi qui la protezione:",
      cta: "Proteggi il mio profilo",
      price: "24,90 € al mese, disdicibile in qualsiasi momento. In caso di ricomparsa del profilo, lo rimuoviamo di nuovo gratuitamente.",
      ...QUESTIONS_IT,
      subject: "Ultimo promemoria: il suo profilo è ancora senza protezione",
    },
  ],
  nl: [
    {
      title: "Een opmerking over de bescherming van uw profiel",
      preview: "Uw profiel is verwijderd – zo blijft u beschermd.",
      greeting: "Goedendag,",
      p1: "hartelijk dank voor de snelle betaling. Nog één opmerking van mijn kant…",
      p2: "Het profiel is volledig verwijderd en kan in zijn huidige vorm dan ook niet meer verschijnen.",
      noteA: "Maar: ",
      noteB: "derden, klanten, medewerkers enz. kunnen in theorie op elk moment een nieuw profiel aanmaken, vanwege de openheid van het Google-systeem (",
      noteLink: "zie hier",
      noteC: ").",
      offer: "Als u ook hiertegen beschermd wilt zijn, bieden wij een beschermingsoplossing die meteen actief is:",
      cta: "Nu bescherming boeken",
      price: "De bescherming kost 24,90 € per maand en voorkomt dat u bij heropduiken opnieuw voor de verwijdering moet betalen. Het abonnement is op elk moment opzegbaar.",
      ...QUESTIONS_NL,
      subject: "Informatie over het beschermingsmodel",
    },
    {
      title: "Al aan bescherming gedacht?",
      preview: "Een korte herinnering – zo voorkomt u dat uw profiel opnieuw verschijnt.",
      greeting: "Goedendag,",
      p1: "ik wilde nog even contact met u opnemen. Uw verwijdering is voltooid – het profiel is momenteel verdwenen.",
      p2: "De ervaring leert echter dat verwijderde vermeldingen vaak binnen enkele weken opnieuw worden aangemaakt: door concurrenten, voormalige medewerkers of automatisch door Google.",
      noteA: "Belangrijk: ",
      noteB: "verschijnt het profiel zonder bescherming opnieuw, dan worden de volledige verwijderingskosten weer in rekening gebracht. Met ons beschermingsmodel nemen wij elke verdere verwijdering voor u op ons, vanwege de openheid van het Google-systeem (",
      noteLink: "zie hier",
      noteC: ").",
      offer: "Met de maandelijkse bescherming bent u vanaf nu aan de veilige kant:",
      cta: "Bescherming activeren",
      price: "De bescherming kost 24,90 € per maand, is op elk moment opzegbaar – en u betaalt nooit meer voor een nieuwe verwijdering.",
      ...QUESTIONS_NL,
      subject: "Is uw profiel al beschermd?",
    },
    {
      title: "Laatste herinnering over de bescherming van uw profiel",
      preview: "Uw vermelding is momenteel onbeschermd – daarna laat ik u met rust.",
      greeting: "Goedendag,",
      p1: "dit is mijn laatste herinnering over het onderwerp bescherming – daarna laat ik u ermee met rust 😊.",
      p2: "Uw profiel is succesvol verwijderd, maar is momenteel niet beschermd tegen opnieuw verschijnen.",
      noteA: "Ter herinnering: ",
      noteB: "mocht de vermelding opnieuw verschijnen, dan zou u de verwijdering opnieuw moeten aanvragen en betalen. Precies dat neemt het beschermingsmodel u uit handen; achtergrond over het Google-systeem (",
      noteLink: "hier",
      noteC: ").",
      offer: "Wilt u blijvende rust, activeer dan hier de bescherming:",
      cta: "Mijn profiel beschermen",
      price: "24,90 € per maand, op elk moment opzegbaar. Verschijnt het profiel opnieuw, dan verwijderen wij het kosteloos opnieuw.",
      ...QUESTIONS_NL,
      subject: "Laatste herinnering: uw profiel is nog onbeschermd",
    },
  ],
  pt: [
    {
      title: "Uma nota sobre a proteção do seu perfil",
      preview: "O seu perfil foi removido – eis como manter-se protegido.",
      greeting: "Bom dia,",
      p1: "muito obrigado pelo pagamento rápido. Apenas mais uma nota da minha parte…",
      p2: "O perfil foi completamente removido e, por isso, já não pode voltar a aparecer na sua forma atual.",
      noteA: "No entanto: ",
      noteB: "terceiros, clientes, colaboradores, etc. poderiam, em teoria, criar um novo perfil a qualquer momento, devido à abertura do sistema do Google (",
      noteLink: "ver aqui",
      noteC: ").",
      offer: "Se quiser estar protegido também contra isso, oferecemos uma solução de proteção que fica ativa de imediato:",
      cta: "Contratar a proteção agora",
      price: "A proteção custa 24,90 € por mês e evita que, caso o perfil reapareça, tenha de pagar novamente pela remoção. A subscrição pode ser cancelada a qualquer momento.",
      ...QUESTIONS_PT,
      subject: "Informação sobre o modelo de proteção",
    },
    {
      title: "Já pensou na proteção?",
      preview: "Um breve lembrete – eis como impedir que o seu perfil reapareça.",
      greeting: "Bom dia,",
      p1: "queria apenas voltar a contactá-lo brevemente. A sua remoção está concluída – o perfil desapareceu de momento.",
      p2: "A experiência mostra, no entanto, que as fichas removidas são muitas vezes recriadas em poucas semanas: por concorrentes, antigos colaboradores ou automaticamente pelo Google.",
      noteA: "Importante: ",
      noteB: "se o perfil reaparecer sem proteção, é novamente cobrada a taxa total de remoção. Com o nosso modelo de proteção, encarregamo-nos de cada nova remoção por si, devido à abertura do sistema do Google (",
      noteLink: "ver aqui",
      noteC: ").",
      offer: "Com a proteção mensal, fica a partir de agora do lado seguro:",
      cta: "Ativar a proteção",
      price: "A proteção custa 24,90 € por mês, pode ser cancelada a qualquer momento – e nunca mais pagará por uma nova remoção.",
      ...QUESTIONS_PT,
      subject: "O seu perfil já está protegido?",
    },
    {
      title: "Último lembrete sobre a proteção do seu perfil",
      preview: "A sua ficha está atualmente sem proteção – depois deixo-o em paz.",
      greeting: "Bom dia,",
      p1: "este é o meu último lembrete sobre o tema da proteção – depois disso, deixo-o em paz 😊.",
      p2: "O seu perfil foi removido com sucesso, mas de momento não está protegido contra um reaparecimento.",
      noteA: "Para lembrar: ",
      noteB: "caso a ficha volte a aparecer, teria de solicitar e pagar a remoção novamente. É precisamente isso que o modelo de proteção lhe poupa; contexto sobre o sistema do Google (",
      noteLink: "aqui",
      noteC: ").",
      offer: "Se quiser tranquilidade duradoura, ative aqui a proteção:",
      cta: "Proteger o meu perfil",
      price: "24,90 € por mês, cancelável a qualquer momento. Se o perfil reaparecer, removemo-lo novamente sem qualquer custo.",
      ...QUESTIONS_PT,
      subject: "Último lembrete: o seu perfil ainda está desprotegido",
    },
  ],
  ja: [
    {
      title: "プロフィールの保護に関するお知らせ",
      preview: "プロフィールは削除されました。再表示を防ぐ方法をご案内します。",
      greeting: "こんにちは。",
      p1: "迅速なお支払いをいただき、誠にありがとうございます。一点だけお知らせがございます…",
      p2: "プロフィールは完全に削除されたため、現在の形で再び表示されることはありません。",
      noteA: "ただし、",
      noteB: "Googleのシステムがオープンな仕組みであるため、第三者・顧客・従業員などが理論上いつでも新しいプロフィールを作成できてしまいます（",
      noteLink: "こちらをご覧ください",
      noteC: "）。",
      offer: "これにも備えて保護をご希望の場合は、お申し込み後すぐに有効となる保護サービスをご用意しております。",
      cta: "今すぐ保護を申し込む",
      price: "保護は月額24,90 €で、再表示された場合に削除費用を再度お支払いいただく必要がなくなります。サブスクリプションはいつでも解約可能です。",
      ...QUESTIONS_JA,
      subject: "保護モデルに関するお知らせ",
    },
    {
      title: "保護についてもうご検討いただけましたか？",
      preview: "簡単なリマインドです。プロフィールの再表示を防ぐ方法をご案内します。",
      greeting: "こんにちは。",
      p1: "あらためて簡単にご連絡いたします。削除は完了し、現在プロフィールは表示されなくなっています。",
      p2: "ただ経験上、削除された掲載は数週間以内に再び作成されることがよくあります。競合他社や元従業員によって、あるいはGoogleによって自動的に作成される場合もあります。",
      noteA: "重要：",
      noteB: "保護がない状態でプロフィールが再表示されると、再び削除費用の全額が発生します。当社の保護モデルなら、その後の削除はすべて当社が代行いたします。これはGoogleのシステムがオープンな仕組みであるためです（",
      noteLink: "こちらをご覧ください",
      noteC: "）。",
      offer: "月額の保護にご加入いただければ、これからは安心です。",
      cta: "保護を有効にする",
      price: "保護は月額24,90 €、いつでも解約可能で、今後再び削除費用をお支払いいただくことはありません。",
      ...QUESTIONS_JA,
      subject: "プロフィールはもう保護されていますか？",
    },
    {
      title: "プロフィール保護に関する最後のご案内",
      preview: "現在お客様の掲載は保護されていません。本件のご連絡はこれが最後です。",
      greeting: "こんにちは。",
      p1: "保護に関するご連絡はこれで最後です。これ以降、本件でお手間を取らせることはございません😊。",
      p2: "お客様のプロフィールは正常に削除されましたが、現在は再表示に対して保護されていません。",
      noteA: "念のため：",
      noteB: "掲載が再び表示された場合、削除を改めて依頼し、お支払いいただく必要があります。まさにその手間を保護モデルが肩代わりいたします。Googleのシステムに関する背景はこちら（",
      noteLink: "こちら",
      noteC: "）。",
      offer: "末永く安心をご希望の場合は、こちらから保護を有効にしてください。",
      cta: "今すぐ保護する",
      price: "月額24,90 €、いつでも解約可能です。プロフィールが再表示された場合は、無料で再度削除いたします。",
      ...QUESTIONS_JA,
      subject: "最後のご案内：プロフィールはまだ保護されていません",
    },
  ],
  sv: [
    {
      title: "En notis om skyddet av din profil",
      preview: "Din profil har tagits bort – så här förblir du skyddad.",
      greeting: "God dag,",
      p1: "tack så mycket för den snabba betalningen. Bara en notis till från min sida…",
      p2: "Profilen har tagits bort helt och kan därmed inte längre dyka upp i sin nuvarande form.",
      noteA: "Men: ",
      noteB: "tredje parter, kunder, anställda osv. skulle i teorin kunna skapa en ny profil när som helst, på grund av öppenheten i Googles system (",
      noteLink: "se här",
      noteC: ").",
      offer: "Om du vill vara skyddad även mot detta erbjuder vi en skyddslösning som aktiveras omedelbart:",
      cta: "Boka skydd nu",
      price: "Skyddet kostar 24,90 € per månad och förhindrar att du, om profilen dyker upp igen, måste betala för borttagningen på nytt. Abonnemanget kan sägas upp när som helst.",
      ...QUESTIONS_SV,
      subject: "Information om skyddsmodellen",
    },
    {
      title: "Har du redan tänkt på skyddet?",
      preview: "En kort påminnelse – så här hindrar du din profil från att dyka upp igen.",
      greeting: "God dag,",
      p1: "jag ville bara höra av mig kort igen. Din borttagning är klar – profilen är för närvarande borta.",
      p2: "Erfarenheten visar dock att borttagna poster ofta återskapas inom några veckor: av konkurrenter, tidigare anställda eller automatiskt av Google.",
      noteA: "Viktigt: ",
      noteB: "om profilen dyker upp igen utan skydd tillkommer hela borttagningsavgiften på nytt. Med vår skyddsmodell tar vi hand om varje ytterligare borttagning åt dig, på grund av öppenheten i Googles system (",
      noteLink: "se här",
      noteC: ").",
      offer: "Med det månatliga skyddet är du på den säkra sidan från och med nu:",
      cta: "Aktivera skydd",
      price: "Skyddet kostar 24,90 € per månad, kan sägas upp när som helst – och du betalar aldrig mer för ännu en borttagning.",
      ...QUESTIONS_SV,
      subject: "Är din profil redan skyddad?",
    },
    {
      title: "Sista påminnelsen om skyddet av din profil",
      preview: "Din notering är för närvarande oskyddad – sedan lämnar jag dig i fred.",
      greeting: "God dag,",
      p1: "det här är min sista påminnelse om skyddet – sedan lämnar jag dig i fred 😊.",
      p2: "Din profil har tagits bort, men är för närvarande inte skyddad mot att dyka upp igen.",
      noteA: "Som påminnelse: ",
      noteB: "skulle noteringen dyka upp igen skulle du behöva beställa och betala för borttagningen på nytt. Det är precis det som skyddsmodellen tar bort från dina axlar; bakgrund om Googles system (",
      noteLink: "här",
      noteC: ").",
      offer: "Om du vill ha varaktig trygghet, aktivera skyddet här:",
      cta: "Skydda min profil",
      price: "24,90 € per månad, kan sägas upp när som helst. Om profilen dyker upp igen tar vi bort den på nytt utan kostnad.",
      ...QUESTIONS_SV,
      subject: "Sista påminnelsen: din profil är fortfarande oskyddad",
    },
  ],
  da: [
    {
      title: "En bemærkning om beskyttelsen af din profil",
      preview: "Din profil er blevet fjernet – sådan forbliver du beskyttet.",
      greeting: "Goddag,",
      p1: "mange tak for den hurtige betaling. Blot en enkelt bemærkning fra min side…",
      p2: "Profilen er blevet fjernet fuldstændigt og kan derfor ikke længere dukke op i sin nuværende form.",
      noteA: "Men: ",
      noteB: "tredjeparter, kunder, medarbejdere osv. kan i teorien til enhver tid oprette en ny profil, hvilket skyldes åbenheden i Googles system (",
      noteLink: "se her",
      noteC: ").",
      offer: "Hvis du også ønsker at være beskyttet mod dette, tilbyder vi en beskyttelsesløsning, der aktiveres med det samme:",
      cta: "Book beskyttelse nu",
      price: "Beskyttelsen koster 24,90 € om måneden og forhindrer, at du ved genoptræden skal betale for fjernelsen igen. Abonnementet kan opsiges til enhver tid.",
      ...QUESTIONS_DA,
      subject: "Information om beskyttelsesmodellen",
    },
    {
      title: "Har du allerede tænkt på beskyttelse?",
      preview: "En kort påmindelse – sådan forhindrer du, at din profil dukker op igen.",
      greeting: "Goddag,",
      p1: "jeg ville lige vende kort tilbage igen. Din fjernelse er gennemført – profilen er for øjeblikket forsvundet.",
      p2: "Erfaringen viser dog, at slettede opslag ofte oprettes igen inden for få uger: af konkurrenter, tidligere medarbejdere eller automatisk af Google.",
      noteA: "Vigtigt: ",
      noteB: "dukker profilen op igen uden beskyttelse, påløber det fulde fjernelsesgebyr på ny. Med vores beskyttelsesmodel tager vi os af enhver yderligere fjernelse for dig, hvilket skyldes åbenheden i Googles system (",
      noteLink: "se her",
      noteC: ").",
      offer: "Med den månedlige beskyttelse er du på den sikre side fra nu af:",
      cta: "Aktivér beskyttelse",
      price: "Beskyttelsen koster 24,90 € om måneden, kan opsiges til enhver tid – og du betaler aldrig igen for endnu en fjernelse.",
      ...QUESTIONS_DA,
      subject: "Er din profil allerede beskyttet?",
    },
    {
      title: "Sidste påmindelse om beskyttelsen af din profil",
      preview: "Dit opslag er for øjeblikket ubeskyttet – derefter lader jeg dig være i fred.",
      greeting: "Goddag,",
      p1: "dette er min sidste påmindelse om beskyttelse – derefter lader jeg dig være i fred med det 😊.",
      p2: "Din profil er blevet fjernet, men er for øjeblikket ikke beskyttet mod at dukke op igen.",
      noteA: "Til erindring: ",
      noteB: "skulle opslaget dukke op igen, ville du skulle bestille og betale for fjernelsen endnu en gang. Det er præcis det, beskyttelsesmodellen tager fra dig; baggrund om Googles system (",
      noteLink: "her",
      noteC: ").",
      offer: "Hvis du ønsker varig ro, så aktivér beskyttelsen her:",
      cta: "Beskyt min profil",
      price: "24,90 € om måneden, kan opsiges til enhver tid. Dukker profilen op igen, fjerner vi den igen uden beregning.",
      ...QUESTIONS_DA,
      subject: "Sidste påmindelse: din profil er stadig ubeskyttet",
    },
  ],
  no: [
    {
      title: "En merknad om beskyttelsen av profilen din",
      preview: "Profilen din er fjernet – slik forblir du beskyttet.",
      greeting: "God dag,",
      p1: "tusen takk for den raske betalingen. Bare en liten merknad fra min side…",
      p2: "Profilen er fjernet fullstendig og kan derfor ikke lenger dukke opp i sin nåværende form.",
      noteA: "Men: ",
      noteB: "tredjeparter, kunder, ansatte osv. kan i teorien når som helst opprette en ny profil, noe som skyldes åpenheten i Googles system (",
      noteLink: "se her",
      noteC: ").",
      offer: "Hvis du også ønsker å være beskyttet mot dette, tilbyr vi en beskyttelsesløsning som aktiveres umiddelbart:",
      cta: "Bestill beskyttelse nå",
      price: "Beskyttelsen koster 24,90 € per måned og forhindrer at du må betale for fjerningen på nytt dersom profilen dukker opp igjen. Abonnementet kan sies opp når som helst.",
      ...QUESTIONS_NO,
      subject: "Informasjon om beskyttelsesmodellen",
    },
    {
      title: "Har du allerede tenkt på beskyttelse?",
      preview: "En kort påminnelse – slik hindrer du at profilen din dukker opp igjen.",
      greeting: "God dag,",
      p1: "jeg ville bare ta kort kontakt igjen. Fjerningen din er fullført – profilen er for øyeblikket borte.",
      p2: "Erfaringen viser imidlertid at slettede oppføringer ofte opprettes på nytt i løpet av få uker: av konkurrenter, tidligere ansatte eller automatisk av Google.",
      noteA: "Viktig: ",
      noteB: "dukker profilen opp igjen uten beskyttelse, påløper hele fjerningsgebyret på nytt. Med beskyttelsesmodellen vår tar vi oss av enhver videre fjerning for deg, noe som skyldes åpenheten i Googles system (",
      noteLink: "se her",
      noteC: ").",
      offer: "Med den månedlige beskyttelsen er du på den sikre siden fra nå av:",
      cta: "Aktiver beskyttelse",
      price: "Beskyttelsen koster 24,90 € per måned, kan sies opp når som helst – og du betaler aldri mer for en ny fjerning.",
      ...QUESTIONS_NO,
      subject: "Er profilen din allerede beskyttet?",
    },
    {
      title: "Siste påminnelse om beskyttelsen av profilen din",
      preview: "Oppføringen din er for øyeblikket ubeskyttet – deretter lar jeg deg være i fred.",
      greeting: "God dag,",
      p1: "dette er min siste påminnelse om beskyttelse – deretter lar jeg deg være i fred med det 😊.",
      p2: "Profilen din er fjernet, men er for øyeblikket ikke beskyttet mot å dukke opp igjen.",
      noteA: "Til påminnelse: ",
      noteB: "skulle oppføringen dukke opp igjen, måtte du bestille og betale for fjerningen på nytt. Det er nettopp det beskyttelsesmodellen tar fra deg; bakgrunn om Googles system (",
      noteLink: "her",
      noteC: ").",
      offer: "Hvis du ønsker varig ro, aktiver beskyttelsen her:",
      cta: "Beskytt profilen min",
      price: "24,90 € per måned, kan sies opp når som helst. Dukker profilen opp igjen, fjerner vi den på nytt uten kostnad.",
      ...QUESTIONS_NO,
      subject: "Siste påminnelse: profilen din er fortsatt ubeskyttet",
    },
  ],
};

const pick = (lang?: string, variant?: number) => {
  const l = (lang && Object.prototype.hasOwnProperty.call(T, lang) ? lang : "de") as keyof typeof T;
  const v = Math.min(3, Math.max(1, Number(variant) || 1)) - 1;
  return { l, t: T[l][v] };
};

export function subject(p: SchutzhinweisProps = {}): string {
  return pick(p.lang, p.variant).t.subject;
}

export default function Schutzhinweis({ lang = "de", variant = 1, protectionUrl }: SchutzhinweisProps = {}) {
  const { l, t } = pick(lang, variant);
  const payUrl = protectionUrl || PROTECTION_URL[l];
  return (
    <EmailShell preview={t.preview} title={t.title} lang={l}>
      <P><strong>{t.greeting}</strong></P>
      <P>{t.p1}</P>
      <P>{t.p2}</P>
      <NoteBox>
        <strong>{t.noteA}</strong>{t.noteB}<A href={GOOGLE_HELP[l]}>{t.noteLink}</A>{t.noteC}
      </NoteBox>
      <P>{t.offer}</P>
      <Section style={{ margin: "18px 0 8px" }}>
        <CtaButton href={payUrl} full>{t.cta}</CtaButton>
      </Section>
      <P muted>{t.price}</P>
      <P>
        {l === "de"
          ? <>{t.questionsA}<A href={`tel:${PHONE_TEL}`}>{PHONE_DISPLAY}</A>{t.questionsB}</>
          : <>{t.questionsA}{t.questionsB}</>}
      </P>
      <P>{t.signoff1}<br />{t.signoff2}</P>
    </EmailShell>
  );
}
