/* Texte des Kunden-Dashboards (Einzelbewertungen) — 10 Sprachen, kein Deutsch (Produkt nicht in DACH). */
export const DASH_TXT = {
  en: {
    title: "My reviews", sub: "Live status of your review removals.", login: "Log in", email: "Email", password: "Password",
    forgot: "Forgot your password?", sendNew: "Send me a new password", sentNew: "If an account exists for this email, we've just sent a new password.",
    wrong: "Wrong email or password.", tooMany: "Too many attempts – please wait a few minutes.", logout: "Log out", order: "Order", noOrders: "No review orders yet.",
    open: "Open review", noText: "no text", payH: "Payments", pay: "Pay now", paid: "Paid ✓",
    kinds: { deposit: "Deposit – reviews without text", software: "Deposit – special software", invoice: "Invoice – removed reviews" },
    st: { checking: "Being checked", in_progress: "In progress", removed: "Removed ✓", not_removable: "Not removable", software_offer: "Possible with special software", software_in_progress: "In progress (special software)", cancelled: "Cancelled" },
    hint: { checking: "We're checking whether this review can be removed.", software_offer: "Pay the special-software deposit above to get started.", not_removable: "This review can't be removed – you won't be charged for it." },
    sum: (r, t) => `${r} of ${t} removed`, help: "Questions? Just reply to any of our emails or write to helpdesk@rapid-remove.com.",
  },
  es: {
    title: "Mis reseñas", sub: "Estado en directo de tus eliminaciones.", login: "Entrar", email: "Correo", password: "Contraseña",
    forgot: "¿Olvidaste la contraseña?", sendNew: "Enviarme una contraseña nueva", sentNew: "Si existe una cuenta con este correo, te acabamos de enviar una contraseña nueva.",
    wrong: "Correo o contraseña incorrectos.", tooMany: "Demasiados intentos: espera unos minutos.", logout: "Salir", order: "Pedido", noOrders: "Aún no hay pedidos de reseñas.",
    open: "Abrir reseña", noText: "sin texto", payH: "Pagos", pay: "Pagar ahora", paid: "Pagado ✓",
    kinds: { deposit: "Anticipo – reseñas sin texto", software: "Anticipo – software especial", invoice: "Factura – reseñas eliminadas" },
    st: { checking: "En revisión", in_progress: "En curso", removed: "Eliminada ✓", not_removable: "No se puede eliminar", software_offer: "Posible con software especial", software_in_progress: "En curso (software especial)", cancelled: "Cancelado" },
    hint: { checking: "Estamos comprobando si esta reseña se puede eliminar.", software_offer: "Paga arriba el anticipo del software especial para empezar.", not_removable: "Esta reseña no se puede eliminar: no se te cobrará." },
    sum: (r, t) => `${r} de ${t} eliminadas`, help: "¿Preguntas? Responde a cualquiera de nuestros correos o escribe a helpdesk@rapid-remove.com.",
  },
  fr: {
    title: "Mes avis", sub: "Le statut de tes suppressions en direct.", login: "Se connecter", email: "E-mail", password: "Mot de passe",
    forgot: "Mot de passe oublié ?", sendNew: "M'envoyer un nouveau mot de passe", sentNew: "Si un compte existe pour cet e-mail, nous venons d'envoyer un nouveau mot de passe.",
    wrong: "E-mail ou mot de passe incorrect.", tooMany: "Trop de tentatives – attends quelques minutes.", logout: "Se déconnecter", order: "Commande", noOrders: "Pas encore de commande d'avis.",
    open: "Ouvrir l'avis", noText: "sans texte", payH: "Paiements", pay: "Payer", paid: "Payé ✓",
    kinds: { deposit: "Acompte – avis sans texte", software: "Acompte – logiciel spécial", invoice: "Facture – avis supprimés" },
    st: { checking: "En vérification", in_progress: "En cours", removed: "Supprimé ✓", not_removable: "Non supprimable", software_offer: "Possible avec logiciel spécial", software_in_progress: "En cours (logiciel spécial)", cancelled: "Annulé" },
    hint: { checking: "Nous vérifions si cet avis peut être supprimé.", software_offer: "Paie l'acompte du logiciel spécial ci-dessus pour démarrer.", not_removable: "Cet avis ne peut pas être supprimé – il ne te sera pas facturé." },
    sum: (r, t) => `${r} sur ${t} supprimé(s)`, help: "Une question ? Réponds à l'un de nos e-mails ou écris à helpdesk@rapid-remove.com.",
  },
  it: {
    title: "Le mie recensioni", sub: "Lo stato delle rimozioni in tempo reale.", login: "Accedi", email: "E-mail", password: "Password",
    forgot: "Password dimenticata?", sendNew: "Inviami una nuova password", sentNew: "Se esiste un account per questa e-mail, ti abbiamo appena inviato una nuova password.",
    wrong: "E-mail o password errate.", tooMany: "Troppi tentativi – attendi qualche minuto.", logout: "Esci", order: "Ordine", noOrders: "Nessun ordine di recensioni.",
    open: "Apri recensione", noText: "senza testo", payH: "Pagamenti", pay: "Paga ora", paid: "Pagato ✓",
    kinds: { deposit: "Acconto – recensioni senza testo", software: "Acconto – software speciale", invoice: "Fattura – recensioni rimosse" },
    st: { checking: "In verifica", in_progress: "In corso", removed: "Rimossa ✓", not_removable: "Non rimovibile", software_offer: "Possibile con software speciale", software_in_progress: "In corso (software speciale)", cancelled: "Annullato" },
    hint: { checking: "Stiamo verificando se questa recensione può essere rimossa.", software_offer: "Paga qui sopra l'acconto del software speciale per iniziare.", not_removable: "Questa recensione non può essere rimossa: non ti verrà addebitata." },
    sum: (r, t) => `${r} di ${t} rimosse`, help: "Domande? Rispondi a una delle nostre e-mail o scrivi a helpdesk@rapid-remove.com.",
  },
  nl: {
    title: "Mijn reviews", sub: "Live status van uw verwijderingen.", login: "Inloggen", email: "E-mail", password: "Wachtwoord",
    forgot: "Wachtwoord vergeten?", sendNew: "Stuur mij een nieuw wachtwoord", sentNew: "Als er een account voor dit e-mailadres bestaat, hebben we zojuist een nieuw wachtwoord gestuurd.",
    wrong: "Onjuist e-mailadres of wachtwoord.", tooMany: "Te veel pogingen – wacht een paar minuten.", logout: "Uitloggen", order: "Bestelling", noOrders: "Nog geen reviewbestellingen.",
    open: "Review openen", noText: "zonder tekst", payH: "Betalingen", pay: "Nu betalen", paid: "Betaald ✓",
    kinds: { deposit: "Aanbetaling – reviews zonder tekst", software: "Aanbetaling – speciale software", invoice: "Factuur – verwijderde reviews" },
    st: { checking: "Wordt gecontroleerd", in_progress: "In behandeling", removed: "Verwijderd ✓", not_removable: "Niet te verwijderen", software_offer: "Mogelijk met speciale software", software_in_progress: "In behandeling (speciale software)", cancelled: "Geannuleerd" },
    hint: { checking: "We controleren of deze review verwijderd kan worden.", software_offer: "Betaal hierboven de aanbetaling voor de speciale software om te starten.", not_removable: "Deze review kan niet worden verwijderd – u betaalt er niets voor." },
    sum: (r, t) => `${r} van ${t} verwijderd`, help: "Vragen? Antwoord op een van onze e-mails of schrijf naar helpdesk@rapid-remove.com.",
  },
  pt: {
    title: "As minhas avaliações", sub: "Estado das remoções em tempo real.", login: "Entrar", email: "E-mail", password: "Palavra-passe",
    forgot: "Esqueceste a palavra-passe?", sendNew: "Enviar-me uma nova palavra-passe", sentNew: "Se existir uma conta com este e-mail, acabámos de enviar uma nova palavra-passe.",
    wrong: "E-mail ou palavra-passe incorretos.", tooMany: "Demasiadas tentativas – aguarda alguns minutos.", logout: "Sair", order: "Encomenda", noOrders: "Ainda não há encomendas de avaliações.",
    open: "Abrir avaliação", noText: "sem texto", payH: "Pagamentos", pay: "Pagar agora", paid: "Pago ✓",
    kinds: { deposit: "Sinal – avaliações sem texto", software: "Sinal – software especial", invoice: "Fatura – avaliações removidas" },
    st: { checking: "Em verificação", in_progress: "Em curso", removed: "Removida ✓", not_removable: "Não removível", software_offer: "Possível com software especial", software_in_progress: "Em curso (software especial)", cancelled: "Cancelado" },
    hint: { checking: "Estamos a verificar se esta avaliação pode ser removida.", software_offer: "Paga acima o sinal do software especial para começar.", not_removable: "Esta avaliação não pode ser removida – não te será cobrada." },
    sum: (r, t) => `${r} de ${t} removidas`, help: "Dúvidas? Responde a qualquer um dos nossos e-mails ou escreve para helpdesk@rapid-remove.com.",
  },
  ja: {
    title: "口コミ削除の状況", sub: "削除の進捗をリアルタイムで確認できます。", login: "ログイン", email: "メールアドレス", password: "パスワード",
    forgot: "パスワードをお忘れですか？", sendNew: "新しいパスワードを送信", sentNew: "このメールアドレスのアカウントがある場合、新しいパスワードをお送りしました。",
    wrong: "メールアドレスまたはパスワードが正しくありません。", tooMany: "試行回数が多すぎます。数分後にお試しください。", logout: "ログアウト", order: "ご注文", noOrders: "口コミのご注文はまだありません。",
    open: "口コミを開く", noText: "本文なし", payH: "お支払い", pay: "支払う", paid: "支払済み ✓",
    kinds: { deposit: "着手金 – 本文なしの口コミ", software: "着手金 – 特別ソフトウェア", invoice: "請求書 – 削除済みの口コミ" },
    st: { checking: "確認中", in_progress: "対応中", removed: "削除済み ✓", not_removable: "削除不可", software_offer: "特別ソフトウェアで削除可能", software_in_progress: "対応中（特別ソフトウェア）", cancelled: "キャンセル" },
    hint: { checking: "この口コミが削除可能か確認しています。", software_offer: "上の着手金をお支払いいただくと、特別ソフトウェアでの対応を開始します。", not_removable: "この口コミは削除できません。料金は発生しません。" },
    sum: (r, t) => `${t}件中${r}件削除`, help: "ご不明な点は、当社からのメールにご返信いただくか helpdesk@rapid-remove.com までご連絡ください。",
  },
  sv: {
    title: "Mina omdömen", sub: "Status för dina borttagningar i realtid.", login: "Logga in", email: "E-post", password: "Lösenord",
    forgot: "Glömt lösenordet?", sendNew: "Skicka ett nytt lösenord", sentNew: "Om det finns ett konto för den här e-postadressen har vi just skickat ett nytt lösenord.",
    wrong: "Fel e-post eller lösenord.", tooMany: "För många försök – vänta några minuter.", logout: "Logga ut", order: "Beställning", noOrders: "Inga beställningar av omdömen än.",
    open: "Öppna omdöme", noText: "utan text", payH: "Betalningar", pay: "Betala nu", paid: "Betald ✓",
    kinds: { deposit: "Handpenning – omdömen utan text", software: "Handpenning – särskild programvara", invoice: "Faktura – borttagna omdömen" },
    st: { checking: "Granskas", in_progress: "Pågår", removed: "Borttaget ✓", not_removable: "Kan inte tas bort", software_offer: "Möjligt med särskild programvara", software_in_progress: "Pågår (särskild programvara)", cancelled: "Avbruten" },
    hint: { checking: "Vi kontrollerar om omdömet kan tas bort.", software_offer: "Betala handpenningen för den särskilda programvaran ovan för att komma igång.", not_removable: "Omdömet kan inte tas bort – du debiteras inte för det." },
    sum: (r, t) => `${r} av ${t} borttagna`, help: "Frågor? Svara på något av våra mejl eller skriv till helpdesk@rapid-remove.com.",
  },
  da: {
    title: "Mine anmeldelser", sub: "Status for dine fjernelser i realtid.", login: "Log ind", email: "E-mail", password: "Adgangskode",
    forgot: "Glemt adgangskoden?", sendNew: "Send mig en ny adgangskode", sentNew: "Hvis der findes en konto til denne e-mail, har vi lige sendt en ny adgangskode.",
    wrong: "Forkert e-mail eller adgangskode.", tooMany: "For mange forsøg – vent et par minutter.", logout: "Log ud", order: "Bestilling", noOrders: "Ingen anmeldelsesbestillinger endnu.",
    open: "Åbn anmeldelse", noText: "uden tekst", payH: "Betalinger", pay: "Betal nu", paid: "Betalt ✓",
    kinds: { deposit: "Depositum – anmeldelser uden tekst", software: "Depositum – særlig software", invoice: "Faktura – fjernede anmeldelser" },
    st: { checking: "Bliver tjekket", in_progress: "I gang", removed: "Fjernet ✓", not_removable: "Kan ikke fjernes", software_offer: "Muligt med særlig software", software_in_progress: "I gang (særlig software)", cancelled: "Annulleret" },
    hint: { checking: "Vi tjekker, om anmeldelsen kan fjernes.", software_offer: "Betal depositummet for den særlige software ovenfor for at komme i gang.", not_removable: "Anmeldelsen kan ikke fjernes – du betaler ikke for den." },
    sum: (r, t) => `${r} af ${t} fjernet`, help: "Spørgsmål? Svar på en af vores mails eller skriv til helpdesk@rapid-remove.com.",
  },
  no: {
    title: "Mine omtaler", sub: "Status for fjerningene dine i sanntid.", login: "Logg inn", email: "E-post", password: "Passord",
    forgot: "Glemt passordet?", sendNew: "Send meg et nytt passord", sentNew: "Hvis det finnes en konto for denne e-postadressen, har vi nettopp sendt et nytt passord.",
    wrong: "Feil e-post eller passord.", tooMany: "For mange forsøk – vent noen minutter.", logout: "Logg ut", order: "Bestilling", noOrders: "Ingen omtalebestillinger ennå.",
    open: "Åpne omtale", noText: "uten tekst", payH: "Betalinger", pay: "Betal nå", paid: "Betalt ✓",
    kinds: { deposit: "Depositum – omtaler uten tekst", software: "Depositum – spesiell programvare", invoice: "Faktura – fjernede omtaler" },
    st: { checking: "Sjekkes", in_progress: "Pågår", removed: "Fjernet ✓", not_removable: "Kan ikke fjernes", software_offer: "Mulig med spesiell programvare", software_in_progress: "Pågår (spesiell programvare)", cancelled: "Avbrutt" },
    hint: { checking: "Vi sjekker om omtalen kan fjernes.", software_offer: "Betal depositumet for den spesielle programvaren ovenfor for å komme i gang.", not_removable: "Omtalen kan ikke fjernes – du betaler ikke for den." },
    sum: (r, t) => `${r} av ${t} fjernet`, help: "Spørsmål? Svar på en av e-postene våre eller skriv til helpdesk@rapid-remove.com.",
  },
};
export const dashLang = (l) => (DASH_TXT[l] ? l : "en");
